PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:pauthor/^:pauthor)|(:pauthor/^:pfriendOf/^:peditor)|(:pauthor/:pfriendOf/^:pauthor))){,3} ?x1 . ?x0 (((:pauthor/:pfollows/^:pfollows/:psubscribes)|(:peditor/:plike/^:plike/:psubscribes)|(:pauthor/:pfollows/^:pfollows/:phomepage))){,3} ?x2 . ?x1 (((:pauthor/:plike/^:plike/:phomepage)|(:peditor/:pfollows/^:partist/:phomepage)|(:pauthor/:plike/^:plike/:phomepage))){,3} ?x3 . } }
