PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pbirthDate/:plocation)|(^:pvalidThrough/:pserialNumber/^:pcontentSize/:pperformedIn)) ?x1 . ?x0 ((^:pvalidForm/:peligibleQuantity/^:popus/:pperformedIn)|(^:pexpires/:pperformedIn)|(^:pexpires/:ptext/^:pgivenName/:plocation)) ?x2 . ?x1 ((^:pbirthDate/:plocation)|(^:pvalidThrough/:peditor/^:pparentContry)|(^:pbirthDate/:plocation)) ?x3 . } }
