PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:peditor/^:previewer/^:phasReview)|(:phomepage/^:psubscribes/^:peditor))){,3} ?x1 . ?x1 ((:pauthor/:pfriendOf/^:pemployee/:poffers)|(:peditor/:plike/^:pincludes)) ?x2 . ?x0 (((:pauthor/^:pfollows/^:peditor)|(^:plike/^:pauthor)|(^:plike/:pmakesPurchase/:ppurchaseFor))){,3} ?x3 . ?x2 (((^:plike/^:partist/^:plike/^:peditor)|(^:plike/^:pauthor))){,3} ?x4 . } }
