PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:plike/^:plike/^:previewer)|(:plike/:pauthor/^:pfollows/^:previewer)|(:plike/^:plike/^:peditor/:phasReview)) ?x1 . ?x1 (((^:phasReview/:phasReview))){,3} ?x2 . ?x2 (((:previewer/^:pdirector/:phasReview))){,3} ?x3 . ?x3 ((^:phasReview/:partist/^:partist)|(:previewer/:pfollows/^:partist)) ?x4 . } }
