PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((^:phomepage/:phomepage/^:ptrailer/:phomepage)|(^:psubscribes/^:pauthor/:phomepage)|(^:ptrailer/:ptrailer))){,3} ?x1 . ?x0 (((^:phomepage/:phomepage)|(^:ptrailer/:phasReview/^:phasReview/:phomepage))){,3} ?x2 . ?x0 (((^:phomepage/:phomepage/^:ptrailer/:phomepage)|(^:phomepage/:phomepage))){,3} ?x3 . } }
