PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:ptrailer/^:pincludes/:pincludes/:phomepage)|(^:psubscribes/^:pfriendOf/^:pauthor/:phomepage)|(^:psubscribes/^:pfriendOf/:phomepage))){,3} ?x1 . ?x1 ((^:phomepage/^:partist/:phasReview)|(^:psubscribes/^:pfollows/^:previewer)) ?x2 . ?x2 (((^:phasReview/:pconductor/^:previewer))){,3} ?x3 . } }
