PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:plocation/^:peditor/:phasGenre)|(^:plocation/:pgivenName/^:pcaption/:phasGenre)) ?x1 . ?x1 ((^:phasGenre/:pexpires/^:prelease/:pcontentSize)) ?x2 . ?x0 ((^:pperformedIn/:ptag)|(^:pperformedIn/:ptag)) ?x3 . ?x2 ((^:pperformedIn/:phasGenre/:ptag)) ?x4 . } }
