PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pcontentSize/:ptag)|(^:pcontentRating/:ptag/^:ptag/:ptag)|(^:popus/:phasGenre/:ptag)) ?x1 . ?x0 ((^:ptelephone/:ptelephone/^:pcontentRating/:ptag)|(^:ptelephone/^:pauthor/:ptag)|(^:popus/:ptag)) ?x2 . ?x0 ((^:pcontentRating/:ptag)|(^:pmovement/:pcaption/^:ptext/:ptag)) ?x3 . } }
