PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:plike/:phomepage/^:phomepage)|(^:pfriendOf/:pfriendOf/:pfollows/:plike)) ?x1 . ?x1 (((^:pincludes/:pincludes/^:pincludes/:pincludes))){,3} ?x2 . ?x0 ((^:peditor/:peditor/:pfriendOf)|(:psubscribes/^:psubscribes/:pfriendOf)|(:psubscribes/^:psubscribes/^:pfriendOf)) ?x3 . ?x2 ((^:pactor/:pactor/:psubscribes/^:psubscribes)) ?x4 . } }
