PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x3 ?x0 ?x2 WHERE {  {  ?x0 (((:pincludes/^:pincludes)|(:pincludes/:phasReview/^:phasReview/^:pincludes)|(:pincludes/:ptrailer/^:phomepage/^:pincludes))){,3} ?x1 . ?x1 (((:pincludes/^:pincludes)|(:pincludes/^:pincludes))){,3} ?x2 . ?x0 (((:pincludes/:phomepage/^:phomepage/^:pincludes))){,3} ?x3 . ?x2 (((:pincludes/:peditor/^:peditor/^:pincludes)|(:pincludes/:phasReview/^:phasReview/^:pincludes)|(:pincludes/:phasReview/^:phasReview/^:pincludes))){,3} ?x4 . } }
