PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:pauthor/^:pauthor)|(:pauthor/^:pactor/:phasReview/^:phasReview)|(:peditor/^:pfriendOf/^:peditor))){,3} ?x1 . ?x0 (((:phasReview/^:phasReview/:phomepage/^:phomepage)|(^:pincludes/:pincludes)|(^:ppurchaseFor/^:pmakesPurchase/^:pfriendOf/^:pauthor))){,3} ?x2 . ?x1 (((:pauthor/:pmakesPurchase/^:pmakesPurchase/^:pauthor)|(^:ppurchaseFor/:ppurchaseFor)|(:phasReview/^:phasReview))){,3} ?x3 . } }
