PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:phasReview/^:phasReview/:partist/:plike)|(:partist/:plike)) ?x1 . ?x1 (((:pconductor/^:previewer/:previewer/^:pconductor))){,3} ?x2 . ?x2 ((:pconductor/:pfollows)|(:pconductor/^:previewer/:previewer/:pfollows)|(^:ppurchaseFor/:ppurchaseFor/:partist)) ?x3 . } }
