PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:ppurchaseFor/^:ppurchaseFor))){,3} ?x1 . ?x0 (((:ppurchaseFor/^:ppurchaseFor))){,3} ?x2 . ?x0 (((^:pmakesPurchase/:pmakesPurchase)|(:ppurchaseFor/:peditor/:pmakesPurchase)|(:ppurchaseFor/^:ppurchaseFor))){,3} ?x3 . ?x0 (((:ppurchaseFor/:phomepage/^:phomepage/:pmakesPurchase))){,3} ?x4 . } }
