PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((:phomepage/^:phomepage/^:pconductor)|(:phasReview/^:phasReview)|(^:pincludes/:pincludes/:phasReview/^:phasReview)) ?x1 . ?x1 ((:pconductor/:pfriendOf/:plike)|(:pconductor/:plike)|(:phomepage/^:phomepage/:pconductor/:plike)) ?x2 . ?x0 ((:phasReview/^:phasReview/:phomepage)|(:phasReview/:previewer/:psubscribes)) ?x3 . ?x2 ((^:pincludes/:pincludes/:phomepage)|(:phomepage/^:phomepage/:phomepage)|(:phomepage/^:psubscribes/^:peditor/:phomepage)) ?x4 . } }
