PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 ?x3 WHERE {  {  ?x0 ((^:pnumberOfPages/^:ppurchaseFor)|(^:pcontentRating/^:ppurchaseFor)) ?x1 . ?x1 (((:ppurchaseFor/:pconductor/^:pconductor/^:ppurchaseFor)|(:ppurchaseFor/:pauthor/:pfriendOf/:pmakesPurchase)|(:ppurchaseFor/:pauthor/^:pauthor/^:ppurchaseFor))){,3} ?x2 . ?x2 (((:ppurchaseFor/^:ppurchaseFor))){,3} ?x3 . } }
