PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:ptype/:pfollows/:pgender)|(^:ptype/:pfamilyName/^:pgivenName/:pgender)|(^:ptype/:pgender)) ?x1 . ?x1 ((^:pgender/:pbirthDate)) ?x2 . ?x2 ((^:pvalidForm/:pprice/^:pcontentSize/:ptag)|(^:pbirthDate/^:pdirector/:ptag)|(^:prelease/:ptitle/^:pkeywords/:ptag)) ?x3 . ?x3 ((^:ptag/:prelease)) ?x4 . } }
