PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:ptype/:ptag)|(^:ptype/^:phasGenre/:phasGenre/:ptag)|(^:ptype/:ptag)) ?x1 . ?x0 ((^:ptype/^:phasGenre/:pperformedIn)|(^:ptype/^:phasGenre/:pperformedIn)|(^:ptype/^:phasGenre/:pperformedIn)) ?x2 . ?x1 ((^:ptype/^:phasGenre/:pperformedIn)|(^:ptype/:ptag/^:ptag/:pperformedIn)|(^:ptype/^:phasGenre/:pperformedIn)) ?x3 . } }
