PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pperformedIn/:pcomposer/^:ptitle/^:prelease/:pproducer/^:pkeywords)|(^:plocation/:plike/^:pexpires/:phomepage/^:phomepage)) ?x1 . ?x0 ((^:ppurchaseFor/:ppurchaseFor/^:pvalidThrough/:pincludes)|(^:ppurchaseFor/:ppurchaseFor/^:pvalidForm/:pincludes/:pkeywords/^:ptitle)) ?x2 . ?x0 ((^:pperformedIn/:phasReview/:prating/^:pdatePublished/^:ppurchaseFor/:pprice/^:pisbn)|(^:pbirthDate/^:peditor/:ptitle/^:ptext)|(^:pexpires/^:plike/:pemail/^:pkeywords)) ?x3 . }  UNION  {  } }
