PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x0 ?x1 WHERE {  {  ?x0 (((:pincludes/^:pincludes))){,3} ?x1 . ?x1 ((:pvalidThrough/^:prelease)|(:pincludes/:pdescription/^:pemail/:plike)|(:pvalidThrough/^:pexpires/:pdescription/^:pkeywords)) ?x2 . ?x0 (((:pincludes/:phomepage/^:phomepage/^:pincludes)|(:pincludes/^:pincludes))){,3} ?x3 . ?x3 (((:pincludes/^:pincludes)|(:pincludes/:phomepage/^:phomepage/^:pincludes))){,3} ?x2 . } }
