PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((^:pcontentSize/:phasGenre)|(^:pnumberOfPages/:pcaption/^:pcaption/:phasGenre)|(^:peligibleQuantity/:pserialNumber/^:pprintColumn/:phasGenre)) ?x1 . ?x1 ((^:phasGenre/:phomepage)|(^:phasGenre/:pcontentSize/^:pcontentRating/:phomepage)) ?x2 . ?x2 ((^:phomepage/^:pincludes/:ppriceValidUntil)|(:purl/^:pproducer/:prelease)) ?x3 . ?x3 ((^:pexpires/:peditor/:pbirthDate)|(^:pexpires/:prelease)|(^:pexpires/:peditor/:pbirthDate)) ?x4 . } }
