PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 (((:phomepage/^:phomepage/^:pactor)|(:phomepage/^:ptrailer)|(:pactor/^:pactor))){,3} ?x1 . ?x0 (((:pdirector/:psubscribes/^:ptrailer)|(:ptrailer/^:phomepage/:phasReview/^:phasReview)|(:pdirector/:pmakesPurchase/:ppurchaseFor))){,3} ?x2 . ?x2 (((:phasReview/^:phasReview/:phomepage/^:phomepage)|(:ptrailer/^:ptrailer)|(:pactor/^:pfriendOf/^:pdirector))){,3} ?x1 . } }
