PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 ((^:phasGenre/:pcontentSize/^:pcontentSize)|(^:phasGenre/:pduration/^:pduration)|(^:phasGenre/:pcontentSize/^:pduration)) ?x1 . ?x1 ((:pdirector/:plike/^:plike/:pmakesPurchase)|(:pdirector/:pfollows/^:pfollows/:pmakesPurchase)|(:pdirector/:pfollows/^:partist/^:ppurchaseFor)) ?x2 . ?x0 ((^:phasGenre/^:ppurchaseFor/:ppurchaseFor)) ?x3 . ?x2 ((^:phasGenre/:pauthor/^:pauthor)|(:ptag/^:ptag)) ?x4 . } }
