PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pcaption/^:pdescription/:ptitle/^:ptitle)|(:pdescription/^:pproducer)|(:ptext/^:paward)) ?x1 . ?x0 ((:peditor/:pfamilyName/^:pproducer)|(:pauthor/:pgivenName/^:pproducer)|(:ptext/^:ptext/^:phasReview)) ?x2 . ?x0 ((:pkeywords/^:pdescription)|(:phasReview/:ptitle/^:pkeywords)|(:phomepage/:purl/^:pdescription)) ?x3 . ?x0 ((:pcontentSize/^:puserId/^:pdirector)) ?x4 . } }
