PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 ?x2 ?x1 WHERE {  {  ?x0 ((:pincludes/:pwordCount/^:ptotalVotes)|(:peligibleQuantity/^:prating)) ?x1 . ?x0 ((:pvalidThrough/^:prelease/:pcaption/^:ptext)|(:pprice/^:pwordCount/:pcaption/^:ptitle)|(:pincludes/:pcaption/^:ptitle)) ?x2 . ?x0 ((:pincludes/:ptitle/^:ptitle)|(:ppriceValidUntil/^:pexpires/:pcomposer/^:ptitle)|(:peligibleQuantity/^:popus/:phasReview)) ?x3 . ?x0 ((:pincludes/:pcaption/^:pcaption/:phasReview)) ?x4 . } }
