PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:phasReview/:pactor/^:pdirector)) ?x1 . ?x0 ((^:phasReview/^:pincludes/:pincludes/^:ppurchaseFor)|(^:phasReview/^:ppurchaseFor)) ?x2 . ?x1 ((:previewer/:phomepage/^:phomepage/^:ppurchaseFor)|(^:phasReview/:phomepage/^:ptrailer/^:ppurchaseFor)) ?x3 . } }
