PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:plike/:pfriendOf/^:pactor)|(^:plike/^:pconductor/^:plike/^:pactor)) ?x1 . ?x0 ((^:ppurchaseFor/:ppurchaseFor/^:plike/^:pdirector)|(^:plike/^:pfollows/^:pfollows/^:pactor)) ?x2 . ?x0 ((^:plike/:psubscribes/^:ptrailer)|(^:plike/^:pactor)) ?x3 . ?x0 ((^:plike/^:pfriendOf/^:pdirector)|(^:plike/:pfriendOf/^:pdirector)|(^:plike/^:pfollows/^:pactor)) ?x4 . } }
