PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 (((^:ppurchaseFor/:ppurchaseFor/:phomepage/^:phomepage))){,3} ?x1 . ?x0 (((:pdescription/^:purl)|(:pkeywords/^:pkeywords/:ptrailer))){,3} ?x2 . ?x1 (((:pdescription/^:pdescription/:pauthor/:phomepage)|(:pcaption/^:pkeywords/:phomepage)|(:pdescription/^:pfamilyName/:phomepage))){,3} ?x3 . } }
