PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pdirector/:ptitle/^:pcaption/:pperformer)|(:pfriendOf/^:pfriendOf/^:pcontactPoint/:pemail)|(:pjobTitle/^:pcaption/:pdescription)) ?x1 . ?x1 ((^:pdescription/:pcontentSize/^:pserialNumber)) ?x2 . ?x2 (((:pincludes/:phomepage/^:phomepage/^:pincludes)|(:pincludes/:phomepage/^:phomepage/^:pincludes)|(:pincludes/^:pincludes))){,3} ?x3 . } }
