PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:planguage/:ptext/^:ptitle/:pnumberOfPages)) ?x1 . ?x0 ((^:planguage/:ptitle/^:ptitle/:pcontentSize)|(^:planguage/^:phomepage/:pcontentRating)|(^:planguage/:phasReview/:ptotalVotes)) ?x2 . ?x0 ((^:planguage/:pkeywords/^:ppublished/:pprintPage)|(^:planguage/:pcaption/^:pcaption/:pprintColumn)) ?x3 . } }
