PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pincludes/:pperformer/^:pdescription)|(:pincludes/:pconductor/:pbirthDate/^:pexpires)|(:pvalidForm/^:pbirthDate/:plike)) ?x1 . ?x1 (((:pconductor/^:pconductor)|(:phomepage/^:ptrailer/^:pincludes/:pincludes)|(:phasReview/^:phasReview/:phomepage/^:phomepage))){,3} ?x2 . ?x0 (((:pincludes/:pconductor/^:pdirector/^:pincludes))){,3} ?x3 . ?x3 (((:pincludes/:pauthor/^:pdirector/^:pincludes)|(:pincludes/:phasReview/^:phasReview/^:pincludes)|(:pincludes/^:pincludes/:pincludes/^:pincludes))){,3} ?x2 . } }
