PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:phasReview/:ptext/^:ptext)|(:ppublished/^:pemail/:plike)) ?x1 . ?x0 ((:pdescription/^:ptitle/^:ppurchaseFor/:ppurchaseFor)) ?x2 . ?x0 ((:pprintColumn/^:pduration)|(:pkeywords/^:ptitle/:pbookEdition/^:pduration)|(:ptext/^:ptext/:ptotalVotes/^:pduration)) ?x3 . ?x0 ((:pprintEdition/^:pcontentSize/:pcaption/^:paward)|(:ptext/^:paward)|(:pprintSection/^:pcontentSize/^:plike/:plike)) ?x4 . } }
