PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:ptitle/^:pproducer/:phasReview)|(:ptotalVotes/^:pcontentSize/:phasReview)) ?x1 . ?x0 (((^:phasReview/:phasReview)|(:previewer/^:previewer)|(^:phasReview/^:ppurchaseFor/:ppurchaseFor/:phasReview))){,3} ?x2 . ?x2 (((^:phasReview/:phomepage/^:psubscribes/^:previewer)|(^:phasReview/^:ppurchaseFor/:ppurchaseFor/:phasReview)|(^:phasReview/:phasReview/^:phasReview/:phasReview))){,3} ?x1 . } }
