PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:plike/^:previewer/^:phasReview/:phomepage)) ?x1 . ?x0 ((^:ppurchaseFor/:ppurchaseFor/^:plike/:phomepage)|(^:plike/:pfriendOf/^:pfollows/:phomepage)|(^:pincludes/:pincludes/^:plike/:psubscribes)) ?x2 . ?x0 ((:peditor/^:partist/:phomepage)) ?x3 . ?x0 ((^:plike/:psubscribes)) ?x4 . } }
