PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:ppurchaseFor/:ppurchaseFor/^:plike/:psubscribes)) ?x1 . ?x0 ((:peditor/^:pauthor/^:ppurchaseFor/:ppurchaseFor)) ?x2 . ?x1 ((:phomepage/^:psubscribes/^:pfriendOf/^:pauthor)|(^:ppurchaseFor/^:pmakesPurchase/^:pauthor)|(^:ppurchaseFor/:ppurchaseFor/:ptrailer/^:phomepage)) ?x3 . } }
