PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x1 ?x2 ?x0 WHERE {  {  ?x0 (((:pincludes/:pconductor/^:pdirector/^:pincludes))){,3} ?x1 . ?x0 (((:pprice/^:pcontentSize/^:pincludes/:peditor)|(:pincludes/:pauthor/:pnationality))){,3} ?x2 . ?x1 (((:peditor/^:pparentContry/:pparentContry)|(:pprice/^:pcontentRating/^:plike/:pnationality))){,3} ?x3 . } }
