PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pcaption/^:pdescription/:ptext/^:ptitle)|(:ptag/^:ptag/:ptext/^:pkeywords)|(:ptext/^:pcaption/:pcaption/^:pdescription)) ?x1 . ?x1 ((^:pincludes/:pincludes/:pauthor/:plike)|(:pdirector/:plike/:phomepage/^:phomepage)|(:phomepage/^:phomepage/:plike)) ?x2 . ?x0 ((:pauthor/^:peditor)) ?x3 . ?x2 ((^:ppurchaseFor/:ppurchaseFor/:phomepage/^:phomepage)) ?x4 . } }
