PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:pemail/^:pauthor)|(^:pgivenName/:plike/:pcontentSize/^:pwordCount)|(^:pjobTitle/^:pauthor)) ?x1 . ?x1 (((^:pincludes/:pincludes/:pactor/^:peditor)|(:pauthor/^:pfriendOf/^:pauthor)|(^:ppurchaseFor/:ppurchaseFor/^:pincludes/:pincludes))){,3} ?x2 . ?x2 (((^:pincludes/:pincludes/:phomepage/^:phomepage)|(^:pincludes/:pincludes)|(:phomepage/^:phomepage/^:peditor))){,3} ?x3 . } }
