PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:ptype/:pgender)|(^:ptype/^:pdirector/:pactor/:pgender)) ?x1 . ?x1 ((^:pgender/^:pactor/:phasGenre/:ptype)|(^:pgender/:plike/:phasGenre/:ptype)|(^:pgender/^:partist/:phasGenre/:ptype)) ?x2 . ?x0 ((^:ptype/:pfamilyName/^:ppaymentAccepted/:pcontactPoint)|(^:ptype/:pgivenName/^:ptext/:pauthor)) ?x3 . ?x3 ((:psubscribes/^:psubscribes/:pnationality)|(^:pfriendOf/:pnationality)|(:pjobTitle/^:ppaymentAccepted/:poffers/:peditor)) ?x2 . } }
