PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 (((^:phasReview/^:pincludes/:pincludes/:phasReview)|(^:phasReview/^:pincludes/:pincludes/:phasReview))){,3} ?x1 . ?x1 ((:previewer/^:pfollows/^:pcontactPoint)|(^:phasReview/^:plike/^:pemployee)) ?x2 . ?x2 (((:pcontactPoint/^:pemployee)|(:pemployee/:pfriendOf/^:pemployee))){,3} ?x3 . } }
