PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((^:pconductor/:pconductor))){,3} ?x1 . ?x1 ((^:partist/^:ppurchaseFor)|(:pfriendOf/^:pfollows/:pmakesPurchase)|(^:pfollows/:pmakesPurchase)) ?x2 . ?x2 (((:ppurchaseFor/:phomepage/^:phomepage/^:ppurchaseFor)|(:ppurchaseFor/:pauthor/:pmakesPurchase))){,3} ?x3 . } }
