PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 (((^:phomepage/:phomepage)|(^:phomepage/:phomepage)|(^:phomepage/:ptrailer))){,3} ?x1 . ?x1 (((^:psubscribes/:pfriendOf/:phomepage)|(^:phomepage/:pfriendOf/:phomepage)|(^:phomepage/:phomepage/^:phomepage/:psubscribes))){,3} ?x2 . ?x0 (((^:phomepage/^:ppurchaseFor/:ppurchaseFor/:phomepage))){,3} ?x3 . ?x2 (((^:phomepage/:phomepage)|(^:phomepage/:pmakesPurchase/:ppurchaseFor/:phomepage)|(^:phomepage/:phomepage))){,3} ?x4 . } }
