PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:planguage/:phasGenre)|(^:planguage/:ptag/^:ptag)) ?x1 . ?x1 ((^:phasGenre/:ptag)) ?x2 . ?x0 ((^:planguage/^:ptrailer/:phasGenre/:ptype)) ?x3 . ?x3 ((^:ptype/^:phasGenre/:pperformedIn)|(^:ptype/^:phasGenre/:pperformedIn)|(^:ptype/^:phasGenre/:pactor/:plocation)) ?x2 . } }
