PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pdatePublished/:pcontentRating/^:pcontentSize/:phomepage)|(^:pbirthDate/:pfriendOf/:phomepage)|(^:pexpires/:pexpires/^:pexpires/:phomepage)) ?x1 . ?x0 ((^:ppriceValidUntil/:pincludes/:phomepage)|(^:prelease/:phomepage)) ?x2 . ?x0 ((^:pexpires/:phomepage)|(^:pexpires/:phomepage)|(^:pexpires/:phomepage)) ?x3 . ?x0 ((^:ppurchaseDate/:ppurchaseFor/:pdescription/^:purl)) ?x4 . } }
