PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:partist/:plike/^:ppurchaseFor)|(:partist/^:peditor/^:ppurchaseFor)|(:partist/:plike/^:ppurchaseFor)) ?x1 . ?x1 (((:ppurchaseFor/:pauthor/^:pauthor/^:ppurchaseFor))){,3} ?x2 . ?x0 ((:partist/:plike/:phasReview/^:phasReview)) ?x3 . ?x2 ((:partist/:plike)) ?x4 . } }
