PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:pauthor/:pauthor))){,3} ?x1 . ?x0 (((:phomepage/^:psubscribes/^:pfriendOf)|(^:pfriendOf/:pfriendOf/^:pactor/:pactor)|(^:peditor/:pauthor/^:pfriendOf))){,3} ?x2 . ?x0 (((^:pactor/:ptrailer/^:psubscribes/:pfriendOf)|(^:pfriendOf/^:pfriendOf))){,3} ?x3 . } }
