PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:planguage/:peditor/:pbirthDate)|(^:planguage/^:phomepage/:pbirthDate)|(^:planguage/^:plike/^:peditor/:pdatePublished)) ?x1 . ?x1 ((^:prelease/:pcaption)) ?x2 . ?x0 ((^:planguage/^:phomepage/:ptype)|(^:planguage/:pdescription/^:pgivenName/:ptype)) ?x3 . ?x2 ((^:planguage/^:phomepage/:peditor/:ptype)) ?x4 . } }
