PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:ptag/:pcaption)|(^:ptag/:phasReview/^:phasReview/:paward)) ?x1 . ?x0 ((^:ptag/^:phasGenre/:pproducer)|(^:ptag/^:plike/:pgivenName)|(^:ptag/^:plike/:pemail)) ?x2 . ?x0 ((^:ptag/:pkeywords/^:pcaption/:ptitle)) ?x3 . } }
