PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 (((:previewer/^:pfriendOf/^:previewer)|(:previewer/^:peditor/:peditor/^:previewer))){,3} ?x1 . ?x0 (((^:phasReview/:phasReview)|(:previewer/^:pauthor/:pauthor/^:previewer)|(:previewer/^:pfriendOf/^:previewer))){,3} ?x2 . ?x0 (((^:phasReview/:pconductor/^:previewer)|(:previewer/^:previewer)|(:previewer/^:pactor/:phasReview))){,3} ?x3 . } }
