PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:ppublished/^:ptext/:pkeywords/^:pcaption)|(:phasReview/:previewer/:pemail/^:ptext)) ?x1 . ?x0 ((:pwordCount/^:pcontentSize/^:plike/^:pauthor)|(:pwordCount/^:pcontentSize)|(:pkeywords/^:pproducer/:pdescription/^:pcaption)) ?x2 . ?x0 ((:pcaption/^:ptext)|(:pwordCount/^:ptotalVotes/^:phasReview)|(:pdescription/^:paward/:paward/^:pcaption)) ?x3 . ?x0 ((:pwordCount/^:pcontentSize)|(:pprintSection/^:pcontentSize/:pcontentSize/^:pprintColumn)|(:pprintColumn/^:popeningHours/:ppaymentAccepted/^:pkeywords)) ?x4 . } }
