PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:partist/^:previewer/^:phasReview)) ?x1 . ?x0 ((^:pincludes/:pincludes/:phomepage/^:phomepage)|(^:ppurchaseFor/:ppurchaseFor/^:pincludes/:pincludes)) ?x2 . ?x1 ((^:pincludes/:pincludes/^:ppurchaseFor/:ppurchaseFor)|(^:ppurchaseFor/:ppurchaseFor)) ?x3 . } }
