PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:ptype/:plike)|(^:ptype/^:pauthor/:pcontentSize/^:pcontentRating)|(^:ptype/^:pfollows/^:pactor)) ?x1 . ?x1 ((:pdirector/^:pfriendOf/^:peditor)|(:ptrailer/^:phomepage/^:peditor)|(:pactor/^:peditor/^:pincludes/:pincludes)) ?x2 . ?x2 ((:pauthor/:plocation)) ?x3 . } }
