PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 ?x3 WHERE {  {  ?x0 (((^:pincludes/:pincludes)|(^:ppurchaseFor/^:pmakesPurchase/^:previewer/^:phasReview))){,3} ?x1 . ?x1 ((:pcaption/^:pcaption/:pdescription/^:pkeywords)) ?x2 . ?x2 (((:pactor/^:pdirector)|(:phasReview/^:phasReview/:phomepage/^:ptrailer))){,3} ?x3 . } }
