PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pcontentRating/^:pprintColumn/:ptitle/^:pperformer)|(^:plike/:pfriendOf/:plike)) ?x1 . ?x1 (((:phomepage/^:phomepage)|(:pconductor/^:pfriendOf/^:pconductor)|(^:pincludes/:pincludes))){,3} ?x2 . ?x2 ((:phomepage/:purl)|(:pconductor/:pgivenName)|(:pmovement/^:pduration/:pdescription)) ?x3 . } }
