PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:ptag/^:ptag)|(:pdescription/^:ptitle)) ?x1 . ?x0 ((:phomepage/:purl/^:pproducer)) ?x2 . ?x0 ((:pcontentSize/^:pduration)|(:ppublished/^:ptext)|(^:plike/:plike/:ptext/^:ptext)) ?x3 . ?x0 ((:pkeywords/^:pjobTitle/^:pactor)|(:pprintColumn/^:pduration)|(^:pincludes/:pserialNumber/^:pduration)) ?x4 . } }
