PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:pdirector/^:pdirector))){,3} ?x1 . ?x0 (((:ptrailer/^:ptrailer)|(:pactor/:phomepage/^:psubscribes/^:pdirector))){,3} ?x2 . ?x0 (((:pdirector/:pfriendOf/^:pfriendOf/^:pactor)|(:phomepage/^:phomepage/:phomepage/^:phomepage)|(:pactor/^:pactor))){,3} ?x3 . } }
