PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pdescription/^:pdescription)|(:pcontentSize/^:pcontentSize/:phomepage/^:phomepage)|(:pkeywords/^:ptitle/:pdescription/^:ptext)) ?x1 . ?x0 ((:pcontentRating/^:pprintPage)|(:ptext/^:ptitle)|(:pkeywords/^:pjobTitle/^:pauthor)) ?x2 . ?x0 ((^:plike/:pfamilyName/^:ptext)|(:phasGenre/:ptag/^:ptag/^:phasGenre)) ?x3 . } }
