PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 (((^:pincludes/:pincludes)|(:pauthor/:phomepage/^:phomepage)|(^:ppurchaseFor/:ppurchaseFor/^:pincludes/:pincludes))){,3} ?x1 . ?x0 (((:phasReview/^:phasReview)|(:phasReview/^:phasReview))){,3} ?x2 . ?x1 (((:peditor/^:pauthor)|(:peditor/^:pactor/:ptrailer/^:phomepage)|(:phomepage/^:phomepage))){,3} ?x3 . } }
