PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((:partist/^:previewer/:previewer/^:pfollows)) ?x1 . ?x1 (((^:pconductor/:pconductor/:pfriendOf))){,3} ?x2 . ?x2 (((:pfriendOf/^:pdirector/:pdirector/:pfriendOf)|(^:pemployee/:pcontactPoint))){,3} ?x3 . } }
