PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:ppublished/^:pdescription/:pkeywords/^:ptext)|(:pkeywords/^:pdescription)|(:ppublished/^:pcaption/:pcaption/^:ptext)) ?x1 . ?x0 ((:pauthor/:puserId/^:pcontentSize)) ?x2 . ?x0 ((:pdescription/^:pkeywords)|(:pdescription/^:ptitle/^:phasReview)|(:pprintColumn/^:puserId/:pemail/^:ptext)) ?x3 . } }
