PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:ppurchaseFor/:ptext/^:pcaption)) ?x1 . ?x0 ((:ppurchaseFor/^:ppurchaseFor)|(:ppurchaseFor/^:ppurchaseFor/^:pmakesPurchase/:pmakesPurchase)) ?x2 . ?x1 ((:ppurchaseFor/:pauthor/^:pdirector/^:ppurchaseFor)|(:ppurchaseFor/^:ppurchaseFor)|(^:pmakesPurchase/:pmakesPurchase)) ?x3 . } }
