PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pgender/:page)) ?x1 . ?x1 ((^:page/:plike/:pkeywords/^:pcomposer)|(^:page/^:previewer/^:phasReview)) ?x2 . ?x2 (((:phasReview/^:phasReview))){,3} ?x3 . } }
