PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x2 ?x1 WHERE {  {  ?x0 (((^:pincludes/:pincludes/:phasReview/^:phasReview))){,3} ?x1 . ?x1 ((^:plike/^:peditor)) ?x2 . ?x2 (((:pauthor/:psubscribes/^:phomepage)|(:phasReview/^:phasReview/:phomepage/^:phomepage)|(^:ppurchaseFor/^:pmakesPurchase/^:peditor))){,3} ?x3 . ?x3 (((:phasReview/:previewer/^:pauthor))){,3} ?x4 . } }
