PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pcontentSize/^:plike/:ptelephone/^:pcontentRating)|(^:pduration/:ptext/^:pkeywords)|(^:prating/:ptext/^:ptext)) ?x1 . ?x0 ((^:ptelephone/:plike)|(^:pduration/:pcaption/^:pdescription)|(^:pprintEdition/:pcaption/^:pcaption)) ?x2 . ?x0 ((^:pfaxNumber/:pemployee/:pemail/^:pdescription)|(^:phits/^:ptrailer)|(^:paggregateRating/:ptelephone/^:pcontentRating)) ?x3 . ?x0 ((^:puserId/:pfriendOf/:puserId/^:pcontentSize)|(^:pbookEdition/:pcontentRating/^:pcontentSize)) ?x4 . } }
