PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:planguage/:pkeywords/^:pemail/:plocation)|(^:planguage/^:plike/:plocation)|(^:planguage/:pactor/:pnationality/^:pparentContry)) ?x1 . ?x0 ((^:planguage/^:plike/:plocation)) ?x2 . ?x0 ((^:planguage/:pisbn/^:puserId/:plocation)|(^:planguage/^:plike/:plocation)) ?x3 . ?x0 ((^:planguage/:peditor/:plocation)|(^:planguage/^:phomepage/:plocation)|(^:planguage/:pcontentSize/^:ptelephone/:plocation)) ?x4 . } }
