PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:pkeywords/^:pkeywords/:pisbn/^:pprintEdition)|(:pproducer/^:ptitle)|(:pcontentSize/^:pprintPage)) ?x1 . ?x0 ((:phomepage/:phits/^:puserId)|(:pcontentSize/^:prating/:previewer)|(:pkeywords/^:pdescription/:pperformer/^:pjobTitle)) ?x2 . ?x1 ((:ptitle/^:ptitle/^:ppurchaseFor/^:pmakesPurchase)|(:ptag/^:ptag/:pactor)) ?x3 . } }
