PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:phomepage/^:phomepage)|(^:pincludes/:pincludes))){,3} ?x1 . ?x1 ((:partist/:phomepage/^:phomepage)|(:partist/:pmakesPurchase/:ppurchaseFor)|(:partist/^:previewer/^:phasReview)) ?x2 . ?x2 (((^:pincludes/:pincludes)|(^:ppurchaseFor/:ppurchaseFor))){,3} ?x3 . ?x3 ((:phomepage/^:psubscribes)|(^:ppurchaseFor/:ppurchaseFor/^:ppurchaseFor/^:pmakesPurchase)|(^:ppurchaseFor/^:pmakesPurchase)) ?x4 . } }
