PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:paggregateRating/^:pcontentRating/:pexpires)|(:pemployee/:pbirthDate)|(:pcontactPoint/^:pauthor/:pdatePublished)) ?x1 . ?x1 ((^:pbirthDate/^:pemployee/:ptelephone)|(^:pbirthDate/^:pfriendOf/:puserId)) ?x2 . ?x2 ((^:pnumberOfPages/:pcaption/^:pdescription/:ptag)|(^:pcontentRating/:ptag)|(^:pcontentSize/:ptag)) ?x3 . ?x3 ((^:ptag/^:phasGenre/^:plike/:pgender)|(^:ptag/:pdescription/^:pjobTitle/:pgender)|(^:ptag/^:plike/:pgender)) ?x4 . } }
