PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((:pdescription/^:pdescription/:phasGenre/:ptype)|(:phasGenre/:ptype)) ?x1 . ?x1 ((^:ptype/^:phasGenre/:pperformedIn)) ?x2 . ?x0 ((^:ppurchaseFor/:ppurchaseFor/^:pincludes/:pincludes)|(:phasReview/^:phasReview/:ptrailer/^:phomepage)) ?x3 . ?x2 ((:phasReview/^:phasReview/:ptrailer/^:phomepage)) ?x4 . } }
