PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 ?x3 WHERE {  {  ?x0 ((^:ptag/:pcontentSize/^:pmovement/:pperformedIn)|(^:ptag/:pcaption/^:pdescription/:pperformedIn)) ?x1 . ?x0 ((^:ptag/:ptext/^:pkeywords/:pcaption)|(^:ptag/:pdescription/^:pdescription/:pdescription)|(^:ptag/:pdescription)) ?x2 . ?x1 ((^:ptag/:phasReview/:ptitle)) ?x3 . } }
