PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((^:ppurchaseFor/:ppurchaseFor/:phomepage/^:phomepage)|(^:ppurchaseFor/:ppurchaseFor)|(:phasReview/:previewer/:psubscribes/^:phomepage))){,3} ?x1 . ?x0 (((:phasReview/^:phasReview/^:pincludes/:pincludes)|(:phasReview/^:phasReview/^:pincludes/:pincludes))){,3} ?x2 . ?x0 (((:phasReview/^:phasReview/^:pincludes/:pincludes)|(:phasReview/:previewer/^:previewer/^:phasReview)|(:phomepage/^:phomepage/^:pincludes/:pincludes))){,3} ?x3 . ?x0 (((:phomepage/^:phomepage))){,3} ?x4 . } }
