PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:planguage/^:psubscribes/:pgivenName)) ?x1 . ?x1 ((^:pdescription/:peditor/:pbirthDate)|(^:ptitle/^:pincludes/:pvalidForm)|(^:pproducer/:prelease)) ?x2 . ?x0 ((^:planguage/:ptext/^:ptext/:pprintPage)|(^:planguage/^:phomepage/:pcontentRating)) ?x3 . ?x2 ((^:planguage/^:ppurchaseFor/:ppurchaseFor/:pnumberOfPages)|(^:planguage/:pexpires/^:pdatePublished/:pprintPage)|(^:planguage/:pisbn)) ?x4 . } }
