PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:plike/^:pauthor/:phasReview)|(^:plike/:pmakesPurchase/:ppurchaseFor/:phasReview)|(^:pincludes/:pincludes/^:plike/^:previewer)) ?x1 . ?x0 ((^:plike/^:pcontactPoint/:pemployee/^:previewer)|(^:plike/^:pauthor/:phasReview)|(^:plike/^:previewer)) ?x2 . ?x0 ((^:plike/^:pconductor/:phasReview)|(^:plike/^:previewer)) ?x3 . } }
