PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:ptag/^:plike/:ptype)|(^:ptag/:pconductor/:ptype)) ?x1 . ?x0 ((^:ptag/^:plike/:ptype)|(^:ptag/^:plike/:ptype)|(^:ptag/:pdescription/^:pgivenName/:ptype)) ?x2 . ?x0 ((^:ptag/:pdirector/:ptype)|(^:ptag/:pcontentRating/^:puserId/:ptype)) ?x3 . ?x0 ((^:ptag/:pauthor/:ptype)|(^:ptag/^:plike/:ptype)|(^:ptag/:peditor/:ptype)) ?x4 . } }
