PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pcontentRating/:ptag/^:ptag)) ?x1 . ?x0 ((^:popus/:ptext/^:pdescription/:phasGenre)|(^:pprintPage/:ptag/^:ptag)) ?x2 . ?x0 ((^:pcontentRating/:phasGenre)|(^:phits/^:phomepage/:phasGenre)) ?x3 . ?x0 ((^:pserialNumber/:pincludes/:phasGenre)|(^:pcontentRating/:phasGenre)|(^:ptelephone/:plike/:phasGenre)) ?x4 . } }
