PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:phomepage/:pdescription/^:pname)|(^:phomepage/:pkeywords/^:pjobTitle/^:pemployee)|(:phits/^:popeningHours)) ?x1 . ?x0 ((:phits/^:pfaxNumber)|(:purl/^:ppaymentAccepted)|(:purl/^:pemail)) ?x2 . ?x0 ((^:psubscribes/^:pauthor/:pwordCount/^:pfaxNumber)) ?x3 . } }
