PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((^:ppurchaseFor/^:pmakesPurchase/^:pdirector))){,3} ?x1 . ?x1 ((:pdirector/^:pfriendOf/:plike)|(:ptrailer/^:phomepage/:plike)|(:pdirector/:pfriendOf/:plike)) ?x2 . ?x2 ((:phasGenre/:ptype)|(:phasGenre/:ptype)) ?x3 . } }
