PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:phomepage/:phits/^:pcontentSize)|(:pcaption/^:pkeywords)) ?x1 . ?x0 ((:pconductor/:pgivenName/^:ptext)) ?x2 . ?x0 ((:ptext/^:pdescription)) ?x3 . ?x0 ((:ptitle/^:ptitle)|(:pcaption/^:pcaption)|(:pkeywords/^:ptext)) ?x4 . } }
