PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 (((:phomepage/^:psubscribes/:psubscribes/^:phomepage)|(:phasReview/^:phasReview)|(:phasReview/^:phasReview/:phomepage/^:phomepage))){,3} ?x1 . ?x1 (((:phasReview/^:phasReview/:phomepage/^:phomepage)|(:phomepage/^:phomepage))){,3} ?x2 . ?x0 (((^:ppurchaseFor/:ppurchaseFor)|(:phomepage/^:phomepage/:phomepage/^:phomepage)|(:phasReview/^:phasReview/:phomepage/^:phomepage))){,3} ?x3 . ?x2 (((:phomepage/^:psubscribes/:phomepage/^:phomepage)|(^:pincludes/:pincludes/:phomepage/^:phomepage)|(:phasReview/^:phasReview))){,3} ?x4 . } }
