PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x3 ?x0 WHERE {  {  ?x0 (((:pdirector/^:pactor)|(:pactor/^:pdirector)|(^:pincludes/:pincludes/^:ppurchaseFor/:ppurchaseFor))){,3} ?x1 . ?x1 ((:pcaption/^:pkeywords/:phasReview)|(:pcontentSize/^:prating)) ?x2 . ?x0 (((^:pincludes/:pincludes/:phasReview/^:phasReview)|(:ptrailer/^:phomepage/^:pdirector)|(:phomepage/^:psubscribes/^:pactor))){,3} ?x3 . ?x3 ((:pdescription/^:pdescription)|(:phasReview/:ptitle/^:ptext)) ?x2 . } }
