PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((:peditor/^:peditor/:phasReview/^:phasReview)|(:pauthor/^:peditor))){,3} ?x1 . ?x1 ((^:ppurchaseFor/:ppurchaseFor/:phomepage/^:phomepage)|(:phasReview/^:phasReview)|(:pauthor/:psubscribes/^:phomepage)) ?x2 . ?x2 (((:phasReview/^:phasReview/^:ppurchaseFor/:ppurchaseFor)|(:phomepage/^:phomepage/:phasReview/^:phasReview)|(:phasReview/^:phasReview))){,3} ?x3 . } }
