PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:page/^:pfollows/^:pactor/:pkeywords)|(^:page/:plike/:ptext)) ?x1 . ?x0 ((^:page/:pfamilyName/^:pjobTitle/:pfamilyName)) ?x2 . ?x0 ((^:page/:pfamilyName)|(^:page/:pjobTitle)) ?x3 . ?x0 ((^:page/^:pactor/:pproducer)|(^:page/:pgivenName)) ?x4 . } }
