PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:ptype/:ptag/^:ptag)) ?x1 . ?x0 ((^:ptype/^:phasGenre)|(^:ptype/^:phasGenre)|(^:ptype/^:phasGenre/^:ppurchaseFor/:ppurchaseFor)) ?x2 . ?x1 ((^:ptype/:ptag/^:ptag)|(^:ptype/^:phasGenre/^:plike/:plike)|(^:ptype/^:phasGenre/:pprintPage/^:pprintColumn)) ?x3 . } }
