PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 (((:phasReview/^:phasReview)|(:phasReview/^:phasReview/^:ppurchaseFor/:ppurchaseFor)|(:phomepage/^:ptrailer))){,3} ?x1 . ?x1 (((:pdirector/^:pactor/:pactor/^:pdirector))){,3} ?x2 . ?x2 (((:pactor/:phomepage/^:ptrailer)|(:ptrailer/^:ptrailer/:pdirector/^:pdirector)|(:phomepage/^:phomepage/^:pdirector))){,3} ?x3 . } }
