PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 ?x3 WHERE {  {  ?x0 (((:pconductor/^:pconductor)|(:pconductor/^:pactor/:phomepage/^:phomepage)|(:phomepage/^:phomepage))){,3} ?x1 . ?x1 ((^:plike/:psubscribes/^:phomepage/:pauthor)) ?x2 . ?x2 ((^:previewer/:previewer/:plike)|(^:pactor/:pactor/:plike)) ?x3 . } }
