PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pauthor/:plike/^:plike/^:pauthor)) ?x1 . ?x1 ((^:plike/^:pauthor/^:pincludes)) ?x2 . ?x2 (((:pincludes/:ptrailer/^:phomepage/^:pincludes)|(:pincludes/^:pincludes))){,3} ?x3 . } }
