PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((:ppurchaseFor/:phasReview/:prating/^:phits)|(:ppurchaseFor/:pkeywords/^:pdescription/:phomepage)) ?x1 . ?x1 ((^:phomepage/:plike/^:plike/^:pauthor)) ?x2 . ?x0 ((:ppurchaseFor/:pcontentSize/^:pprice/:pincludes)|(:pprice/^:pcontentSize/:pdescription/^:pkeywords)|(:ppurchaseFor/:paward/^:pdescription)) ?x3 . ?x2 ((:ppurchaseFor/^:plike/:pfamilyName/^:ptitle)|(:ppurchaseFor/:popus/^:pprintEdition)) ?x4 . } }
