PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:ptitle/:ptitle/^:pkeywords)) ?x1 . ?x1 ((:ptext/^:pfamilyName/:pnationality)|(^:plike/:pnationality)|(:pdescription/^:pemail/:pnationality)) ?x2 . ?x0 ((^:paward/:pdirector/:plocation)|(^:pkeywords/:pactor/:plocation)|(^:ptitle/:pperformedIn)) ?x3 . ?x3 ((^:plocation/^:pauthor/:phasGenre/:ptype)|(^:pperformedIn/:phasGenre/:ptype)) ?x2 . } }
