PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pgender/^:pfollows/^:pconductor/:pperformedIn)|(^:pgender/:plike/^:plike/:plocation)) ?x1 . ?x1 ((:pparentContry/^:pparentContry)|(:pparentContry/^:pnationality/:plocation)) ?x2 . ?x0 ((^:pgender/:plike/:phasGenre)|(^:pgender/:ptelephone/^:pcontentSize/:phasGenre)) ?x3 . ?x2 ((^:pgender/^:pauthor/:phasGenre)|(^:pgender/:pfamilyName/^:pdescription/:phasGenre)|(^:pgender/:plike/:phasGenre)) ?x4 . } }
