PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x3 ?x0 WHERE {  {  ?x0 ((^:phomepage/:pcontentRating/^:pwordCount)|(^:psubscribes/:pfollows/:pfamilyName/^:ppublished)|(:purl/^:pcaption/^:plike/^:pauthor)) ?x1 . ?x0 ((:purl/^:pdescription/:pdirector/^:peditor)|(:phits/^:pprintEdition)) ?x2 . ?x0 ((:purl/^:ptitle)|(^:phomepage/:ptext/^:ptitle)) ?x3 . ?x0 ((^:phomepage/:pcaption/^:ptext/^:phasReview)) ?x4 . } }
