PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 (((^:pauthor/^:pincludes/:pincludes/:pdirector)|(^:previewer/:previewer/^:pdirector/:pdirector))){,3} ?x1 . ?x1 ((:pfollows/^:pfollows/^:pactor)|(:plike/^:plike/^:pactor)) ?x2 . ?x0 (((:pmakesPurchase/:ppurchaseFor/:peditor)|(^:pconductor/:pconductor)|(^:pfriendOf/^:pfriendOf/:psubscribes/^:phomepage))){,3} ?x3 . ?x2 (((^:peditor/:pauthor/^:pemployee/:pemployee)|(^:pauthor/:pauthor/^:peditor/:peditor))){,3} ?x4 . } }
