PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:phomepage/:plike/:phasReview)|(^:phomepage/:plike/:phasReview)|(^:psubscribes/:plike/:phasReview)) ?x1 . ?x0 ((^:psubscribes/:pfriendOf/:plike/:phasReview)) ?x2 . ?x0 ((^:phomepage/:pauthor/:plike/:phasReview)|(^:phomepage/:pauthor/:plike/:phasReview)|(^:phomepage/:plike/:phasReview)) ?x3 . ?x0 ((^:phomepage/:plike/:phasReview)) ?x4 . } }
