PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:previewer/:plike/^:plike/^:pemployee)|(:previewer/:pfollows/^:pfollows/^:pcontactPoint)|(:previewer/:plike/^:plike/^:pemployee)) ?x1 . ?x0 ((:previewer/:plike/^:plike/^:pemployee)|(:previewer/:plike/^:pincludes/^:poffers)) ?x2 . ?x0 ((:previewer/:pfollows/^:pfollows/^:pemployee)|(:previewer/:plike/^:plike/^:pcontactPoint)|(:previewer/:plike/^:plike/^:pemployee)) ?x3 . ?x0 ((:previewer/:plike/^:plike/^:pcontactPoint)|(:previewer/:plike/^:plike/^:pemployee)) ?x4 . } }
