PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 ?x3 WHERE {  {  ?x0 ((^:pgender/^:pfriendOf/:page)|(^:pgender/:plike/:pauthor/:page)) ?x1 . ?x1 ((^:page/:pnationality)) ?x2 . ?x0 ((^:pgender/:ptelephone)|(^:pgender/:puserId)|(^:pgender/:ptelephone/^:pduration/:pcontentSize)) ?x3 . ?x2 ((^:pgender/^:pfriendOf/:ptelephone)|(^:pgender/:plike/:pcontentRating)|(^:pgender/^:pauthor/^:pincludes/:peligibleQuantity)) ?x4 . } }
