PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:phasReview/^:phasReview/^:ppurchaseFor/:ppurchaseFor))){,3} ?x1 . ?x1 ((:pactor/^:previewer)|(:phomepage/^:psubscribes/^:previewer)) ?x2 . ?x2 (((:previewer/:pmakesPurchase/:ppurchaseFor/:phasReview)|(^:phasReview/:phomepage/^:phomepage/:phasReview))){,3} ?x3 . } }
