PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pnationality/:pjobTitle)|(^:pnationality/:pjobTitle)) ?x1 . ?x0 ((^:pnationality/:pjobTitle)) ?x2 . ?x0 ((^:pnationality/:pfamilyName/^:pperformer/:pperformer)|(^:pnationality/:puserId/^:pcontentSize/:pdescription)|(^:pparentContry/^:pperformedIn/:pdescription)) ?x3 . } }
