PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 ?x3 WHERE {  {  ?x0 (((:phomepage/^:ptrailer/:phasReview/^:phasReview)|(^:pincludes/:pincludes/^:pincludes/:pincludes)|(:phomepage/^:phomepage/:phomepage/^:phomepage))){,3} ?x1 . ?x0 (((^:pincludes/:pincludes/^:pincludes/:pincludes)|(^:ppurchaseFor/:ppurchaseFor)|(:phomepage/^:phomepage))){,3} ?x2 . ?x0 (((:phomepage/^:phomepage/:psubscribes/^:phomepage)|(:phomepage/^:phomepage/:phomepage/^:phomepage)|(:phomepage/^:ptrailer/:ptrailer/^:phomepage))){,3} ?x3 . ?x0 (((^:ppurchaseFor/:ppurchaseFor/^:ppurchaseFor/:ppurchaseFor))){,3} ?x4 . } }
