PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:pcontentSize/^:pmovement/:pperformer/^:pjobTitle)|(:pdescription/^:pgivenName/:pfollows)|(^:plike/:pfollows)) ?x1 . ?x0 ((:pkeywords/^:purl)|(:ptitle/^:purl)) ?x2 . ?x1 ((:pdescription/^:pdescription/:pcaption/^:purl)) ?x3 . } }
