PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pperformedIn/:phasGenre/:ptype)|(^:plocation/:plike/:phasGenre/:ptype)|(^:plocation/^:pauthor/:phasGenre/:ptype)) ?x1 . ?x0 ((^:pperformedIn/:pcaption/^:pkeywords/:planguage)|(^:plocation/:plike/:planguage)|(^:pperformedIn/:pcomposer/^:pdescription/:planguage)) ?x2 . ?x1 ((^:pperformedIn/:phomepage/:planguage)|(^:pperformedIn/:pcomposer/^:pproducer/:planguage)) ?x3 . } }
