PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:phomepage/:pbookEdition/^:pcontentSize)|(:purl/^:pcaption/:pdescription/^:pcaption)) ?x1 . ?x0 ((:purl/^:pemail)|(^:phomepage/:pprintEdition/^:pfaxNumber)) ?x2 . ?x1 ((:purl/^:pname/:ppaymentAccepted/^:ppaymentAccepted)) ?x3 . } }
