PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:planguage/:pexpires)|(^:planguage/:pexpires)|(^:planguage/^:phomepage/:pexpires)) ?x1 . ?x1 ((^:pexpires/:phasReview/^:phasReview)) ?x2 . ?x2 (((:phasReview/^:phasReview/:pauthor/^:pconductor))){,3} ?x3 . ?x3 (((:pconductor/^:peditor/:pauthor/^:pconductor)|(:phasReview/^:phasReview))){,3} ?x4 . } }
