PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:phasGenre/:planguage)|(^:phasGenre/:planguage)|(^:phasGenre/:phomepage/:planguage)) ?x1 . ?x0 ((^:phasGenre/:planguage)|(^:phasGenre/^:pincludes/:pincludes/:planguage)) ?x2 . ?x0 ((^:phasGenre/:pdescription/^:ptitle/:planguage)) ?x3 . } }
