PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x3 ?x1 WHERE {  {  ?x0 ((^:ptag/:pperformedIn/:pparentContry)|(^:ptag/^:plike/:pnationality)|(^:ptag/:paward/^:pjobTitle/:pnationality)) ?x1 . ?x1 ((^:pnationality/^:peditor/:phasGenre/:ptype)|(^:pnationality/^:pauthor/:phasGenre/:ptype)|(^:pnationality/^:peditor/:phasGenre/:ptype)) ?x2 . ?x0 ((^:ptag/:pkeywords/^:pgivenName/:pnationality)|(^:ptag/:pdescription/^:pgivenName/:pnationality)) ?x3 . ?x2 ((^:ptag/^:plike/:pnationality)|(^:ptag/^:pincludes/:peditor)|(^:ptag/:pauthor/:plocation/:pparentContry)) ?x4 . } }
