PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:psubscribes/:plike/^:plike/^:pauthor)|(^:phomepage/:plike/^:plike/^:peditor)|(^:psubscribes/:plike/^:plike/^:peditor)) ?x1 . ?x1 ((^:plike/^:pconductor)|(^:plike/^:pdirector/:pactor/^:pconductor)|(^:plike/^:pfollows/^:pconductor)) ?x2 . ?x2 (((^:ppurchaseFor/^:pmakesPurchase/^:pconductor))){,3} ?x3 . } }
