PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:page/^:pdirector/^:plike/:pfriendOf)|(^:page/^:pauthor/:peditor)) ?x1 . ?x0 ((^:page/^:pfriendOf/:plike)) ?x2 . ?x1 ((^:page/:puserId/^:pprintSection)|(^:page/:plike/:pcontentSize/^:pcontentSize)) ?x3 . } }
