PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pduration/^:pduration/:paward/^:pcaption)|(:pdirector/:pjobTitle/^:pcaption)|(:pdescription/^:pkeywords)) ?x1 . ?x0 ((:pduration/^:paggregateRating)|(:ptext/^:plegalName)|(:pcontentSize/^:pfaxNumber)) ?x2 . ?x1 ((:ptrailer/:purl/^:plegalName)|(:paward/^:paward/:pcaption/^:pemail)) ?x3 . } }
