PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pcontentRating/^:puserId/^:partist)|(:pisbn/^:peligibleQuantity/:pincludes)) ?x1 . ?x1 ((:partist/:plike)|(:partist/:pfriendOf/^:pauthor)|(:partist/^:pauthor)) ?x2 . ?x2 ((:peditor/^:partist/^:ppurchaseFor)|(^:plike/:pfriendOf/:pmakesPurchase)) ?x3 . } }
