PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:pmakesPurchase/:pfollows/^:pfollows/^:pconductor)|(:ppurchaseFor/:partist/^:pfollows/^:pconductor)|(^:pmakesPurchase/:plike/^:plike/^:pconductor)) ?x1 . ?x1 ((^:ppurchaseFor/:ppurchaseFor)|(^:ppurchaseFor/:ppurchaseFor)|(:pconductor/^:previewer/^:phasReview)) ?x2 . ?x2 (((^:pincludes/:pincludes/:phomepage/^:phomepage))){,3} ?x3 . } }
