PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:page/:pfollows/:puserId/^:pisbn)) ?x1 . ?x1 (((:pauthor/^:pfriendOf/^:pauthor))){,3} ?x2 . ?x0 ((^:page/:pgivenName/^:pkeywords)|(^:page/:pmakesPurchase/:ppurchaseFor)|(^:page/:pjobTitle/^:pcaption)) ?x3 . ?x3 ((^:plike/:pfriendOf/:pmakesPurchase/:pprice)|(^:plike/:puserId/^:phits/:phits)|(:ptext/^:paward/:pcontentSize)) ?x2 . } }
