PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:phasGenre/:ptitle/^:pdescription/:pexpires)|(^:phasGenre/^:pincludes/:ppriceValidUntil)) ?x1 . ?x1 ((^:ppurchaseDate/:pprice/^:pprintColumn/:pprintPage)|(^:pbirthDate/^:pdirector/:pduration)) ?x2 . ?x2 ((^:pcontentRating/:pcaption/^:ptitle/:phasGenre)) ?x3 . ?x3 ((^:phasGenre/^:plike/:pgender)) ?x4 . } }
