PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pconductor/:pkeywords/^:ptitle)|(:pfamilyName/^:pkeywords/:pkeywords/^:paward)|(:pfriendOf/:psubscribes/:purl/^:pdescription)) ?x1 . ?x0 ((:pjobTitle/^:ptitle)|(^:pactor/:phasGenre/:ptag/^:ptag)|(^:pconductor/:ptext/^:ptext)) ?x2 . ?x0 ((:pemail/^:pcaption/:pisbn/^:pduration)|(:pfollows/^:pfollows/:pemail/^:pproducer)) ?x3 . ?x0 ((:pjobTitle/^:pdescription/:pcontentSize/^:pcontentSize)|(:pfriendOf/:pjobTitle/^:pkeywords)|(:pfamilyName/^:ptext)) ?x4 . } }
