PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((:pactor/:plike/^:plike/:psubscribes)|(:pdirector/:plike/^:plike/:phomepage)) ?x1 . ?x1 (((^:phomepage/:pactor/:psubscribes)|(^:phomepage/:phomepage))){,3} ?x2 . ?x2 ((^:phomepage/^:plike/^:pactor)|(^:phomepage/^:plike/:pmakesPurchase/:ppurchaseFor)|(^:phomepage/^:plike/^:pactor)) ?x3 . ?x3 ((:phasReview/:previewer/:plike)) ?x4 . } }
