PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pemployee/:pfriendOf/:plike)) ?x1 . ?x0 ((:pemployee/:plike)|(:pemployee/:plike)) ?x2 . ?x0 ((:poffers/:pincludes/^:pincludes/:pincludes)|(:pemployee/:pfollows/:plike)) ?x3 . ?x0 ((:pemployee/:plike)|(:pemployee/:plike)) ?x4 . } }
