PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x3 ?x0 WHERE {  {  ?x0 (((^:pmakesPurchase/^:pauthor/^:ppurchaseFor)|(:ppurchaseFor/:pauthor/^:pfriendOf/:pmakesPurchase)|(:ppurchaseFor/^:ppurchaseFor))){,3} ?x1 . ?x0 (((:ppurchaseFor/^:pincludes/:pincludes/^:ppurchaseFor))){,3} ?x2 . ?x0 (((^:pmakesPurchase/:phomepage/^:ptrailer/^:ppurchaseFor)|(^:pmakesPurchase/^:pconductor/^:ppurchaseFor)|(:ppurchaseFor/:phasReview/^:phasReview/^:ppurchaseFor))){,3} ?x3 . } }
