PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((^:pkeywords/:ptext/^:pgivenName/:plike)) ?x1 . ?x1 (((:phasReview/^:phasReview)|(^:pincludes/:pincludes/:phomepage/^:phomepage)|(:phomepage/^:psubscribes/^:peditor))){,3} ?x2 . ?x2 ((:ptitle/^:pcaption/:pexpires/^:pexpires)|(:pprintEdition/^:pprice/:ppurchaseFor)|(:ptext/^:ptext/:ptext/^:pkeywords)) ?x3 . ?x3 ((:phomepage/^:phomepage)|(:phomepage/^:phomepage)) ?x4 . } }
