PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pparentContry/^:plocation)|(^:pnationality/^:pfriendOf)|(^:pnationality/^:peditor/:pdescription/^:pfamilyName)) ?x1 . ?x0 ((^:pnationality/:pgivenName/^:pkeywords/:pactor)) ?x2 . ?x0 ((^:pnationality/:pemail/^:pemail)|(^:pnationality/^:pcontactPoint/:pcontactPoint)) ?x3 . } }
