PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 ?x3 WHERE {  {  ?x0 (((^:pfriendOf/:pfriendOf)|(:pfriendOf/^:pfriendOf)|(:psubscribes/^:psubscribes))){,3} ?x1 . ?x1 ((:puserId/^:pprice)|(:plike/:pcontentSize/^:pprice)) ?x2 . ?x0 ((:pfollows/:pjobTitle/^:pperformer)|(:pjobTitle/^:paward/:phasReview/^:phasReview)) ?x3 . ?x3 ((:pconductor/:plike/^:plike/^:pconductor)|(:pconductor/:plike/^:plike/^:pconductor)|(:pconductor/:plike/^:plike/^:pconductor)) ?x2 . } }
