PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pperformedIn/:pperformer/^:ptext/:pcontentSize)|(^:plocation/:pmakesPurchase/:ppurchaseFor/:pcontentRating)|(^:plocation/:puserId)) ?x1 . ?x0 ((^:pperformedIn/^:plike/^:pauthor/:pprintEdition)) ?x2 . ?x0 ((^:plocation/:pfollows/:plike/:pcontentSize)|(^:plocation/^:partist/^:pincludes/:pprice)|(^:plocation/:pfriendOf/:ptelephone)) ?x3 . } }
