PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pgender/^:peditor/:pkeywords/^:pcaption)|(^:pgender/:plike/:pproducer/^:pcaption)) ?x1 . ?x1 (((:phomepage/^:phomepage/^:pincludes/:pincludes)|(^:ppurchaseFor/^:pmakesPurchase/:pmakesPurchase/:ppurchaseFor)|(^:ppurchaseFor/^:pmakesPurchase/:psubscribes/^:phomepage))){,3} ?x2 . ?x2 ((^:ppurchaseFor/:ppurchaseFor/:phasReview)) ?x3 . ?x3 ((:previewer/:plike/^:plike/^:pconductor)|(^:phasReview/:partist/^:pfollows/^:pconductor)) ?x4 . } }
