PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x3 ?x1 WHERE {  {  ?x0 ((:ppurchaseFor/:ptitle/^:ppublished/^:pincludes)) ?x1 . ?x0 ((:ppurchaseFor/:ptitle/^:pdescription/:poffers)|(^:pmakesPurchase/^:pactor/:pcontentRating/^:pprice)) ?x2 . ?x0 ((:pprice/^:pcontentRating/:pprintColumn/^:pserialNumber)|(:pprice/^:pbookEdition/:pexpires/^:ppriceValidUntil)|(:pprice/^:pprice)) ?x3 . ?x0 ((:ppurchaseFor/:pcontentRating/^:pcontentRating/^:pincludes)|(:pprice/^:pisbn/:pnumberOfPages/^:pserialNumber)) ?x4 . } }
