PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:phasTag/^:pisSubclassOf/:planguage)|(^:phasInterest/^:phasCreator/^:preplyOf/:planguage)|(^:phasTag/^:preplyOf/:planguage)) ?x1 . ?x0 ((:pname/^:pcontent/:pimageFile/^:pname)|(:pname/^:pname/:pname/^:pname)|(:pname/^:pbrowserUsed/:pbrowserUsed/^:pname)) ?x2 . ?x2 ((:pisLocatedIn/^:pisLocatedIn/:pisLocatedIn)|(:pisLocatedIn/^:pisLocatedIn/:pemail/^:pname)) ?x1 . } }
