PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((:pname/^:pbrowserUsed/:pspeaks/^:pname)|(:pname/^:plocationIP/:pemail/^:pname)) ?x1 . ?x1 ((:pname/^:pgender/:pbirthday)|(:pname/^:pname/:pcreationDate)) ?x2 . ?x2 (((^:pbirthday/:pbrowserUsed/^:pbrowserUsed/:pcreationDate)|(^:pcreationDate/:pcreationDate)|(^:pcreationDate/:pcreationDate))){,3} ?x3 . }  UNION  {  } }
