PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:pbirthday/^:phasModerator)) ?x1 . ?x1 ((:plength/^:pcontent)|(:plength/^:plocationIP/:pbrowserUsed/^:pcontent)|(:plength/^:pcontent)) ?x2 . ?x0 ((^:pcreationDate/:pbrowserUsed/^:pname)|(^:pbirthday/:pname/^:pname)|(^:pcreationDate/:pbrowserUsed/^:pname)) ?x3 . ?x2 ((^:pcreationDate/:pgender/^:pname)) ?x4 . }  UNION  {  } }
