PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:pbrowserUsed/^:plocationIP)|(:pbrowserUsed/^:pcontent/:pcontent/^:pbrowserUsed)|(:plocationIP/^:plocationIP))){,3} ?x1 . ?x1 ((^:pisSubclassOf/:pcontent/^:pemail/:pbirthday)|(^:pisSubclassOf/^:pcontainerOf/:pcreationDate)|(^:plikes/:pcreationDate/^:pcreationDate/:pbirthday)) ?x2 . ?x2 ((^:pcreationDate/^:phasModerator/:plength/^:pname)|(^:pbirthday/:pemail/^:pname)) ?x3 . } }
