PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 (((^:plocationIP/:plocationIP/^:pcontent/:planguage)|(^:pbrowserUsed/:plocationIP/^:pname/:pname)|(^:pname/:pgender/^:pname/:pname))){,3} ?x1 . ?x0 (((^:pbrowserUsed/:pbrowserUsed/^:pgender/:pname))){,3} ?x2 . ?x0 (((^:pbrowserUsed/:pgender/^:pname/:pname)|(^:pname/:pname))){,3} ?x3 . ?x0 (((^:pimageFile/:pimageFile)|(^:pbrowserUsed/:pname/^:pimageFile/:planguage))){,3} ?x4 . }  UNION  {  }  UNION  {  } }
