PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pname/^:pemail/:pcreationDate)|(:pname/^:pbrowserUsed/:phasCreator/:pbirthday)|(:pisPartOf/:pname/^:pbrowserUsed/:pbirthday)) ?x1 . ?x0 (((:pname/^:pname)|(:pname/^:pname))){,3} ?x2 . ?x2 (((:pname/^:pbrowserUsed/:pgender/^:pname)|(:pname/^:plocationIP/:plocationIP/^:pname))){,3} ?x1 . }  UNION  {  } }
