PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 ((^:pworksAt/^:pknows/:pcreationDate)|(^:pworksAt/:plikes/:pcreationDate)|(^:pworksAt/:pbrowserUsed/^:pspeaks/:pbirthday)) ?x1 . ?x1 (((^:pbirthday/:pgender/^:pbrowserUsed/:pcreationDate))){,3} ?x2 . ?x2 (((^:pcreationDate/:plocationIP/^:pname/:pbirthday)|(^:pbirthday/:pbirthday))){,3} ?x3 . ?x3 ((^:pcreationDate/^:phasCreator/:pisLocatedIn/^:pisPartOf)|(^:pcreationDate/:pisLocatedIn/^:pisPartOf)|(^:pcreationDate/:pisLocatedIn/^:pisPartOf)) ?x4 . } }
