PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:pimageFile/:pimageFile/^:plocationIP/:pname)|(^:pgender/:pbrowserUsed/^:pbrowserUsed/:pname))){,3} ?x1 . ?x1 (((^:pbrowserUsed/:plocationIP/^:planguage/:pcontent)|(^:pcontent/:planguage/^:planguage/:pcontent)|(^:pbrowserUsed/:pname/^:pbrowserUsed/:pname))){,3} ?x2 . ?x0 (((^:pname/:pname))){,3} ?x3 . ?x2 (((^:pgender/:pname)|(^:pname/:plocationIP/^:plocationIP/:pbrowserUsed)|(^:plocationIP/:pgender))){,3} ?x4 . } }
