PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pisLocatedIn/:pname/^:pname)|(:pisLocatedIn/:pname/^:pname)|(:pisLocatedIn/:pname/^:pname)) ?x1 . ?x1 ((:pname/^:pname/:pname)|(:pname/^:pcontent/:planguage)) ?x2 . ?x2 ((^:pname/:pgender/^:pname)|(^:pname/:pbrowserUsed/^:pname)|(^:pgender/:pgender/^:pname)) ?x3 . ?x3 (((:pname/^:pname)|(:pname/^:pgender/:pbrowserUsed/^:pname)|(:pname/^:planguage/:pimageFile/^:pname))){,3} ?x4 . } }
