PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pbirthday/:pstudyAt/:pname/^:pcontent)|(^:pcreationDate/:pisLocatedIn/:pname/^:pimageFile)) ?x1 . ?x0 ((^:pcreationDate/:phasInterest/:pname/^:pname)|(^:pcreationDate/:pknows/:pbrowserUsed/^:pname)|(^:pcreationDate/:phasMember/:pname/^:pname)) ?x2 . ?x1 ((^:pbirthday/:pname/^:pname/:phasType)|(^:pbirthday/:pemail/^:pname/:pisSubclassOf)) ?x3 . } }
