PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x3 ?x1 WHERE {  {  ?x0 ((^:pcreationDate/:pknows/:pisLocatedIn)|(^:pcreationDate/^:plikes/:pisLocatedIn)|(^:pcreationDate/:phasMember/:pisLocatedIn)) ?x1 . ?x1 ((:pisPartOf/:pisPartOf)) ?x2 . ?x0 ((^:pcreationDate/:pstudyAt/:pname)|(^:pcreationDate/:pisLocatedIn/:pname)) ?x3 . ?x2 ((^:pbirthday/:pworksAt/:pname)|(^:pcreationDate/:phasCreator/:plocationIP)) ?x4 . } }
