PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:pgender/:pbrowserUsed/^:pimageFile/:planguage)|(^:pbrowserUsed/:pbrowserUsed)|(^:pcontent/:pimageFile))){,3} ?x1 . ?x0 (((^:pbrowserUsed/:pgender/^:pbrowserUsed/:plocationIP)|(^:pbrowserUsed/:plocationIP/^:pname/:pname))){,3} ?x2 . ?x1 (((^:pgender/:pcreationDate/^:pbirthday/:pgender)|(^:pname/:pname/^:pname/:pname)|(^:pname/:pname/^:pbrowserUsed/:pbrowserUsed))){,3} ?x3 . } }
