PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 (((:pname/^:pname)|(:pname/^:plength/:plength/^:pname))){,3} ?x1 . ?x1 (((:pname/^:pname/:pgender/^:pname)|(:pname/^:plocationIP/:pbrowserUsed/^:pname))){,3} ?x2 . ?x0 ((:pname/^:pcontent/:planguage)|(:pname/^:pcontent/:planguage)) ?x3 . ?x3 (((^:planguage/:planguage))){,3} ?x2 . } }
