PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x3 ?x0 ?x1 WHERE {  {  ?x0 (((^:pname/:pgender)|(^:pgender/:pbirthday/^:pcreationDate/:pbrowserUsed)|(^:planguage/:pcontent))){,3} ?x1 . ?x1 ((^:pemail/:plikes/^:preplyOf)|(^:pemail/^:phasCreator/^:pisSubclassOf)|(^:pcontent/:pisSubclassOf/^:preplyOf)) ?x2 . ?x0 (((^:pbrowserUsed/^:plikes/^:phasCreator/:pisLocatedIn)|(^:pemail/^:phasCreator/:pisLocatedIn)|(^:plocationIP/:phasCreator/^:phasCreator/:pisLocatedIn))){,3} ?x3 . ?x2 (((^:pspeaks/:pemail/^:pname)|(^:pemail/^:phasCreator/:pisLocatedIn))){,3} ?x4 . }  UNION  {  }  UNION  {  }  UNION  {  }  UNION  {  } }
