PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:phasMember/:pcontainerOf)|(^:phasMember/:pcontainerOf)|(^:pknows/:pemail/^:planguage)) ?x1 . ?x0 ((^:pknows/:pemail/^:pcontent)) ?x2 . ?x0 ((:plikes/^:pisSubclassOf)|(:pknows/:pknows/:pgender/^:pcontent)|(:pknows/:pspeaks/^:pcontent)) ?x3 . ?x0 ((:pname/^:pemail/:pspeaks/^:pcontent)|(^:phasMember/:pcontainerOf)) ?x4 . }  UNION  {  }  UNION  {  } }
