PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((:pname/^:pimageFile/:pimageFile/^:pname)|(:pname/^:planguage/:pcontent/^:pname)|(:pname/^:pbrowserUsed/:pname/^:pname))){,3} ?x1 . ?x1 ((:pname/^:pspeaks/:plocationIP/^:pname)) ?x2 . ?x2 (((:pname/^:pname/:pgender/^:pname))){,3} ?x3 . }  UNION  {  }  UNION  {  } }
