PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 (((:pname/^:pname)|(:pname/^:pname/:pname/^:pname))){,3} ?x1 . ?x1 ((^:phasType/:pname/^:pcontent/:planguage)|(^:phasType/:pname/^:pcontent/:planguage)|(^:phasType/:pname/^:pcontent/:planguage)) ?x2 . ?x2 (((^:planguage/:planguage/^:planguage/:planguage)|(^:planguage/:planguage)|(^:planguage/:planguage))){,3} ?x3 . ?x3 ((^:planguage/:pcontent/^:pname/^:pworksAt)|(^:planguage/:pcontent/^:pname/^:pstudyAt)|(^:planguage/:pcontent/^:pname/^:pworksAt)) ?x4 . } }
