PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((^:pbirthday/:plikes/^:preplyOf)) ?x1 . ?x0 ((^:pbirthday/^:pknows/:pspeaks/^:pname)|(^:pcreationDate/^:plikes/:pemail/^:pname)|(^:pcreationDate/^:plikes/:plikes/:pisLocatedIn)) ?x2 . ?x1 ((^:pcreationDate/^:pknows/:plikes/:pisLocatedIn)) ?x3 . } }
