PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x2 ?x1 WHERE {  {  ?x0 (((^:pbirthday/:pcreationDate)|(^:pcreationDate/:plength/^:pbrowserUsed/:pcreationDate)|(^:pcreationDate/:pcreationDate))){,3} ?x1 . ?x1 ((^:pbirthday/:pemail/^:pbrowserUsed/:pworksAt)|(^:pcreationDate/:pknows/:pworksAt)|(^:pcreationDate/:phasMember/:pworksAt)) ?x2 . ?x2 (((:pname/^:planguage/:pimageFile/^:pname)|(:pname/^:pcontent/:pcontent/^:pname))){,3} ?x3 . ?x3 ((:pname/^:plength)) ?x4 . }  UNION  {  } }
