PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:plocationIP/^:pbrowserUsed))){,3} ?x1 . ?x0 (((:pgender/^:pbrowserUsed)|(:pname/^:pcontent/:pcontent/^:pgender)|(:plocationIP/^:plocationIP))){,3} ?x2 . ?x0 (((:pgender/^:pgender)|(:pname/^:pcontent/:pcontent/^:pgender)|(:pgender/^:pcontent/:pcontent/^:plocationIP))){,3} ?x3 . ?x0 (((:pcreationDate/^:pbirthday/:plocationIP/^:pname)|(:pcreationDate/^:pcreationDate)|(:pgender/^:planguage/:pimageFile/^:plocationIP))){,3} ?x4 . } }
