PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:pisSubclassOf/:phasCreator/:pemail/^:pname)) ?x1 . ?x1 ((:pname/^:pemail/:phasInterest/:phasType)|(^:pworksAt/:phasInterest/:phasType)) ?x2 . ?x0 ((:pcontent/^:pcontent)|(:pcontent/^:pname/:pname/^:pcontent)|(:pcontent/^:pcontent/:pimageFile/^:pcontent)) ?x3 . ?x2 ((:pcontent/^:pimageFile/:pcontent/^:pcontent)|(:pcontent/^:pgender/:plocationIP/^:pcontent)|(:pcontent/^:pcontent)) ?x4 . }  UNION  {  }  UNION  {  } }
