PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pisLocatedIn/:phasInterest/:phasType)|(^:pisLocatedIn/:phasInterest/:phasType)) ?x1 . ?x0 ((^:pisLocatedIn/:phasInterest/:phasType)|(^:pisLocatedIn/:phasInterest/:phasType)|(^:pisLocatedIn/:phasInterest/:phasType)) ?x2 . ?x0 ((^:pisLocatedIn/^:pknows/:phasInterest/:phasType)|(^:pisLocatedIn/^:phasCreator/:phasTag/:phasType)) ?x3 . }  UNION  {  } }
