PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pname/^:pname/:plocationIP/^:planguage)|(:pname/^:pgender/:pname/^:planguage)|(:pname/^:planguage)) ?x1 . ?x0 ((:pname/^:pimageFile)|(:pname/^:pbrowserUsed/:pbrowserUsed/^:planguage)) ?x2 . ?x0 ((:pname/^:pimageFile)) ?x3 . }  UNION  {  }  UNION  {  } }
