PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:plocationIP/:pbrowserUsed/^:pname)|(^:planguage/:pcontent/^:pname)|(^:pname/:pgender/^:pname)) ?x1 . ?x1 ((:pname/^:pbrowserUsed/^:phasModerator)|(:pname/^:pname/^:pworksAt/^:phasModerator)|(:pname/^:pbrowserUsed/:pemail/^:plength)) ?x2 . ?x0 ((^:pname/^:pknows/:pstudyAt)|(^:pgender/^:pknows/:pstudyAt)) ?x3 . ?x2 ((^:pbrowserUsed/^:phasCreator/:phasCreator/:pstudyAt)|(^:plocationIP/^:plikes/:pstudyAt)) ?x4 . }  UNION  {  }  UNION  {  }  UNION  {  } }
