PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 (((:plocationIP/^:plocationIP)|(:pbrowserUsed/^:planguage/:pimageFile/^:plocationIP))){,3} ?x1 . ?x0 ((^:plikes/:pknows/:pspeaks/^:pimageFile)|(^:pisSubclassOf/:pisSubclassOf/^:pisSubclassOf)) ?x2 . ?x2 ((:pcontent/^:pname/^:pisPartOf)|(:pcontent/^:plocationIP/:pemail/^:pname)|(:pcontent/^:pname/^:pisPartOf)) ?x1 . }  UNION  {  } }
