PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pbirthday/:pemail/^:pbrowserUsed/:plikes)|(^:pcreationDate/^:plikes/:pgender/^:plocationIP)) ?x1 . ?x1 ((:plocationIP/^:pname/^:phasTag/:pcreationDate)|(^:plikes/:pbirthday)) ?x2 . ?x2 (((^:pcreationDate/:pcreationDate))){,3} ?x3 . ?x3 ((^:pcreationDate/:plikes/:pisLocatedIn)|(^:pbirthday/^:phasCreator/:pisLocatedIn)|(^:pbirthday/:plikes/:pisLocatedIn)) ?x4 . } }
