PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 (((^:planguage/:planguage)|(^:planguage/:planguage/^:planguage/:planguage)|(^:planguage/:planguage/^:planguage/:planguage))){,3} ?x1 . ?x1 ((^:planguage/:preplyOf/:pisLocatedIn/^:pisLocatedIn)) ?x2 . ?x0 (((^:planguage/:pcontent/^:pcontent/:planguage)|(^:planguage/:pcontent/^:pcontent/:planguage))){,3} ?x3 . ?x2 (((^:planguage/:planguage/^:planguage/:planguage))){,3} ?x4 . } }
