PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((:pname/^:pname/:pname/^:plength)|(:pname/^:pname/:pname/^:plength)) ?x1 . ?x1 ((:plength/^:pname/^:pisPartOf/:pname)) ?x2 . ?x0 ((:pname/^:pname)|(:pname/^:pname/:pgender/^:pname)) ?x3 . ?x3 (((:pname/^:pimageFile/:pcontent/^:pname)|(:pname/^:planguage/:pcontent/^:pname)|(:pname/^:plength/:plength/^:pname))){,3} ?x2 . } }
