PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:preplyOf/:pcontent/^:plocationIP/^:phasModerator)|(^:preplyOf/:pcontent/^:plocationIP/^:phasModerator)|(:pbrowserUsed/^:pbrowserUsed/:pspeaks/^:plength)) ?x1 . ?x1 ((:pcontainerOf/:pcontent/^:pcontent)|(:plength/^:plocationIP/^:pisSubclassOf)|(:plength/^:pbrowserUsed/:pspeaks/^:pcontent)) ?x2 . ?x2 (((:pcontent/^:pbrowserUsed/:pgender/^:pcontent)|(:pcontent/^:pcontent/:planguage/^:planguage)|(:pcontent/^:pgender/:plocationIP/^:pcontent))){,3} ?x3 . ?x3 (((:pcontent/^:pbrowserUsed/:pbrowserUsed/^:pcontent)|(:pcontent/^:pcontent)|(:pcontent/^:pcontent))){,3} ?x4 . }  UNION  {  }  UNION  {  }  UNION  {  } }
