PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:pcreationDate/^:pcreationDate)|(:plength/^:pbrowserUsed/:pname/^:plength)|(:plength/^:plength))){,3} ?x1 . ?x0 (((:plength/^:pname/:pname/^:plength)|(:plength/^:pname/:pbirthday/^:pcreationDate)|(:plength/^:pgender/:pname/^:plength))){,3} ?x2 . ?x0 (((:plength/^:pgender/:pbirthday/^:pcreationDate)|(:plength/^:pbrowserUsed/:pbrowserUsed/^:plength))){,3} ?x3 . }  UNION  {  }  UNION  {  }  UNION  {  } }
