PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 (((:pname/^:pname)|(:pname/^:plocationIP/:plocationIP/^:pname))){,3} ?x1 . ?x1 ((^:pisPartOf/:pisPartOf/:pisPartOf)) ?x2 . ?x0 (((:pname/^:plength/:plength/^:pname)|(:pname/^:plocationIP/:plocationIP/^:pname)|(:pname/^:pname))){,3} ?x3 . ?x2 (((:pname/^:plocationIP/:pbrowserUsed/^:pname)|(:pname/^:pname))){,3} ?x4 . }  UNION  {  } }
