PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((:plocationIP/^:pname/^:phasTag)) ?x1 . ?x1 (((:pcreationDate/^:pcreationDate))){,3} ?x2 . ?x0 ((:pbrowserUsed/^:pbrowserUsed)) ?x3 . ?x2 ((:plocationIP/^:pbrowserUsed)|(:pbrowserUsed/^:pname/:pname/^:pbrowserUsed)|(:plocationIP/^:pgender/:pbrowserUsed/^:plocationIP)) ?x4 . } }
