PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:planguage/:pcontent/^:pcontent/^:pcontainerOf)|(^:planguage/:preplyOf/:plocationIP/^:plength)) ?x1 . ?x0 ((^:planguage/:pisSubclassOf/:pbrowserUsed/^:plength)|(^:planguage/:preplyOf/:pcreationDate/^:pcreationDate)|(^:planguage/:pcontent/^:pcontent/^:pcontainerOf)) ?x2 . ?x0 ((^:planguage/:pisSubclassOf/:plocationIP/^:plength)) ?x3 . ?x0 ((^:planguage/:pisSubclassOf/:pcreationDate/^:pcreationDate)|(^:planguage/:preplyOf/:pbrowserUsed/^:plength)) ?x4 . } }
