PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 (((:pname/^:pname/:pbrowserUsed/^:pname))){,3} ?x1 . ?x1 ((:pname/^:plocationIP/:pworksAt)) ?x2 . ?x2 (((:pname/^:planguage/:pcontent/^:pname))){,3} ?x3 . ?x3 (((:pname/^:pname/:pname/^:pname)|(:pname/^:plocationIP/:pbrowserUsed/^:pname)|(:pname/^:plocationIP/:pbrowserUsed/^:pname))){,3} ?x4 . }  UNION  {  } }
