PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:phasType/^:pisSubclassOf)|(:phasType/^:pisSubclassOf)) ?x1 . ?x0 ((:pname/^:pname/^:phasType/:phasType)|(^:phasInterest/:phasInterest/:phasType)) ?x2 . ?x0 ((^:phasInterest/:plikes/:pbrowserUsed/^:pname)) ?x3 . ?x0 ((:phasType/^:pisSubclassOf)) ?x4 . }  UNION  {  } }
