PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:pname/^:pbrowserUsed/:pbirthday)) ?x1 . ?x1 (((^:pcreationDate/:plocationIP/^:pbrowserUsed/:pbirthday)|(^:pcreationDate/:pbrowserUsed/^:plocationIP/:pbirthday)|(^:pbirthday/:pcreationDate))){,3} ?x2 . ?x0 ((:pname/^:pname)|(:pname/^:pname/:pgender/^:pname)) ?x3 . ?x2 ((:pname/^:plocationIP/:pbrowserUsed/^:pname)|(:pname/^:pname)) ?x4 . }  UNION  {  } }
