PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pbrowserUsed/:plikes/^:preplyOf/:planguage)|(^:pemail/^:phasCreator/^:pisSubclassOf/:planguage)) ?x1 . ?x0 ((^:pname/:pname/^:planguage/:planguage)|(^:pcontent/:pimageFile/^:pbrowserUsed/:pgender)|(^:pcontent/:pimageFile/^:planguage/:planguage)) ?x2 . ?x1 ((^:pcontent/:pcontent)|(^:pcontent/:planguage/^:plength/:plength)) ?x3 . } }
