PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:pname/^:pgender/:plocationIP/^:pname))){,3} ?x1 . ?x0 (((:pname/^:pcontent/:pcontent/^:pname)|(:pname/^:plocationIP/:pbrowserUsed/^:pname))){,3} ?x2 . ?x2 ((:pisLocatedIn/:pname/^:pname/:pbirthday)) ?x1 . } }
