PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((:pname/^:pname/:pisPartOf)) ?x1 . ?x1 ((:pname/^:pname)) ?x2 . ?x2 (((:pname/^:planguage/:pcontent/^:pname)|(:pname/^:pbrowserUsed/:pbrowserUsed/^:pname)|(:pname/^:plocationIP/:pbrowserUsed/^:pname))){,3} ?x3 . ?x3 (((:pname/^:pbrowserUsed/:pname/^:pname)|(:pname/^:pname))){,3} ?x4 . } }
