PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((:pisSubclassOf/:pname/^:planguage/:pcontent)|(:pisSubclassOf/:pname/^:pname/:pname)) ?x1 . ?x1 (((^:plength/:plength)|(^:pcontent/:pcontent/^:pname/:plocationIP))){,3} ?x2 . ?x0 ((^:phasType/:phasType)) ?x3 . ?x3 ((^:pisSubclassOf/:pname/^:plocationIP/:pcreationDate)|(:pname/^:plocationIP/^:phasModerator/:pcreationDate)|(^:pisSubclassOf/:pname/^:plocationIP/:pcreationDate)) ?x2 . } }
