PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:pname/^:pname)|(:pname/^:pbrowserUsed/:pgender/^:pname)) ?x1 . ?x0 ((:pname/^:pbrowserUsed/:plocationIP/^:pname)|(:pname/^:pcontent/:pimageFile/^:pname)|(:pname/^:plocationIP/:pbrowserUsed/^:pname)) ?x2 . ?x0 ((:pname/^:plocationIP/:pname/^:pname)|(:pname/^:pname)|(:pname/^:pbrowserUsed/:pbrowserUsed/^:pname)) ?x3 . } }
