PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 (((:pcontent/^:pcontent/:pcontent/^:pcontent))){,3} ?x1 . ?x1 (((:pcontent/^:pgender/:pbrowserUsed/^:pcontent))){,3} ?x2 . ?x2 (((:pcontent/^:pcontent))){,3} ?x3 . ?x3 (((:pcontent/^:pname/:pbrowserUsed/^:pcontent)|(:pcontent/^:pname/:pname/^:pcontent)|(:pcontent/^:pname/:pname/^:pcontent))){,3} ?x4 . }  UNION  {  }  UNION  {  } }
