PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pname/^:pname/^:pisSubclassOf)) ?x1 . ?x1 (((:pname/^:pbrowserUsed/:pbrowserUsed/^:pname)|(:pname/^:pimageFile/:planguage/^:pname))){,3} ?x2 . ?x0 ((:pname/^:pbrowserUsed)|(:pname/^:pbrowserUsed)) ?x3 . ?x2 ((:pname/^:pname/:pname/^:plocationIP)) ?x4 . }  UNION  {  } }
