PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:pname/^:pcontent/:pimageFile/^:pname)) ?x1 . ?x1 ((^:pisLocatedIn/:pgender/^:pname)|(^:pisLocatedIn/:pgender/^:pname)|(^:pisLocatedIn/:pname/^:pname)) ?x2 . ?x0 ((:pname/^:pgender/:pemail/^:pname)) ?x3 . ?x3 (((:pname/^:planguage/:pimageFile/^:pname)|(:pname/^:pname)|(:pname/^:planguage/:planguage/^:pname))){,3} ?x2 . } }
