PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pisSubclassOf/:pcontent/^:pname)) ?x1 . ?x1 ((^:pisLocatedIn/:pstudyAt)|(^:pisLocatedIn/:pstudyAt)) ?x2 . ?x2 ((:pname/^:pbrowserUsed/:pemail)) ?x3 . } }
