PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pisPartOf/:pname/^:pname)|(:pname/^:pname/:pspeaks/^:pname)|(^:pisPartOf/^:pisLocatedIn/:pname/^:pname)) ?x1 . ?x1 (((:pname/^:pbrowserUsed/:pbrowserUsed/^:pname)|(:pname/^:pcontent/:planguage/^:pname))){,3} ?x2 . ?x0 ((:pname/^:pspeaks/:pname/^:planguage)) ?x3 . ?x2 ((:pname/^:pspeaks/:pbrowserUsed/^:planguage)|(:pname/^:pspeaks/:plocationIP/^:pimageFile)|(:pname/^:pspeaks/:pbrowserUsed/^:pimageFile)) ?x4 . } }
