PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 ?x3 WHERE {  {  ?x0 ((:plength/^:planguage/:pcontent/^:pname)) ?x1 . ?x1 (((:pname/^:planguage/:pcontent/^:pname)|(:pname/^:pname/:pname/^:pname))){,3} ?x2 . ?x2 ((:pisLocatedIn/^:pisLocatedIn/:pcreationDate)|(:pisLocatedIn/^:pisLocatedIn/:pcreationDate)) ?x3 . } }
