PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((^:pstudyAt/:plikes/^:preplyOf)|(^:pstudyAt/:plikes/^:pisSubclassOf)) ?x1 . ?x0 ((:pname/^:pemail/:phasInterest)|(^:pstudyAt/^:pknows/:pspeaks/^:pname)|(:pisLocatedIn/^:pisLocatedIn/:phasInterest)) ?x2 . ?x1 ((:pname/^:plocationIP/:plikes/:phasTag)|(^:pstudyAt/^:pknows/:phasInterest)|(:pname/^:pspeaks/:phasInterest)) ?x3 . } }
