PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((^:pgender/:plocationIP/^:plocationIP/:pbrowserUsed)|(^:pgender/:plocationIP))){,3} ?x1 . ?x0 (((^:pcontent/:pcontent/^:pname/:pgender)|(^:pname/:pname))){,3} ?x2 . ?x1 (((^:pname/:pname)|(^:pbrowserUsed/:pbrowserUsed/^:planguage/:pimageFile))){,3} ?x3 . } }
