PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 (((^:pname/:pname/^:pcontent/:pimageFile)|(^:pname/:pname)|(^:planguage/:planguage/^:plocationIP/:plocationIP))){,3} ?x1 . ?x1 (((^:pname/:pname/^:pgender/:pgender))){,3} ?x2 . ?x2 (((^:planguage/:pimageFile/^:pcontent/:pimageFile)|(^:pcontent/:planguage/^:pbrowserUsed/:pgender)|(^:plength/:plength))){,3} ?x3 . ?x3 ((^:plocationIP/:plikes/:phasCreator/^:phasCreator)|(^:pemail/^:phasCreator)|(^:pbrowserUsed/:pisLocatedIn/^:pisLocatedIn/:plikes)) ?x4 . }  UNION  {  } }
