PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 (((^:planguage/:pcontent/^:pcontent/:planguage))){,3} ?x1 . ?x1 ((^:planguage/:preplyOf/:pisLocatedIn/^:pisLocatedIn)|(^:planguage/:preplyOf/:pisLocatedIn/^:pisLocatedIn)) ?x2 . ?x2 (((:pname/^:pname)|(:pname/^:pname)|(:pname/^:pcontent/:planguage/^:pname))){,3} ?x3 . ?x3 ((:pname/^:pname/^:pisPartOf/^:pisLocatedIn)|(:pname/^:pname/:pspeaks/^:pname)) ?x4 . } }
