PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pbirthday/^:pknows/:pemail/^:pname)|(^:pcreationDate/:phasCreator/:pemail/^:pname)|(^:pbirthday/:pknows/:pspeaks/^:pname)) ?x1 . ?x0 ((^:pcreationDate/:phasModerator/:pspeaks/^:pname)|(^:pcreationDate/:pknows/:pemail/^:pname)) ?x2 . ?x0 ((^:pbirthday/^:pknows/:pspeaks/^:pname)) ?x3 . }  UNION  {  } }
