PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x3 ?x1 ?x0 WHERE {  {  ?x0 ((:pname/^:plocationIP/:pisLocatedIn/^:pisLocatedIn)|(:pisPartOf/^:pisPartOf/^:pisLocatedIn)|(^:pisLocatedIn/:pisLocatedIn/^:pisLocatedIn)) ?x1 . ?x0 ((:pname/^:pemail/:pemail/^:pname)|(:pisPartOf/^:pisPartOf/^:pisLocatedIn)) ?x2 . ?x0 ((^:pisLocatedIn/:pisLocatedIn/^:pisLocatedIn)|(:pisPartOf/^:pisPartOf/^:pisLocatedIn)) ?x3 . } }
