PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((:plocationIP/^:pname/:pname/^:pbrowserUsed)|(:plocationIP/^:pgender)|(:pbirthday/^:pcreationDate))){,3} ?x1 . ?x1 (((:pbrowserUsed/^:pbrowserUsed/:pbrowserUsed/^:pname))){,3} ?x2 . ?x2 (((:pbrowserUsed/^:pimageFile/:pimageFile/^:plocationIP)|(:pcreationDate/^:pbirthday/:pbrowserUsed/^:plocationIP))){,3} ?x3 . } }
