PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 (((:pname/^:plocationIP/:pbrowserUsed/^:pname)|(:pname/^:pname)|(:pname/^:plocationIP/:plocationIP/^:pname))){,3} ?x1 . ?x1 ((:pname/^:plength/:phasModerator/:pbirthday)|(:pname/^:plength/:phasModerator/:pbirthday)) ?x2 . ?x2 (((^:pcreationDate/:pgender/^:plocationIP/:pcreationDate)|(^:pbirthday/:pbrowserUsed/^:pbrowserUsed/:pcreationDate))){,3} ?x3 . ?x3 (((^:pcreationDate/:plocationIP/^:pbrowserUsed/:pbirthday)|(^:pbirthday/:pbirthday)|(^:pbirthday/:pcreationDate))){,3} ?x4 . }  UNION  {  } }
