PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((^:pname/:pname/^:plocationIP/:pbrowserUsed)|(^:pname/:pgender/^:plocationIP/:pgender))){,3} ?x1 . ?x1 ((^:pgender/^:phasMember)|(^:plength/:phasMember/:pgender/^:plength)) ?x2 . ?x2 (((:pcreationDate/^:pcreationDate)|(:plength/^:pgender/:pgender/^:plength)|(:plength/^:pname/:pname/^:plength))){,3} ?x3 . }  UNION  {  } }
