PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:pisLocatedIn/:pname/^:pcontent/:planguage)|(:pisLocatedIn/:pname/^:pcontent/:planguage)|(:pisLocatedIn/:pname/^:pcontent/:planguage)) ?x1 . ?x0 ((:pisLocatedIn/:pname/^:pcontent/:planguage)) ?x2 . ?x0 ((:pisLocatedIn/:pname/^:pcontent/:planguage)) ?x3 . } }
