PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:pname/^:pname)|(:pname/^:planguage/:pcontent/^:pname)|(:pname/^:pgender/:pname/^:pname))){,3} ?x1 . ?x1 ((^:pworksAt/:plikes/^:preplyOf)) ?x2 . ?x2 (((:planguage/^:planguage)|(:pcontent/^:planguage/:pcontent/^:pcontent))){,3} ?x3 . } }
