PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((:pisLocatedIn/:pisPartOf/^:pisPartOf)) ?x1 . ?x0 ((^:pknows/:pspeaks/^:pname)|(:plikes/^:plikes/:pisLocatedIn)) ?x2 . ?x0 ((:pisLocatedIn/:pisPartOf/^:pisPartOf)|(:pisLocatedIn/^:pisLocatedIn/^:pstudyAt/:pisLocatedIn)) ?x3 . ?x0 ((^:pknows/:pknows/:pisLocatedIn)|(:pisLocatedIn/^:pisLocatedIn/:pknows/:pisLocatedIn)) ?x4 . } }
