PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 (((:pname/^:planguage/:pcontent/^:pname)|(:pname/^:pbrowserUsed/:pbrowserUsed/^:pname))){,3} ?x1 . ?x0 (((:pname/^:plocationIP/:plocationIP/^:pname)|(:pname/^:pname))){,3} ?x2 . ?x0 (((:pname/^:pcontent/:pcontent/^:pname)|(:pname/^:pcontent/:planguage/^:pname)|(:pname/^:pcontent/:planguage/^:pname))){,3} ?x3 . ?x0 (((:pname/^:planguage/:planguage/^:pname)|(:pname/^:planguage/:planguage/^:pname))){,3} ?x4 . }  UNION  {  }  UNION  {  } }
