PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((:pcontent/^:plocationIP/:pbrowserUsed/^:pcontent)|(:pcontent/^:pname/:pname/^:pcontent)|(:pcontent/^:pname/:pname/^:pcontent))){,3} ?x1 . ?x0 (((:pcontent/^:plocationIP/:pname/^:pcontent)|(:pcontent/^:plocationIP/:pbrowserUsed/^:pcontent))){,3} ?x2 . ?x0 (((:pcontent/^:pimageFile/:planguage/^:pcontent)|(:pcontent/^:planguage/:pimageFile/^:pcontent))){,3} ?x3 . ?x0 (((:pcontent/^:pcontent))){,3} ?x4 . }  UNION  {  }  UNION  {  } }
