PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pisPartOf/^:pisLocatedIn/:pgender)|(:pname/^:pbrowserUsed/:pspeaks)|(^:pisLocatedIn/:pname)) ?x1 . ?x0 ((:pname/^:plocationIP)|(:pname/^:pbrowserUsed)) ?x2 . ?x1 ((:pname/^:pname/:pname/^:plocationIP)) ?x3 . } }
