PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pcreationDate/:pbirthday/^:pcreationDate)|(^:pbirthday/:pgender/^:plength)) ?x1 . ?x0 ((^:pcreationDate/:pcreationDate/^:pcreationDate)|(^:pcreationDate/:pbirthday/^:pcreationDate)|(^:pcreationDate/:pgender/^:plength)) ?x2 . ?x0 ((^:pcreationDate/:pbrowserUsed/^:plength)) ?x3 . ?x0 ((^:pcreationDate/:plocationIP/^:plength)|(^:pcreationDate/:pcreationDate/^:pcreationDate)) ?x4 . } }
