PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x3 ?x0 ?x1 WHERE {  {  ?x0 (((:planguage/^:plocationIP/:pname/^:planguage)|(:pcontent/^:planguage))){,3} ?x1 . ?x1 ((:pisSubclassOf/^:plikes/:pcreationDate)) ?x2 . ?x0 (((:planguage/^:pbrowserUsed/:pbrowserUsed/^:pcontent))){,3} ?x3 . ?x2 (((:planguage/^:plocationIP/:pbrowserUsed/^:pcontent))){,3} ?x4 . }  UNION  {  } }
