PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pname/^:planguage/:pimageFile/^:pname)|(:pname/^:pgender/:pbrowserUsed/^:pname)|(:pname/^:pcontent/:planguage/^:pname)) ?x1 . ?x1 (((:pname/^:pname)|(:pname/^:pname/:pname/^:pname))){,3} ?x2 . ?x2 ((:pisPartOf/:pname/^:pcontent)|(:pisPartOf/:pname/^:pcontent)|(:pname/^:pspeaks/:pbrowserUsed/^:pcontent)) ?x3 . }  UNION  {  }  UNION  {  } }
