PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:preplyOf/^:plikes/:plocationIP/^:pname)) ?x1 . ?x1 (((:pname/^:plocationIP/:plocationIP/^:pname))){,3} ?x2 . ?x2 ((:pname/^:pbrowserUsed/:pemail/^:pname)) ?x3 . } }
