PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x3 ?x1 WHERE {  {  ?x0 (((:pname/^:plocationIP/:pname/^:pname))){,3} ?x1 . ?x1 ((^:pworksAt/:plocationIP)) ?x2 . ?x2 (((^:planguage/:pcontent/^:pgender/:plocationIP))){,3} ?x3 . }  UNION  {  }  UNION  {  } }
