PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 (((:pname/^:pname/:pname/^:pname))){,3} ?x1 . ?x1 ((:pname/^:plength/:phasMember/:pemail)) ?x2 . ?x2 (((^:pname/:plocationIP/^:pname/:pgender)|(^:plength/:plength)|(^:pname/:pbrowserUsed/^:pname/:plocationIP))){,3} ?x3 . } }
