PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pname/^:pimageFile/:pcontent)|(:pname/^:planguage/:pimageFile)|(:pname/^:pname/:pgender)) ?x1 . ?x1 ((^:pname/:pknows/:pstudyAt)|(^:pname/:pknows/:pgender/^:pname)|(^:pgender/:pknows/:plocationIP/^:pname)) ?x2 . ?x2 (((:pname/^:pname)|(:pname/^:pgender/:plocationIP/^:pname))){,3} ?x3 . ?x3 ((^:pstudyAt/:plocationIP/^:pname/^:phasCreator)|(^:pstudyAt/^:phasCreator)) ?x4 . }  UNION  {  } }
