PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:pgender/^:pbrowserUsed/:plocationIP/^:pbrowserUsed)|(:pname/^:pgender/:pbrowserUsed/^:pgender)|(:pgender/^:plocationIP/:plocationIP/^:plocationIP))){,3} ?x1 . ?x0 (((:pgender/^:pname)|(:pcreationDate/^:pbirthday/:plocationIP/^:pbrowserUsed)|(:plocationIP/^:pgender/:pbrowserUsed/^:pbrowserUsed))){,3} ?x2 . ?x1 (((:pbirthday/^:pcreationDate)|(:pname/^:pimageFile/:pcontent/^:pgender))){,3} ?x3 . } }
