PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((:pcreationDate/^:pbirthday/:plocationIP/^:plength))){,3} ?x1 . ?x0 (((:plength/^:plength)|(:plength/^:planguage/:pimageFile/^:plength))){,3} ?x2 . ?x0 (((:plength/^:pgender/:pname/^:plength)|(:plength/^:plength)|(:plength/^:plocationIP/:pgender/^:plength))){,3} ?x3 . } }
