PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pisSubclassOf/:phasCreator/:pspeaks/^:pname)|(:preplyOf/^:plikes/:pstudyAt)) ?x1 . ?x0 ((:pisSubclassOf/^:plikes/:plocationIP/^:pname)|(:pisSubclassOf/^:plikes/:pstudyAt)) ?x2 . ?x0 ((:preplyOf/^:plikes/:pstudyAt)|(:pisSubclassOf/^:plikes/:pstudyAt)|(:preplyOf/^:plikes/:pbrowserUsed/^:pname)) ?x3 . }  UNION  {  }  UNION  {  }  UNION  {  } }
