PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x3 ?x2 ?x0 WHERE {  {  ?x0 (((:pname/^:plocationIP/:plocationIP/^:pname))){,3} ?x1 . ?x0 (((:pname/^:pname/:pname/^:pname)|(:pname/^:pgender/:plocationIP/^:pname))){,3} ?x2 . ?x0 (((:pname/^:plength/:plength/^:pname))){,3} ?x3 . ?x0 (((:pname/^:pname)|(:pname/^:planguage/:pimageFile/^:pname)|(:pname/^:pcontent/:pcontent/^:pname))){,3} ?x4 . }  UNION  {  } }
