PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 ?x1 ?x2 WHERE {  {  ?x0 ((^:phasCreator/:plocationIP/^:pgender/:pgender)|(^:phasCreator/:pbrowserUsed)) ?x1 . ?x0 ((:plikes/:pisLocatedIn)|(^:phasCreator/:pisLocatedIn)) ?x2 . ?x1 ((^:phasCreator/:phasTag/:pname/^:pname)|(^:phasModerator/:phasModerator/:pgender/^:pname)|(^:phasModerator/:phasMember/:pbrowserUsed/^:pname)) ?x3 . }  UNION  {  }  UNION  {  } }
