PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((:pgender/^:plocationIP/:pbirthday/^:pbirthday)|(:pname/^:plocationIP)|(:pbrowserUsed/^:pname))){,3} ?x1 . ?x0 (((:plocationIP/^:pgender))){,3} ?x2 . ?x1 (((:pname/^:pname/:pname/^:pgender)|(:pbrowserUsed/^:plocationIP/:plocationIP/^:pgender)|(:pname/^:plocationIP/:plocationIP/^:pbrowserUsed))){,3} ?x3 . } }
