PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 (((:pname/^:pname)|(:pname/^:pname)|(:pname/^:pname))){,3} ?x1 . ?x1 ((:pname/^:pname/:pname/^:pname)) ?x2 . ?x0 (((:pname/^:pname)|(:pname/^:pcontent/:pcontent/^:pname)|(:pname/^:pname/:pname/^:pname))){,3} ?x3 . ?x2 (((:pname/^:pimageFile/:pimageFile/^:pname)|(:pname/^:pcontent/:planguage/^:pname)|(:pname/^:pbrowserUsed/:pbrowserUsed/^:pname))){,3} ?x4 . } }
