PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:phasInterest/:phasType)|(:phasInterest/:phasType)) ?x1 . ?x0 ((:phasInterest/:phasType)) ?x2 . ?x0 ((:pisLocatedIn/^:pisLocatedIn/:pspeaks/^:pname)|(^:phasCreator/:phasTag/:phasType)|(:plikes/:phasCreator/:phasInterest/:phasType)) ?x3 . ?x0 ((:plikes/:phasTag/:phasType)|(:pisLocatedIn/:pname/^:pname/^:pisSubclassOf)|(:pbrowserUsed/^:pemail/:phasInterest/:phasType)) ?x4 . } }
