PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 ?x2 ?x1 WHERE {  {  ?x0 (((:pimageFile/^:plocationIP/:pgender/^:pimageFile)|(:planguage/^:pcontent))){,3} ?x1 . ?x1 (((:pcontent/^:pcontent/:pimageFile/^:pcontent))){,3} ?x2 . ?x2 ((^:pcontainerOf/:phasMember/:plocationIP)) ?x3 . } }
