PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pReference/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)) ?x1 . ?x0 ((^:pReference/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)) ?x2 . ?x0 ((^:pReference/:pReference/:pAuthoredBy)) ?x3 . ?x0 ((^:pReference/^:pInteracts/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)) ?x4 . } }
