PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:pInteracts/:pInteracts/^:pInteracts)|(:pInteracts/:pInteracts/:pInteracts/:pInteracts)|(^:pInteracts/^:pInteracts))){,3} ?x1 . ?x1 ((:pReference/^:pReference)) ?x2 . ?x2 ((^:pInteracts/:pInteracts/:pInteracts)|(:pInteracts/^:pInteracts)|(^:pInteracts/^:pInteracts)) ?x3 . ?x3 ((:pInteracts/:pOccursIn/^:pOccursIn/^:pInteracts)) ?x4 . } }
