PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pReference/^:pInteracts)|(^:pReference/^:pInteracts/:pInteracts)) ?x1 . ?x0 ((^:pReference/^:pInteracts/:pInteracts)) ?x2 . ?x0 ((^:pReference/^:pInteracts/:pInteracts/:pInteracts)|(^:pReference/:pInteracts)|(^:pReference/:pInteracts/:pInteracts)) ?x3 . ?x0 ((^:pReference/^:pInteracts)|(^:pReference/^:pInteracts)) ?x4 . } }
