PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pEncodedOn/^:pInteracts/:pInteracts/^:pInteracts)|(^:pEncodedOn/:pInteracts)|(^:pEncodedOn/:pInteracts/^:pInteracts)) ?x1 . ?x0 ((^:pEncodedOn/:pReference/:pPublishedIn)|(^:pEncodedOn/:pReference/:pPublishedIn)|(^:pEncodedOn/:pReference/:pPublishedIn)) ?x2 . ?x1 ((^:pEncodedOn/:pInteracts/:pReference/:pPublishedIn)|(^:pEncodedOn/:pReference/:pPublishedIn)) ?x3 . } }
