PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pPublishedIn/^:pPublishedIn/:pPublishedIn)) ?x1 . ?x1 ((^:pPublishedIn/^:pReference/:pInteracts)) ?x2 . ?x2 ((^:pInteracts/^:pInteracts/:pReference)|(:pInteracts/^:pInteracts/:pReference)|(:pInteracts/:pInteracts/:pInteracts/:pReference)) ?x3 . } }
