PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pEncodedOn/:pOccursIn/^:pOccursIn)|(^:pEncodedOn/:pReference/^:pReference)|(^:pEncodedOn/^:pInteracts/:pHasKeyword/^:pHasKeyword)) ?x1 . ?x1 ((:pReference/:pPublishedIn)|(:pReference/:pPublishedIn)) ?x2 . ?x2 ((^:pPublishedIn/:pAuthoredBy/^:pAuthoredBy)|(^:pPublishedIn/:pAuthoredBy/^:pAuthoredBy)|(^:pPublishedIn/^:pReference/^:pInteracts/:pReference)) ?x3 . } }
