PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 ?x3 WHERE {  {  ?x0 ((^:pHasKeyword/:pReference/:pPublishedIn)|(^:pHasKeyword/:pReference/:pPublishedIn)) ?x1 . ?x1 ((^:pPublishedIn/^:pReference/:pOccursIn)) ?x2 . ?x0 ((^:pHasKeyword/^:pInteracts/^:pInteracts/:pHasKeyword)|(^:pHasKeyword/:pInteracts/:pHasKeyword)) ?x3 . ?x2 ((^:pHasKeyword/^:pInteracts/:pHasKeyword)|(^:pHasKeyword/:pHasKeyword)|(^:pHasKeyword/:pEncodedOn/^:pEncodedOn/:pHasKeyword)) ?x4 . } }
