PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pPublishedIn/:pPublishedIn/^:pPublishedIn)) ?x1 . ?x1 ((^:pReference/:pHasKeyword)|(^:pReference/:pEncodedOn/^:pEncodedOn/:pHasKeyword)|(^:pReference/^:pInteracts/:pHasKeyword)) ?x2 . ?x2 ((^:pHasKeyword/:pInteracts/:pEncodedOn)) ?x3 . } }
