PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 ?x3 WHERE {  {  ?x0 ((^:pHasKeyword/:pOccursIn/^:pOccursIn/:pReference)|(^:pHasKeyword/:pReference)|(^:pHasKeyword/:pInteracts/:pReference)) ?x1 . ?x1 ((^:pReference/:pReference/^:pReference)) ?x2 . ?x0 ((^:pHasKeyword/:pReference/^:pReference/:pInteracts)|(^:pHasKeyword/:pInteracts/^:pInteracts/^:pInteracts)) ?x3 . ?x3 ((^:pInteracts/^:pInteracts/:pEncodedOn)|(:pInteracts/:pEncodedOn)|(^:pInteracts/^:pInteracts/:pInteracts/:pEncodedOn)) ?x2 . } }
