PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((^:pEncodedOn/^:pInteracts/^:pInteracts)|(^:pEncodedOn/:pInteracts)|(^:pEncodedOn/^:pInteracts/^:pInteracts)) ?x1 . ?x1 ((:pInteracts/:pReference/:pPublishedIn)|(:pInteracts/:pReference/:pPublishedIn)) ?x2 . ?x2 ((^:pPublishedIn/^:pReference/:pReference)) ?x3 . ?x3 ((:pPublishedIn/^:pPublishedIn/:pPublishedIn)|(^:pReference/:pInteracts/:pReference/:pPublishedIn)|(:pAuthoredBy/^:pAuthoredBy/:pPublishedIn)) ?x4 . } }
