PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:pOccursIn/:pHasKeyword)|(^:pOccursIn/:pHasKeyword/^:pHasKeyword/:pHasKeyword)) ?x1 . ?x1 ((^:pHasKeyword/^:pInteracts/:pOccursIn)|(^:pHasKeyword/^:pInteracts/:pOccursIn)) ?x2 . ?x0 ((^:pOccursIn/:pReference/:pPublishedIn)|(^:pOccursIn/^:pInteracts/:pReference/:pPublishedIn)) ?x3 . ?x3 ((^:pPublishedIn/^:pReference/^:pInteracts/:pHasKeyword)) ?x2 . } }
