PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pReference/:pInteracts/:pEncodedOn)|(^:pReference/:pEncodedOn)|(^:pReference/:pInteracts/:pEncodedOn)) ?x1 . ?x1 ((^:pEncodedOn/:pInteracts/^:pInteracts)|(^:pEncodedOn/^:pInteracts)) ?x2 . ?x0 ((:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)|(:pPublishedIn/^:pPublishedIn/:pAuthoredBy)) ?x3 . ?x2 ((:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)|(:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(:pPublishedIn/^:pPublishedIn/:pAuthoredBy)) ?x4 . } }
