PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pOccursIn/^:pInteracts/:pEncodedOn/^:pEncodedOn)|(^:pOccursIn/:pHasKeyword/^:pHasKeyword)|(^:pOccursIn/:pInteracts)) ?x1 . ?x1 ((:pInteracts/:pOccursIn)|(:pInteracts/:pInteracts/^:pInteracts/:pOccursIn)|(:pInteracts/:pOccursIn)) ?x2 . ?x2 ((^:pOccursIn/:pInteracts/:pReference/:pAuthoredBy)) ?x3 . ?x3 ((^:pAuthoredBy/:pPublishedIn/^:pPublishedIn/:pPublishedIn)) ?x4 . } }
