PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pHasKeyword/:pInteracts/:pInteracts/:pPublishedIn/^:pPublishedIn/^:pReference/:pEncodedOn)) ?x1 . ?x0 ((:pInteracts/^:pInteracts/:pAuthoredBy/^:pAuthoredBy/^:pReference/:pEncodedOn)|(:pInteracts/:pInteracts/^:pReference/:pHasKeyword/^:pHasKeyword/:pEncodedOn)|(^:pInteracts/:pInteracts/:pInteracts/:pPublishedIn/^:pPublishedIn/^:pReference/:pEncodedOn)) ?x2 . ?x0 ((^:pHasKeyword/^:pInteracts/:pInteracts/:pOccursIn/^:pReference/:pReference/^:pReference/:pEncodedOn)|(^:pHasKeyword/:pOccursIn/^:pReference/:pReference/^:pReference/:pEncodedOn)|(^:pHasKeyword/:pOccursIn/:pPublishedIn/^:pPublishedIn/^:pReference/:pEncodedOn)) ?x3 . ?x0 ((^:pReference/:pHasKeyword/^:pHasKeyword/:pEncodedOn)|(:pAuthoredBy/^:pAuthoredBy/^:pReference/:pEncodedOn)|(^:pReference/:pReference/^:pReference/:pEncodedOn)) ?x4 . }  UNION  {  } }
