PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:pPublishedIn/^:pReference/^:pInteracts/:pReference)) ?x1 . ?x1 ((^:pReference/^:pInteracts/:pHasKeyword)|(^:pReference/:pHasKeyword)) ?x2 . ?x0 ((^:pPublishedIn/:pPublishedIn/^:pPublishedIn/:pPublishedIn)|(^:pPublishedIn/:pPublishedIn)) ?x3 . ?x2 ((^:pPublishedIn/:pPublishedIn)|(^:pPublishedIn/^:pReference/:pReference/:pPublishedIn)) ?x4 . } }
