PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pReference/:pPublishedIn/^:pPublishedIn)) ?x1 . ?x1 ((:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)|(:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)) ?x2 . ?x2 ((^:pAuthoredBy/^:pReference/^:pInteracts/^:pInteracts)|(^:pAuthoredBy/^:pReference/:pInteracts/^:pInteracts)) ?x3 . } }
