PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pReference/:pHasKeyword/^:pHasKeyword/:pOccursIn)) ?x1 . ?x0 ((^:pReference/^:pInteracts/:pOccursIn)|(^:pReference/:pInteracts/^:pInteracts/:pOccursIn)) ?x2 . ?x0 ((^:pReference/:pInteracts/:pOccursIn)|(^:pReference/:pOccursIn)) ?x3 . ?x0 ((^:pReference/:pOccursIn/^:pOccursIn/:pOccursIn)|(^:pReference/:pInteracts/^:pInteracts/:pOccursIn)|(^:pReference/:pOccursIn)) ?x4 . } }
