PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)) ?x1 . ?x1 ((:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)|(:pPublishedIn/^:pPublishedIn/:pAuthoredBy)) ?x2 . ?x0 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)) ?x3 . ?x2 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)) ?x4 . } }
