PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pEncodedOn/^:pEncodedOn/:pInteracts/:pEncodedOn)|(^:pInteracts/:pHasKeyword/^:pHasKeyword/:pEncodedOn)|(:pReference/^:pReference/:pEncodedOn)) ?x1 . ?x0 ((:pHasKeyword/^:pHasKeyword/:pEncodedOn)) ?x2 . ?x0 ((:pReference/^:pReference/:pEncodedOn)|(:pEncodedOn/^:pEncodedOn/:pEncodedOn)|(:pEncodedOn/^:pEncodedOn/:pEncodedOn)) ?x3 . } }
