PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pOccursIn/:pReference/:pAuthoredBy)|(^:pOccursIn/^:pInteracts/:pReference/:pAuthoredBy)) ?x1 . ?x0 ((^:pOccursIn/^:pInteracts/:pReference/:pAuthoredBy)|(^:pOccursIn/^:pInteracts/:pReference/:pAuthoredBy)|(^:pOccursIn/:pReference/:pAuthoredBy)) ?x2 . ?x0 ((^:pOccursIn/:pInteracts/:pReference/:pAuthoredBy)) ?x3 . ?x0 ((^:pOccursIn/:pReference/:pAuthoredBy)|(^:pOccursIn/:pInteracts/:pReference/:pAuthoredBy)|(^:pOccursIn/:pReference/:pAuthoredBy)) ?x4 . } }
