PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pOccursIn/:pInteracts/:pOccursIn)) ?x1 . ?x0 ((^:pOccursIn/^:pInteracts/:pReference/:pPublishedIn)|(^:pOccursIn/:pReference/:pPublishedIn)|(^:pOccursIn/^:pInteracts/:pReference/:pPublishedIn)) ?x2 . ?x2 ((^:pPublishedIn/^:pReference/:pHasKeyword)|(^:pPublishedIn/^:pReference/:pHasKeyword)) ?x1 . } }
