PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pReference/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)|(^:pReference/:pReference/:pAuthoredBy)) ?x1 . ?x1 ((^:pAuthoredBy/^:pReference/:pReference/:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy)) ?x2 . ?x0 ((:pAuthoredBy)|(:pAuthoredBy)|(:pAuthoredBy)) ?x3 . ?x3 ((^:pAuthoredBy/^:pReference/^:pInteracts)|(^:pAuthoredBy/^:pReference)) ?x2 . } }
