PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:pPublishedIn/^:pReference/^:pInteracts/:pEncodedOn)|(^:pPublishedIn/^:pReference/:pInteracts/:pEncodedOn)) ?x1 . ?x1 ((^:pEncodedOn/:pReference/:pPublishedIn/^:pPublishedIn)|(^:pEncodedOn/:pReference/^:pReference/:pReference)|(^:pEncodedOn/:pReference/:pPublishedIn/^:pPublishedIn)) ?x2 . ?x2 ((^:pReference/^:pInteracts/:pReference/:pPublishedIn)) ?x3 . } }
