PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pPublishedIn/:pAuthoredBy/^:pAuthoredBy)|(^:pPublishedIn/:pAuthoredBy/^:pAuthoredBy)|(^:pPublishedIn/:pPublishedIn/^:pPublishedIn)) ?x1 . ?x1 ((^:pReference/:pInteracts/:pEncodedOn)|(^:pReference/^:pInteracts/:pEncodedOn)|(^:pReference/^:pInteracts/:pInteracts/:pEncodedOn)) ?x2 . ?x2 ((^:pEncodedOn/:pReference/:pAuthoredBy)|(^:pEncodedOn/:pReference/:pAuthoredBy)|(^:pEncodedOn/:pInteracts/:pReference/:pAuthoredBy)) ?x3 . ?x3 ((^:pAuthoredBy/^:pReference/:pReference/:pPublishedIn)|(^:pAuthoredBy/:pPublishedIn)|(^:pAuthoredBy/^:pReference/:pReference/:pPublishedIn)) ?x4 . } }
