PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)) ?x1 . ?x0 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)|(^:pAuthoredBy/:pPublishedIn/^:pPublishedIn)) ?x2 . ?x1 ((^:pAuthoredBy/:pPublishedIn/^:pPublishedIn)|(^:pAuthoredBy/:pPublishedIn/^:pPublishedIn)|(^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)) ?x3 . } }
