PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pHasKeyword/:pOccursIn)|(^:pHasKeyword/^:pInteracts/:pInteracts/:pOccursIn)) ?x1 . ?x1 ((^:pOccursIn/:pHasKeyword/^:pHasKeyword/:pHasKeyword)|(^:pOccursIn/^:pInteracts/:pHasKeyword)|(^:pOccursIn/^:pInteracts/:pHasKeyword)) ?x2 . ?x0 ((^:pHasKeyword/:pInteracts/:pReference/:pPublishedIn)) ?x3 . ?x2 ((^:pHasKeyword/:pReference/:pPublishedIn)|(^:pHasKeyword/^:pInteracts/:pReference/:pPublishedIn)|(^:pHasKeyword/:pInteracts/:pReference/:pPublishedIn)) ?x4 . } }
