PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:pOccursIn/:pHasKeyword/^:pHasKeyword/:pEncodedOn)) ?x1 . ?x1 ((^:pEncodedOn/:pReference/^:pReference/:pReference)|(^:pEncodedOn/:pOccursIn/^:pOccursIn/:pReference)|(^:pEncodedOn/:pEncodedOn/^:pEncodedOn/:pReference)) ?x2 . ?x0 ((^:pOccursIn/:pReference/:pAuthoredBy/^:pAuthoredBy)) ?x3 . ?x3 ((^:pReference/:pReference)|(^:pReference/:pInteracts/:pReference)) ?x2 . } }
