PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 ((^:pPublishedIn/^:pReference/:pReference/:pPublishedIn)|(^:pPublishedIn/^:pReference/:pReference/:pPublishedIn)|(^:pPublishedIn/:pPublishedIn)) ?x1 . ?x1 ((^:pPublishedIn/^:pReference/:pEncodedOn)|(^:pPublishedIn/^:pReference/:pInteracts/:pEncodedOn)|(^:pPublishedIn/^:pReference/:pEncodedOn)) ?x2 . ?x2 ((^:pEncodedOn/:pReference)|(^:pEncodedOn/:pReference)|(^:pEncodedOn/:pInteracts/:pReference)) ?x3 . ?x3 ((^:pReference/:pInteracts/:pInteracts/:pEncodedOn)|(^:pReference/^:pInteracts/:pEncodedOn)) ?x4 . } }
