PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((^:pAuthoredBy/:pPublishedIn)|(^:pAuthoredBy/^:pReference/:pReference/:pPublishedIn)|(^:pAuthoredBy/:pPublishedIn)) ?x1 . ?x0 ((^:pAuthoredBy/^:pReference/^:pInteracts)|(^:pAuthoredBy/^:pReference/^:pInteracts/^:pInteracts)|(^:pAuthoredBy/^:pReference)) ?x2 . ?x2 ((^:pInteracts/:pReference)|(:pInteracts/:pInteracts/:pReference)) ?x1 . } }
