PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((:pInteracts/:pInteracts/:pInteracts/:pInteracts))){,3} ?x1 . ?x1 ((:pInteracts/:pInteracts/:pHasKeyword)|(^:pInteracts/:pReference/^:pReference/:pHasKeyword)|(:pHasKeyword/^:pHasKeyword/:pHasKeyword)) ?x2 . ?x2 ((^:pHasKeyword/:pInteracts/:pReference/:pPublishedIn)|(^:pHasKeyword/^:pInteracts/:pReference/:pPublishedIn)|(^:pHasKeyword/:pReference/:pPublishedIn)) ?x3 . } }
