PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((:pHasKeyword/^:pHasKeyword/:pHasKeyword/^:pHasKeyword)|(^:pInteracts/^:pInteracts/:pEncodedOn/^:pEncodedOn)) ?x1 . ?x0 ((:pHasKeyword/^:pHasKeyword)) ?x2 . ?x0 ((:pHasKeyword/^:pHasKeyword)|(:pHasKeyword/^:pHasKeyword/:pInteracts)) ?x3 . } }
