PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pEncodedOn/:pReference/:pAuthoredBy)) ?x1 . ?x1 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)|(^:pAuthoredBy/:pPublishedIn/^:pPublishedIn)) ?x2 . ?x2 ((^:pReference/:pInteracts/:pHasKeyword)|(:pAuthoredBy/^:pAuthoredBy/^:pReference/:pHasKeyword)) ?x3 . ?x3 ((^:pHasKeyword/:pHasKeyword/^:pHasKeyword)) ?x4 . } }
