PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pEncodedOn/:pReference/^:pReference)|(^:pEncodedOn/:pReference/^:pReference)) ?x1 . ?x1 ((:pReference/:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(:pReference/:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(:pEncodedOn/^:pEncodedOn/:pReference/:pAuthoredBy)) ?x2 . ?x0 ((^:pEncodedOn/:pReference)) ?x3 . ?x3 ((^:pReference/^:pInteracts/:pInteracts/^:pInteracts)) ?x2 . } }
