PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((^:pAuthoredBy/^:pReference/:pReference)|(^:pAuthoredBy/^:pReference/:pReference)|(^:pAuthoredBy/^:pReference/:pInteracts/:pReference)) ?x1 . ?x0 ((^:pAuthoredBy/^:pReference/:pInteracts)) ?x2 . ?x2 (((^:pInteracts/:pInteracts))){,3} ?x1 . } }
