PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:pAuthoredBy/^:pReference/:pInteracts/:pHasKeyword)) ?x1 . ?x1 ((^:pHasKeyword/:pReference/:pAuthoredBy)|(^:pHasKeyword/:pReference/:pAuthoredBy)) ?x2 . ?x0 ((^:pAuthoredBy/^:pReference/:pOccursIn)) ?x3 . ?x3 ((^:pOccursIn/^:pInteracts)|(^:pOccursIn/^:pInteracts/:pEncodedOn/^:pEncodedOn)) ?x2 . } }
