PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pEncodedOn/:pReference)) ?x1 . ?x1 ((^:pReference/^:pInteracts/^:pInteracts/^:pInteracts)|(^:pReference/:pInteracts)|(^:pReference/:pInteracts)) ?x2 . ?x2 (((:pInteracts/:pInteracts/^:pInteracts)|(^:pInteracts/:pInteracts/^:pInteracts/^:pInteracts)|(:pInteracts/^:pInteracts/^:pInteracts))){,3} ?x3 . } }
