PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((^:pPublishedIn/:pAuthoredBy)|(^:pPublishedIn/:pAuthoredBy)) ?x1 . ?x1 ((^:pAuthoredBy/^:pReference/:pReference)|(^:pAuthoredBy/^:pReference/^:pInteracts/:pReference)) ?x2 . ?x0 ((^:pPublishedIn/^:pReference)) ?x3 . ?x2 ((^:pPublishedIn/^:pReference/:pEncodedOn/^:pEncodedOn)) ?x4 . } }
