PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:pAuthoredBy/^:pReference/:pOccursIn/^:pOccursIn)|(^:pAuthoredBy/^:pReference/:pEncodedOn/^:pEncodedOn)) ?x1 . ?x1 (((^:pInteracts/^:pInteracts))){,3} ?x2 . ?x0 ((^:pAuthoredBy/^:pReference/:pOccursIn/^:pOccursIn)|(^:pAuthoredBy/^:pReference/:pReference/^:pReference)) ?x3 . ?x3 (((^:pInteracts/^:pInteracts)|(^:pInteracts/^:pInteracts/:pInteracts)|(^:pInteracts/:pInteracts/:pInteracts/:pInteracts))){,3} ?x2 . } }
