PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:pOccursIn/:pInteracts/:pInteracts/:pHasKeyword)|(^:pOccursIn/:pHasKeyword)|(^:pOccursIn/:pHasKeyword)) ?x1 . ?x0 ((^:pOccursIn/:pHasKeyword)|(^:pOccursIn/:pReference/^:pReference/:pHasKeyword)|(^:pOccursIn/^:pInteracts/:pInteracts/:pHasKeyword)) ?x2 . ?x0 ((^:pOccursIn/:pHasKeyword)|(^:pOccursIn/:pInteracts/:pInteracts/:pHasKeyword)) ?x3 . } }
