PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pHasKeyword/:pEncodedOn)|(^:pHasKeyword/^:pInteracts/:pEncodedOn)) ?x1 . ?x1 ((^:pEncodedOn/:pInteracts/^:pInteracts/:pReference)) ?x2 . ?x2 ((:pPublishedIn/^:pPublishedIn)|(:pPublishedIn/^:pPublishedIn)) ?x3 . ?x3 ((^:pReference/:pInteracts/:pHasKeyword)|(^:pReference/:pEncodedOn/^:pEncodedOn/:pHasKeyword)|(^:pReference/:pHasKeyword/^:pHasKeyword/:pHasKeyword)) ?x4 . } }
