PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((:pInteracts/^:pInteracts/^:pInteracts/:pReference)) ?x1 . ?x0 ((:pInteracts/:pInteracts)|(^:pInteracts/^:pInteracts/^:pInteracts/:pInteracts)|(^:pInteracts/^:pInteracts)) ?x2 . ?x1 ((^:pInteracts/:pInteracts/^:pInteracts)|(^:pInteracts/:pInteracts/:pInteracts/^:pInteracts)|(^:pInteracts/^:pInteracts)) ?x3 . } }
