PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pOccursIn/:pReference)|(^:pOccursIn/^:pInteracts/:pReference)) ?x1 . ?x1 ((^:pReference/:pInteracts/:pReference/:pAuthoredBy)) ?x2 . ?x2 ((^:pAuthoredBy/:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(^:pAuthoredBy/:pPublishedIn/^:pPublishedIn/:pAuthoredBy)|(^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy/:pAuthoredBy)) ?x3 . ?x3 ((^:pAuthoredBy/:pAuthoredBy/^:pAuthoredBy)|(^:pAuthoredBy/:pPublishedIn/^:pPublishedIn)) ?x4 . } }
