PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 ((^:pOccursIn/:pReference/:pAuthoredBy)|(^:pOccursIn/:pReference/:pAuthoredBy)|(^:pOccursIn/:pReference/:pAuthoredBy)) ?x1 . ?x1 ((^:pAuthoredBy/^:pReference/:pOccursIn)|(^:pAuthoredBy/^:pReference/:pOccursIn)) ?x2 . ?x2 ((^:pOccursIn/:pReference/:pPublishedIn)|(^:pOccursIn/:pReference/:pPublishedIn)|(^:pOccursIn/:pReference/:pPublishedIn)) ?x3 . } }
