PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pPublishedIn/^:pReference/:pReference)) ?x1 . ?x0 ((^:pPublishedIn/^:pReference/:pInteracts/:pReference)|(^:pPublishedIn/:pAuthoredBy/^:pAuthoredBy)|(^:pPublishedIn/^:pReference/:pInteracts/:pReference)) ?x2 . ?x0 ((^:pPublishedIn/^:pReference/^:pInteracts/:pReference)|(^:pPublishedIn/:pPublishedIn/^:pPublishedIn)) ?x3 . ?x0 ((^:pPublishedIn/:pPublishedIn/^:pPublishedIn)) ?x4 . } }
