PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:pEncodedOn/:pReference/:pPublishedIn/^:pPublishedIn)|(^:pEncodedOn/:pReference/:pPublishedIn/^:pPublishedIn)) ?x1 . ?x1 ((^:pReference/:pReference/:pAuthoredBy)) ?x2 . ?x0 ((^:pEncodedOn/:pReference/:pAuthoredBy/^:pAuthoredBy)|(^:pEncodedOn/:pEncodedOn/^:pEncodedOn/:pReference)) ?x3 . ?x2 ((^:pEncodedOn/:pReference/:pPublishedIn/^:pPublishedIn)) ?x4 . } }
