PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 (((^:pInteracts/:pInteracts/^:pInteracts)|(^:pInteracts/:pInteracts))){,3} ?x1 . ?x0 (((:pInteracts/^:pInteracts/:pInteracts)|(:pInteracts/^:pInteracts/^:pInteracts)|(:pInteracts/^:pInteracts/:pInteracts))){,3} ?x2 . ?x2 (((^:pInteracts/:pInteracts/^:pInteracts)|(^:pInteracts/^:pInteracts))){,3} ?x1 . } }
