PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pReference/:pReference/:pPublishedIn)|(^:pReference/:pReference/:pPublishedIn)|(^:pReference/:pInteracts/:pReference/:pPublishedIn)) ?x1 . ?x1 ((^:pPublishedIn/:pAuthoredBy/^:pAuthoredBy/:pPublishedIn)|(^:pPublishedIn/:pPublishedIn)) ?x2 . ?x2 ((^:pPublishedIn/^:pReference/:pReference/:pAuthoredBy)) ?x3 . } }
