PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pHasKeyword/^:pHasKeyword)|(^:pInteracts/:pHasKeyword/^:pHasKeyword)|(:pEncodedOn/^:pEncodedOn/:pInteracts)) ?x1 . ?x0 ((:pInteracts/:pHasKeyword/^:pHasKeyword)|(:pHasKeyword/^:pHasKeyword)|(:pOccursIn/^:pOccursIn/:pReference/^:pReference)) ?x2 . ?x0 ((:pOccursIn/^:pOccursIn/:pInteracts/^:pInteracts)|(:pEncodedOn/^:pEncodedOn/:pInteracts/^:pInteracts)|(^:pInteracts/:pReference/^:pReference)) ?x3 . ?x0 ((^:pInteracts/:pOccursIn/^:pOccursIn)) ?x4 . } }
