PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pAuthoredBy/^:pAuthoredBy/^:pReference/:pEncodedOn)|(^:pReference/:pEncodedOn/^:pEncodedOn/:pEncodedOn)) ?x1 . ?x0 ((^:pReference/:pEncodedOn/^:pEncodedOn)|(^:pReference/:pReference/^:pReference/^:pInteracts)|(^:pReference/^:pInteracts/:pReference/^:pReference)) ?x2 . ?x1 ((^:pReference/^:pInteracts/:pReference/^:pReference)|(^:pReference/:pReference/^:pReference)) ?x3 . } }
