PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pHasKeyword/^:pHasKeyword/:pInteracts)|(:pInteracts/^:pInteracts/:pOccursIn/^:pOccursIn)) ?x1 . ?x0 ((:pReference/^:pReference)|(:pEncodedOn/^:pEncodedOn)) ?x2 . ?x0 ((:pOccursIn/^:pOccursIn/:pInteracts)) ?x3 . } }
