PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((^:pHasKeyword/:pInteracts/:pHasKeyword)|(^:pHasKeyword/:pHasKeyword)|(^:pHasKeyword/:pInteracts/^:pInteracts/:pHasKeyword)) ?x1 . ?x0 ((^:pHasKeyword/^:pInteracts/:pInteracts/:pHasKeyword)|(^:pHasKeyword/:pHasKeyword)|(^:pHasKeyword/:pHasKeyword)) ?x2 . ?x0 ((^:pHasKeyword/:pHasKeyword)) ?x3 . ?x0 ((^:pHasKeyword/:pHasKeyword)|(^:pHasKeyword/:pReference/^:pReference/:pHasKeyword)|(^:pHasKeyword/:pInteracts/:pHasKeyword)) ?x4 . } }
