PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:pReference/:pReference/^:pReference)) ?x1 . ?x1 (((:pInteracts/:pInteracts)|(:pInteracts/^:pInteracts/:pInteracts/^:pInteracts)|(:pInteracts/:pInteracts/:pInteracts))){,3} ?x2 . ?x0 ((^:pReference/^:pInteracts/:pEncodedOn)) ?x3 . ?x3 ((^:pEncodedOn/:pEncodedOn)) ?x2 . } }
