PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:pHasKeyword/^:pInteracts/:pHasKeyword)) ?x1 . ?x1 ((^:pHasKeyword/:pInteracts/:pReference)) ?x2 . ?x2 ((^:pReference/:pInteracts/^:pInteracts/^:pInteracts)|(^:pReference/^:pInteracts/^:pInteracts/^:pInteracts)) ?x3 . } }
