PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pextendedTo/:ppublishedIn/:pheldIn/^:pheldIn)) ?x1 . ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo/:ppublishedIn)|(^:pextendedTo/:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x2 . ?x0 ((^:pextendedTo/:ppublishedIn/:pheldIn/^:pheldIn)|(^:pextendedTo/^:pauthors/:pauthors/:ppublishedIn)) ?x3 . ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo/:ppublishedIn)|(^:pextendedTo/^:pauthors/:pauthors/:ppublishedIn)|(^:pextendedTo/^:pauthors/:pauthors/:ppublishedIn)) ?x4 . } }
