PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x2 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x3 . } }
