PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn)) ?x1 . ?x1 ((:pheldIn/^:pheldIn)|(:pheldIn/^:pheldIn)|(:pheldIn/^:pheldIn)) ?x2 . ?x0 ((^:ppublishedIn/:pextendedTo/^:pextendedTo/^:pauthors)|(^:ppublishedIn/^:pauthors/:pauthors/^:pauthors)|(^:ppublishedIn/^:pauthors/:pauthors/^:pauthors)) ?x3 . ?x2 ((^:ppublishedIn/^:pauthors/:pauthors/^:pauthors)) ?x4 . } }
