PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pextendedTo/^:pauthors)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn)) ?x2 . ?x2 (((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn))){,3} ?x3 . ?x3 (((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn))){,3} ?x4 . } }
