PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:ppublishedIn/^:pauthors/:pauthors/:pextendedTo)|(^:ppublishedIn/:pextendedTo/^:pextendedTo/:pextendedTo)|(^:ppublishedIn/^:pauthors/:pauthors/:pextendedTo)) ?x1 . ?x1 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/^:pauthors/:pauthors/^:pauthors)|(^:pextendedTo/:pextendedTo/^:pextendedTo/^:pauthors)) ?x3 . } }
