PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:pextendedTo/^:pextendedTo/^:pauthors)) ?x2 . ?x2 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x3 . ?x3 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x4 . } }
