PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)|(:pauthors/:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x2 . ?x0 ((^:pheldIn/:pheldIn/^:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn)) ?x3 . ?x2 ((^:pheldIn/^:ppublishedIn/:ppublishedIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn)|(^:pheldIn/:pheldIn/^:pheldIn)) ?x4 . } }
