PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pauthors/^:pauthors/:pauthors)|(:pauthors/^:pauthors/:pauthors)) ?x1 . ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x2 . ?x1 ((:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)|(:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x3 . } }
