PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors/:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn/:pheldIn/^:pheldIn)|(:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x1 . ?x1 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:pheldIn/^:pheldIn/:pheldIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x2 . ?x2 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn/^:pheldIn/^:ppublishedIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn/^:pheldIn/:pheldIn/^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn/^:pheldIn/^:ppublishedIn)) ?x3 . ?x3 (((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn))){,3} ?x4 . }  UNION  {  } }
