PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x1 . ?x1 ((^:pextendedTo/^:pauthors/:pauthors/:pextendedTo)|(^:pextendedTo/:pextendedTo/^:pextendedTo/:pextendedTo)|(^:pextendedTo/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x3 . ?x3 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x4 . } }
