PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)) ?x3 . } }
