PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn)|(^:pheldIn/:pheldIn/^:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn)) ?x1 . ?x0 ((^:pheldIn/^:ppublishedIn)) ?x2 . ?x1 ((^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn/:pextendedTo/^:pextendedTo)) ?x3 . } }
