PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 (((^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn))){,3} ?x1 . ?x1 ((^:ppublishedIn/^:pauthors/:pauthors/:pextendedTo)|(^:ppublishedIn/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/:ppublishedIn/:pheldIn)|(^:pextendedTo/:ppublishedIn/:pheldIn)) ?x3 . } }
