PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pextendedTo/^:pauthors)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x0 ((^:pextendedTo/:ppublishedIn/:pheldIn)) ?x2 . ?x1 ((^:pextendedTo/:ppublishedIn/:pheldIn)|(^:pextendedTo/:ppublishedIn/:pheldIn)|(^:pextendedTo/:ppublishedIn/:pheldIn)) ?x3 . } }
