PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pextendedTo/^:pextendedTo/^:pauthors)|(^:pauthors/:pauthors/^:pauthors)|(^:pauthors/:pauthors/^:pauthors)) ?x1 . ?x0 ((^:pauthors/:pauthors/:ppublishedIn)|(:ppublishedIn/:pheldIn/^:pheldIn)) ?x2 . ?x1 ((:ppublishedIn/:pheldIn/^:pheldIn)|(^:pauthors/:pauthors/:ppublishedIn)) ?x3 . } }
