PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:pextendedTo/^:pextendedTo)|(:pauthors/^:pauthors/:pauthors)) ?x2 . ?x2 (((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn))){,3} ?x3 . ?x3 ((^:pauthors/:pauthors/:ppublishedIn/:pheldIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(:ppublishedIn/:pheldIn)) ?x4 . } }
