PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(:pauthors/:pextendedTo)|(:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x1 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x1 ((:pauthors/:ppublishedIn/^:ppublishedIn)) ?x3 . } }
