PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x1 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x3 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)) ?x4 . } }
