PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x1 . ?x0 ((:pauthors/^:pauthors)|(:pauthors/^:pauthors)|(:pauthors/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x2 ((:pauthors/:ppublishedIn/:pheldIn)) ?x1 . } }
