PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x3 ?x2 WHERE {  {  ?x0 ((^:pauthors/:pauthors)|(^:pauthors/:pauthors)) ?x1 . ?x0 ((:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x1 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x3 . } }
