PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x3 . ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x4 . } }
