PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pheldIn/:pheldIn)) ?x1 . ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x2 . ?x1 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x3 . } }
