PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo/^:pauthors)|(^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/^:ppublishedIn/^:pauthors)|(:pauthors/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo)) ?x3 . ?x2 ((^:pextendedTo/:pextendedTo/^:pextendedTo)) ?x4 . } }
