PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:ppublishedIn/:pheldIn/^:pheldIn)) ?x1 . ?x0 ((:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x2 . ?x0 ((^:pauthors/:pauthors/:ppublishedIn)|(:ppublishedIn/:pheldIn/^:pheldIn)|(:ppublishedIn/:pheldIn/^:pheldIn)) ?x3 . } }
