PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x1 . ?x0 ((^:ppublishedIn/:ppublishedIn/^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x2 . ?x1 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn/^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn/^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x3 . }  UNION  {  } }
