PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x1 . ?x1 ((:pauthors/^:pauthors/:pauthors/:ppublishedIn)|(:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)) ?x2 . ?x2 ((^:ppublishedIn/^:pauthors/:pauthors/:pextendedTo)) ?x3 . } }
