PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn/:pextendedTo/^:pextendedTo)) ?x1 . ?x1 ((^:pauthors/:pauthors/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x2 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x3 . ?x3 ((:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x4 . } }
