PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pauthors/:pextendedTo)|(:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x1 . ?x1 ((^:pextendedTo/:ppublishedIn)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x2 . ?x2 ((:pheldIn/^:pheldIn/^:ppublishedIn/^:pauthors)|(^:ppublishedIn/^:pauthors/:pauthors/^:pauthors)) ?x3 . ?x3 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x4 . } }
