PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pextendedTo/^:pauthors/:pauthors)) ?x1 . ?x1 ((^:pauthors/:pauthors)|(^:pauthors/:pauthors/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo/:pextendedTo)|(^:pextendedTo/:pextendedTo/^:pextendedTo/:pextendedTo)|(^:pextendedTo/^:pauthors/:pauthors/:pextendedTo)) ?x3 . ?x2 ((^:pextendedTo/^:pauthors/:pauthors/:pextendedTo)|(^:pextendedTo/^:pauthors/:pauthors/:pextendedTo)) ?x4 . } }
