PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x3 ?x0 ?x2 WHERE {  {  ?x0 ((:pextendedTo/^:pextendedTo/:ppublishedIn)|(:ppublishedIn/:pheldIn/^:pheldIn)|(:ppublishedIn/:pheldIn/^:pheldIn)) ?x1 . ?x1 ((^:ppublishedIn/:pextendedTo)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/:ppublishedIn/:pheldIn)) ?x3 . } }
