PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 ((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/^:pauthors)|(^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x2 . ?x2 ((^:ppublishedIn/:pextendedTo)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x3 . ?x3 ((^:pextendedTo/^:pauthors)) ?x4 . } }
