PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn)) ?x1 . ?x1 ((:ppublishedIn/^:ppublishedIn/:pextendedTo)|(:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x2 . ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn)) ?x3 . ?x2 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn)) ?x4 . } }
