PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/^:pauthors/:pauthors/^:pauthors)) ?x2 . ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors/:pauthors)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x3 . ?x2 ((^:pheldIn/^:ppublishedIn)) ?x4 . } }
