PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:pextendedTo/:ppublishedIn)) ?x1 . ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x2 . ?x0 ((^:pextendedTo/:ppublishedIn)) ?x3 . ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:pextendedTo/:ppublishedIn)) ?x4 . } }
