PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x1 . ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x2 . ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x3 . } }
