PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x0 ((^:pextendedTo/:ppublishedIn)) ?x2 . ?x1 ((^:pextendedTo/:ppublishedIn)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x3 . } }
