PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x1 . ?x0 ((:pauthors/:ppublishedIn)|(:pauthors/:ppublishedIn)|(:pauthors/:ppublishedIn)) ?x2 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn)) ?x3 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn)) ?x4 . } }
