PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x1 . ?x0 ((^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x2 . ?x1 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x3 . } }
