PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x1 . ?x1 (((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn))){,3} ?x2 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x3 . ?x2 ((:pauthors/:ppublishedIn/^:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn)) ?x4 . } }
