PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x1 . ?x1 ((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(^:ppublishedIn/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/:ppublishedIn/:pheldIn)|(^:pextendedTo/:ppublishedIn/:pheldIn)|(^:pextendedTo/:ppublishedIn/:pheldIn)) ?x3 . } }
