PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x3 ?x2 WHERE {  {  ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x1 . ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn)) ?x3 . ?x0 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x4 . } }
