PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:pextendedTo/^:pextendedTo)|(:pauthors/:pextendedTo/^:pextendedTo)) ?x2 . ?x2 ((:pextendedTo/^:pextendedTo/:pextendedTo)|(:pextendedTo/^:pextendedTo/:pextendedTo)) ?x3 . } }
