PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn)) ?x1 . ?x0 ((^:pheldIn/:pheldIn/^:pheldIn/^:ppublishedIn)) ?x2 . ?x1 ((^:pheldIn/^:ppublishedIn/:pextendedTo/^:pextendedTo)|(^:pheldIn/:pheldIn/^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn/^:pauthors/:pauthors)) ?x3 . } }
