PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/:ppublishedIn)|(:pauthors/:pextendedTo/^:pextendedTo/:ppublishedIn)|(:pauthors/:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x1 . ?x0 ((:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(:pauthors/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x2 . ?x2 ((^:ppublishedIn/:pextendedTo/^:pextendedTo/^:pauthors)|(^:ppublishedIn/:pextendedTo/^:pextendedTo/^:pauthors)) ?x1 . } }
