PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pauthors/^:pauthors/:pauthors/:ppublishedIn)|(:pauthors/^:pauthors/:pauthors/:ppublishedIn)) ?x1 . ?x0 ((:pauthors/^:pauthors/:pauthors/:ppublishedIn)|(:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)) ?x2 . ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/:ppublishedIn)|(:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)) ?x3 . } }
