PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 ?x3 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x1 . ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x2 . ?x0 ((^:pheldIn/:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x3 . ?x0 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x4 . } }
