PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pextendedTo/^:pauthors/:pauthors/^:pauthors)|(^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x1 . ?x1 ((:pauthors/:pextendedTo/^:pextendedTo)|(:pauthors/^:pauthors/:pauthors)) ?x2 . ?x2 ((:ppublishedIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pauthors/:pauthors/:ppublishedIn/:pheldIn)) ?x3 . } }
