PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pextendedTo/:ppublishedIn)) ?x1 . ?x0 ((^:pextendedTo/^:pauthors)|(^:pextendedTo/^:pauthors)|(^:pextendedTo/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x1 ((^:pextendedTo/^:pauthors)|(^:pextendedTo/^:pauthors)|(^:pextendedTo/^:pauthors)) ?x3 . } }
