PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn)|(^:pheldIn/:pheldIn/^:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn)) ?x1 . ?x1 ((^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x2 . ?x2 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x3 . } }
