PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/:pheldIn/^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn/^:pauthors/:pauthors)) ?x1 . ?x1 ((:ppublishedIn/^:ppublishedIn)|(:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x2 . ?x2 (((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn))){,3} ?x3 . ?x3 (((:ppublishedIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn))){,3} ?x4 . } }
