PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x1 . ?x1 ((^:pheldIn/^:ppublishedIn/:pextendedTo)|(^:pheldIn/^:ppublishedIn/:pextendedTo)|(^:pheldIn/^:ppublishedIn/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x3 . ?x3 ((^:pextendedTo/^:pauthors/:pauthors)) ?x4 . } }
