PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn)) ?x1 . ?x1 (((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn))){,3} ?x2 . ?x2 ((:pheldIn/^:pheldIn/:pheldIn)|(^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x3 . } }
