PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:ppublishedIn/:ppublishedIn))){,3} ?x1 . ?x1 ((:pheldIn/^:pheldIn)|(:pheldIn/^:pheldIn)) ?x2 . ?x2 ((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x3 . } }
