PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:ppublishedIn/^:pauthors/:pauthors/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x2 ((:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x3 . } }
