PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/^:pauthors)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/^:pauthors)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)|(:pauthors/^:pauthors/:pauthors/:pextendedTo)) ?x2 . ?x0 ((^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn)) ?x3 . ?x2 ((^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)) ?x4 . } }
