PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)|(^:pheldIn/^:ppublishedIn/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x2 . ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x3 . ?x2 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x4 . } }
