PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/:pheldIn/^:pheldIn)) ?x2 . ?x2 (((^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn)|(^:ppublishedIn/:ppublishedIn/^:ppublishedIn/:ppublishedIn))){,3} ?x3 . } }
