PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)) ?x1 . ?x1 ((^:pheldIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x2 ((:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)) ?x3 . } }
