PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x1 . ?x0 ((:pauthors/^:pauthors/:pauthors/:pextendedTo)|(:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x2 . ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)|(:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x3 . } }
