PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn/:pextendedTo)) ?x1 . ?x1 ((^:pextendedTo/:pextendedTo/^:pextendedTo/:pextendedTo)) ?x2 . ?x2 ((^:pextendedTo/^:pauthors/:pauthors/:ppublishedIn)|(^:pextendedTo/:pextendedTo/^:pextendedTo/:ppublishedIn)|(^:pextendedTo/:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x3 . } }
