PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:ppublishedIn/:ppublishedIn/:pheldIn/^:pheldIn)|(:pheldIn/^:pheldIn)|(:pheldIn/^:pheldIn/^:ppublishedIn/:ppublishedIn)) ?x1 . ?x1 ((^:ppublishedIn/:pextendedTo/^:pextendedTo/:ppublishedIn)) ?x2 . ?x2 ((:pheldIn/^:pheldIn/:pheldIn)|(^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x3 . } }
