PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:pheldIn/^:ppublishedIn)|(^:pheldIn/^:ppublishedIn/:pextendedTo/^:pextendedTo)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/^:ppublishedIn)) ?x1 . ?x1 ((:pextendedTo/^:pextendedTo/:ppublishedIn/:pheldIn)|(:ppublishedIn/:pheldIn)) ?x2 . ?x0 ((^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x3 . ?x2 ((^:pheldIn/:pheldIn/^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn)|(^:pheldIn/:pheldIn)) ?x4 . } }
