PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((:pauthors/:pextendedTo/^:pextendedTo/^:pauthors)|(:pauthors/^:pauthors/:pauthors/^:pauthors)|(:pauthors/:pextendedTo/^:pextendedTo/^:pauthors)) ?x1 . ?x1 ((:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)|(:pauthors/:ppublishedIn/:pheldIn)) ?x2 . ?x0 ((:pauthors/:pextendedTo)|(:pauthors/:pextendedTo)) ?x3 . ?x2 ((:pauthors/:ppublishedIn/^:ppublishedIn/:pextendedTo)|(:pauthors/:pextendedTo)) ?x4 . } }
