PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:ppublishedIn/:pextendedTo/^:pextendedTo)|(^:ppublishedIn/^:pauthors/:pauthors)) ?x1 . ?x0 ((^:ppublishedIn/^:pauthors/:pauthors)|(:pheldIn/^:pheldIn/^:ppublishedIn)|(^:ppublishedIn/^:pauthors/:pauthors)) ?x2 . ?x0 ((^:ppublishedIn/^:pauthors/:pauthors)) ?x3 . ?x0 ((^:ppublishedIn/^:pauthors/:pauthors)|(:pheldIn/^:pheldIn/^:ppublishedIn)) ?x4 . } }
