PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo/^:pauthors)|(^:pextendedTo/^:pauthors/:pauthors/^:pauthors)|(^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x1 . ?x0 ((^:pextendedTo/:pextendedTo/^:pextendedTo/^:pauthors)|(^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x2 . ?x1 ((^:pextendedTo/^:pauthors/:pauthors/^:pauthors)) ?x3 . } }
