PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:ppublishedIn/:ppublishedIn/:pheldIn)|(^:ppublishedIn/:ppublishedIn/:pheldIn)) ?x1 . ?x1 ((^:pheldIn/^:ppublishedIn/^:pauthors)) ?x2 . ?x2 ((:pauthors/:pextendedTo/^:pextendedTo/:pextendedTo)|(:pauthors/^:pauthors/:pauthors/:pextendedTo)) ?x3 . } }
