PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p53/:p0/^:p9/^:p61/^:p68/:p69/:p63)) ?x1 . ?x0 ((:p81/^:p81/^:p61/:p63)) ?x2 . ?x0 ((^:p53/:p65/:p64/:p55/^:p64/:p63)|(^:p53/:p67/:p64/:p55/^:p64/:p63)|(^:p66/:p65/:p63)) ?x3 . }  UNION  {  } }
