PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x3 ?x0 ?x1 WHERE {  {  ?x0 ((:p80/:p57/^:p57/^:p72)|(:p80/:p57/^:p57/^:p71)) ?x1 . ?x0 ((:p80/:p57/^:p57/^:p72)|(:p80/:p59/^:p59/^:p72)|(:p80/:p57/^:p57/^:p71)) ?x2 . ?x0 ((:p80/:p57/^:p57/^:p71)|(:p80/:p57/^:p57/^:p72)) ?x3 . } }
