PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:p69/:p70/^:p58)|(^:p65/:p81/^:p81/:p68))){,3} ?x1 . ?x1 ((^:p80/^:p81)|(^:p68/:p69/^:p80/^:p81)|(^:p80/^:p81)) ?x2 . ?x2 (((:p81/^:p81))){,3} ?x3 . } }
