PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p79/:p68/:p59/^:p75)|(^:p78/:p60/:p59/^:p75)|(^:p78/^:p60/:p59/^:p74)) ?x1 . ?x1 (((:p74/:p60/:p60/^:p74)|(:p75/^:p71/:p72/^:p75)|(:p75/:p54/^:p54/^:p74))){,3} ?x2 . ?x0 ((^:p78/^:p71/^:p79)|(^:p78/^:p80/^:p81/^:p79)|(:p79/:p72/:p78)) ?x3 . ?x2 ((:p79/^:p79)) ?x4 . } }
