PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:p72/:p57/:p72/:p57)|(:p81/:p80/:p57)) ?x1 . ?x1 (((^:p76/:p76/^:p79/:p79)|(^:p76/:p76/^:p79/:p79)|(:p54/^:p54/:p81/^:p81))){,3} ?x2 . ?x2 (((:p81/^:p81/^:p79/:p79))){,3} ?x3 . } }
