PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:p71/:p71)|(^:p60/:p60))){,3} ?x1 . ?x1 (((:p60/:p60)|(^:p69/:p54/^:p58))){,3} ?x2 . ?x0 (((^:p68/:p68/:p78/^:p78))){,3} ?x3 . ?x2 (((:p78/^:p78)|(^:p74/:p74))){,3} ?x4 . } }
