PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((^:p59/:p57)|(^:p65/:p9/^:p2)) ?x1 . ?x1 (((:p54/^:p54))){,3} ?x2 . ?x0 ((:p57/:p8/^:p31)|(^:p80/^:p81/:p11/^:p33)|(^:p71/:p0/^:p26)) ?x3 . ?x2 ((:p45/^:p39/^:p73)) ?x4 . } }
