PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p18/:p56)|(^:p45/:p57/:p56)) ?x1 . ?x1 ((^:p56/^:p54/:p66)|(^:p56/:p69/:p61)) ?x2 . ?x2 ((^:p66/:p81/^:p81/^:p76)|(^:p61/:p57/^:p76)) ?x3 . ?x3 (((:p76/^:p76)|(:p76/^:p76)|(:p76/^:p79/:p79/^:p76))){,3} ?x4 . } }
