PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((^:p52/^:p79)|(^:p52/^:p79)) ?x1 . ?x0 ((^:p52/^:p79)|(^:p52/:p25/^:p35)) ?x2 . ?x0 ((^:p52/:p72/:p78)|(^:p52/:p2/^:p11/^:p79)|(^:p52/^:p79)) ?x3 . } }
