PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:p54/^:p54/:p60)) ?x1 . ?x1 (((^:p68/^:p79/:p79/:p71)|(:p60/^:p60)|(:p60/^:p60/^:p60))){,3} ?x2 . ?x0 ((^:p79/:p79/^:p76/:p76)|(:p54/^:p54)) ?x3 . ?x2 ((^:p76/:p76/:p54/^:p54)|(^:p76/:p76/^:p76/:p76)|(:p54/^:p70/:p70/^:p54)) ?x4 . } }
