PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p76/:p68/^:p72/^:p76)|(:p76/^:p76))){,3} ?x1 . ?x0 (((:p76/^:p76)|(:p76/:p54/^:p54/^:p76))){,3} ?x2 . ?x0 (((:p76/^:p76)|(:p76/:p72/^:p72/^:p76)|(:p76/^:p76/:p76/^:p76))){,3} ?x3 . ?x0 (((:p76/^:p76)|(:p76/:p72/^:p69/^:p76)|(:p76/^:p76))){,3} ?x4 . } }
