PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:p79/:p79/^:p79/:p79)|(:p65/^:p80/^:p81)|(:p65/^:p60/^:p65))){,3} ?x1 . ?x0 (((:p54/^:p54/^:p65)|(:p65/^:p80/^:p81))){,3} ?x2 . ?x0 (((:p65/:p58/^:p54))){,3} ?x3 . } }
