PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:p81/:p54/^:p58/^:p80)|(^:p81/:p81))){,3} ?x1 . ?x1 ((^:p81/:p72/:p60/:p57)|(^:p81/:p54/^:p58/:p57)) ?x2 . ?x2 ((^:p57/:p46/^:p2)|(:p15/^:p5)|(:p53/^:p53)) ?x3 . ?x3 (((:p71/^:p72/:p71/^:p71)|(^:p76/:p76))){,3} ?x4 . } }
