PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((^:p54/:p54))){,3} ?x1 . ?x1 ((^:p54/:p9/^:p29)|(^:p54/^:p57/:p30/^:p27)) ?x2 . ?x2 (((:p75/:p60/^:p74)|(:p75/^:p60/^:p75)|(:p75/^:p74/:p75/^:p74))){,3} ?x3 . } }
