PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p6/:p67/:p60/:p63)) ?x1 . ?x0 ((^:p6/:p2/^:p47/:p63)|(^:p6/:p68/:p63)|(^:p20/:p72/:p63)) ?x2 . ?x0 ((^:p6/:p2/^:p47/:p63)|(^:p20/:p72/^:p60/:p63)) ?x3 . } }
