PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:p52/^:p52/:p51)) ?x1 . ?x0 ((:p52/^:p52/:p51)|(:p6/^:p6/:p53/:p51)|(:p52/^:p52/:p51)) ?x2 . ?x0 ((:p3/^:p5/:p53/:p51)) ?x3 . } }
