PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p62/^:p60/:p63)|(^:p62/^:p60/:p63)|(^:p62/:p29/^:p29/:p63)) ?x1 . ?x0 ((^:p62/^:p60/:p63)|(^:p62/:p48/^:p48/:p63)|(^:p62/:p57/^:p57/:p63)) ?x2 . ?x0 ((^:p62/:p63)|(^:p62/^:p72/:p72/:p63)) ?x3 . } }
