PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p72/:p57)|(:p71/^:p68/:p69/:p57)) ?x1 . ?x1 (((:p54/^:p70/:p81/^:p81)|(^:p79/:p79))){,3} ?x2 . ?x0 ((:p72/:p48)|(:p2/^:p10/^:p76/:p36)|(:p2/^:p3/:p6)) ?x3 . ?x2 ((:p20/^:p6/:p6)|(^:p57/:p48)|(:p19/^:p3/:p6)) ?x4 . } }
