PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p70/:p53/:p51)|(^:p54/:p53/:p51)) ?x1 . ?x0 ((^:p54/:p53/:p51)) ?x2 . ?x0 ((^:p54/^:p71/:p53/:p51)|(^:p54/:p53/:p51)|(:p42/^:p1/:p53/:p51)) ?x3 . } }
