PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:p60/^:p65)|(:p58/^:p54)) ?x1 . ?x1 (((:p65/^:p72/:p81/^:p81))){,3} ?x2 . ?x0 ((^:p75/:p74/:p78/^:p78)|(^:p68/:p54/^:p54/:p71)) ?x3 . ?x2 ((^:p60/^:p60)|(^:p72/:p71)|(^:p74/:p75)) ?x4 . } }
