PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((:p80/^:p60/^:p72/:p81)|(^:p81/:p81)|(^:p81/:p54/^:p54/:p81))){,3} ?x1 . ?x0 (((^:p81/:p54/^:p54/:p81)|(:p80/^:p69/:p81)|(^:p81/:p54/^:p54/:p81))){,3} ?x2 . ?x0 (((^:p81/:p65/^:p80)|(:p80/:p60/^:p80))){,3} ?x3 . ?x0 (((:p80/^:p71/:p81)|(^:p81/:p81/^:p81/:p81))){,3} ?x4 . } }
