PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((:p81/^:p81)|(:p81/^:p81/^:p79/:p79))){,3} ?x1 . ?x1 ((:p54/^:p58/^:p72)|(^:p79/:p79)|(:p81/^:p81/^:p79/:p79)) ?x2 . ?x2 (((:p81/:p80/^:p72))){,3} ?x3 . } }
