PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((^:p78/:p78/:p79/^:p79))){,3} ?x1 . ?x0 (((:p79/^:p79/:p79/^:p79)|(^:p78/^:p65/^:p79))){,3} ?x2 . ?x0 (((^:p78/^:p72/^:p79)|(^:p78/:p60/^:p71/^:p79))){,3} ?x3 . } }
