PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 ((^:p53/^:p57/^:p80/^:p81)) ?x1 . ?x1 (((:p65/^:p65)|(:p65/:p54/^:p54)|(:p65/^:p60/^:p65))){,3} ?x2 . ?x2 ((:p65/:p59/^:p67/^:p76)|(:p65/:p59/^:p67/^:p76)|(:p65/:p59/^:p67/^:p76)) ?x3 . ?x3 (((:p76/:p68/^:p72/^:p76))){,3} ?x4 . } }
