PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p58/:p59/^:p67)|(^:p58/:p57/:p65/^:p67)) ?x1 . ?x1 (((:p81/^:p81/^:p79/:p79))){,3} ?x2 . ?x2 (((:p54/^:p70/^:p76/:p76)|(:p81/^:p81)|(:p81/:p80/:p58/^:p54))){,3} ?x3 . } }
