PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((:p76/:p69/^:p75/:p73)) ?x1 . ?x1 (((:p76/:p72/^:p72/^:p76)|(:p76/^:p76)|(:p76/:p54/^:p54/^:p76))){,3} ?x2 . ?x0 ((:p76/:p71/^:p65/^:p76)) ?x3 . ?x2 ((:p76/^:p76)|(:p76/^:p76)) ?x4 . } }
