PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:p66/:p9/^:p5/:p81)|(^:p66/:p9/^:p50)|(^:p61/^:p68/:p81)) ?x1 . ?x1 ((:p3/^:p33)|(:p43/^:p7/:p10/^:p26)) ?x2 . ?x2 ((:p75/:p59/^:p68/^:p76)) ?x3 . } }
