PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p52/:p51/^:p51/:p51)|(^:p52/:p53/:p51)) ?x1 . ?x0 ((^:p52/^:p53/:p53/:p51)|(^:p52/:p53/:p51)|(^:p52/:p53/:p51)) ?x2 . ?x0 ((^:p52/:p53/:p51)|(^:p52/:p53/:p51)) ?x3 . } }
