PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p63/:p57/:p52)) ?x1 . ?x1 ((^:p52/:p52/^:p52)) ?x2 . ?x0 ((^:p63/^:p72/:p53)|(^:p63/^:p71/:p53)|(^:p63/:p57/:p53)) ?x3 . ?x2 ((^:p63/:p57/:p53)|(^:p63/^:p71/:p53)|(^:p63/:p57/:p53)) ?x4 . } }
