PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:p53/:p81/:p50/^:p47)|(^:p53/^:p57)|(^:p53/^:p57)) ?x1 . ?x1 ((:p59/^:p67)|(:p59/^:p67)|(:p59/^:p67)) ?x2 . ?x2 ((:p67/^:p59/^:p71)) ?x3 . } }
