PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p51/^:p53/:p1)|(^:p51/^:p53/:p18)) ?x1 . ?x0 ((^:p51/^:p53/:p1)|(^:p51/^:p53/:p4)|(^:p51/:p52/^:p52/:p4)) ?x2 . ?x1 ((^:p51/^:p53/:p4)|(^:p51/^:p53/:p1)|(^:p51/^:p53/:p1)) ?x3 . } }
