PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 ?x3 WHERE {  {  ?x0 (((^:p76/:p76))){,3} ?x1 . ?x1 (((^:p76/:p76/:p54/^:p54))){,3} ?x2 . ?x0 (((:p54/^:p54/^:p57))){,3} ?x3 . ?x2 (((^:p57/^:p68/:p68))){,3} ?x4 . } }
