PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p74/^:p60/:p60/^:p75))){,3} ?x1 . ?x1 (((:p75/^:p80/:p80/^:p75)|(:p74/^:p60/^:p75)|(:p75/^:p60/^:p75))){,3} ?x2 . ?x2 (((:p74/^:p80/:p80/^:p74)|(:p75/^:p72/:p71/^:p74)|(:p74/^:p60/^:p74))){,3} ?x3 . } }
