PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:p76/:p81)|(:p76/:p81)) ?x1 . ?x0 ((:p76/:p54/^:p54/:p81)|(:p76/:p72/^:p80)|(:p76/:p72/^:p80)) ?x2 . ?x0 ((:p76/:p69/^:p60/^:p80)) ?x3 . } }
