PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((:p81/^:p81/^:p79)|(:p65/:p78)) ?x1 . ?x1 ((^:p78/:p57/^:p57/^:p71)|(^:p78/:p59/^:p59/^:p71)|(^:p78/:p59/^:p59/^:p72)) ?x2 . ?x2 (((:p72/^:p60/^:p60/^:p72)|(^:p79/:p79))){,3} ?x3 . } }
