PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p63/^:p68/:p52)|(^:p63/:p57/:p52)|(^:p63/:p57/:p52)) ?x1 . ?x0 ((^:p63/:p63)|(^:p63/:p57/:p67/:p63)) ?x2 . ?x1 ((^:p63/^:p69/:p68/:p63)|(^:p63/^:p75/:p74/:p63)) ?x3 . } }
