PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p8/^:p1/^:p57)|(:p1/^:p1/:p0/^:p47)|(:p9/^:p46)) ?x1 . ?x1 (((:p60/:p60)|(^:p71/:p72))){,3} ?x2 . ?x2 ((:p60/:p57/:p81/^:p81)) ?x3 . } }
