PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 (((^:p58/:p58/^:p54/:p54)|(^:p54/:p54))){,3} ?x1 . ?x0 (((^:p54/:p54/^:p54/:p54))){,3} ?x2 . ?x0 (((^:p70/:p54))){,3} ?x3 . ?x0 (((^:p54/:p68/:p58))){,3} ?x4 . } }
