PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:p4/^:p27/:p28/^:p11)|(:p0/^:p46/:p57)|(:p0/^:p19/:p0/^:p11)) ?x1 . ?x0 ((:p2/^:p49/^:p69)|(:p5/^:p3)|(:p6/^:p48/:p57)) ?x2 . ?x0 ((:p5/^:p15)|(:p2/^:p49/^:p68)) ?x3 . ?x0 ((:p3/^:p5/:p2/^:p11)|(:p3/^:p50/:p81/^:p81)) ?x4 . } }
