PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 ?x1 ?x2 WHERE {  {  ?x0 ((^:p56/:p50/^:p9/:p52)) ?x1 . ?x1 ((^:p52/:p50/^:p0/:p52)|(^:p52/:p52)) ?x2 . ?x0 ((^:p56/:p15/^:p0/:p56)|(^:p56/:p70/:p56)) ?x3 . ?x2 ((^:p56/^:p70/:p56)|(^:p56/:p0/^:p50/:p56)|(^:p56/:p1/^:p4/:p56)) ?x4 . } }
