PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((^:p14/:p54/^:p70/:p52)|(^:p1/:p50/^:p0/:p52)) ?x1 . ?x0 ((^:p4/:p52)|(^:p39/:p76/:p52)) ?x2 . ?x0 ((^:p16/:p5/^:p0/:p52)|(^:p27/:p27/^:p4/:p52)|(^:p30/:p57/:p52)) ?x3 . } }
