PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 (((:p72/:p60/^:p60/^:p71)|(:p54/^:p54/:p71/^:p71)|(:p71/^:p71))){,3} ?x1 . ?x0 (((:p54/^:p54/:p54/^:p54)|(^:p76/:p76)|(:p72/^:p72))){,3} ?x2 . ?x0 (((:p72/^:p72)|(:p54/^:p58/:p58/^:p54))){,3} ?x3 . } }
