PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:p60/^:p60/^:p60)|(^:p68/:p81/:p80))){,3} ?x1 . ?x1 ((:p60/:p57)|(:p59/^:p71/:p54/^:p54)|(:p59/^:p72/:p72/:p57)) ?x2 . ?x2 (((^:p76/:p76)|(^:p76/:p76)|(:p54/^:p54/:p54/^:p54))){,3} ?x3 . } }
