PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p57/:p63)|(:p67/:p63)|(:p67/:p60/:p63)) ?x1 . ?x1 ((^:p63/:p78)|(^:p63/:p78)|(^:p63/^:p71/^:p79)) ?x2 . ?x2 (((:p79/:p65/^:p60/:p78)|(^:p78/:p78))){,3} ?x3 . } }
