PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((^:p79/:p79/:p81/^:p81)|(^:p79/:p79)|(:p81/^:p81))){,3} ?x1 . ?x1 ((^:p79/:p79/^:p79/:p79)|(:p81/^:p81)) ?x2 . ?x2 ((^:p57/:p78)) ?x3 . } }
