PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((^:p81/:p67/^:p59/:p54)|(:p80/:p57/^:p57/:p54)) ?x1 . ?x1 ((^:p54/:p59/^:p59/:p78)|(^:p54/:p67/^:p59/:p78)|(^:p54/:p57/^:p57/:p78)) ?x2 . ?x2 (((:p79/^:p79)|(^:p78/^:p71/:p72/:p78)|(:p79/^:p79))){,3} ?x3 . } }
