PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p15/:p1/^:p42)) ?x1 . ?x0 ((^:p5/:p54)|(^:p0/:p0/^:p41)) ?x2 . ?x0 ((^:p5/:p3/^:p50/:p54)|(^:p47/:p57/:p54)) ?x3 . ?x0 ((^:p50/:p0/^:p2/:p54)) ?x4 . } }
