PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p51/^:p53/:p56)|(^:p51/^:p53/:p54/:p56)) ?x1 . ?x0 ((^:p51/^:p53/:p72/:p63)|(^:p51/^:p53/:p69/:p63)|(^:p51/^:p53/:p67/:p63)) ?x2 . ?x1 ((^:p51/^:p53/:p65/:p63)) ?x3 . } }
