PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:p81/^:p81)|(^:p79/:p79)|(:p54/^:p54/:p54/^:p54)) ?x1 . ?x0 ((:p81/:p80/^:p71)) ?x2 . ?x0 ((:p81/:p80/^:p71)|(^:p79/^:p78/^:p72)|(^:p79/:p79)) ?x3 . } }
