PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:p66/^:p76)) ?x1 . ?x1 (((:p76/^:p76/:p76/^:p76)|(:p76/^:p76)|(:p76/^:p76))){,3} ?x2 . ?x2 ((:p76/:p67/^:p59/^:p68)|(:p76/:p67/^:p59/^:p68)) ?x3 . ?x3 ((:p54/:p56)|(:p69/:p46/^:p11/:p56)|(:p52/^:p52/:p54/:p56)) ?x4 . } }
