PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p52/^:p57/:p62)|(^:p52/:p69/:p62)) ?x1 . ?x1 ((^:p62/:p57)|(^:p62/:p57)|(^:p62/:p47/^:p11)) ?x2 . ?x2 ((:p70/:p42)) ?x3 . } }
