PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p54/^:p54/:p58/^:p54)|(:p54/^:p54/:p81/^:p81))){,3} ?x1 . ?x1 (((^:p76/:p76/^:p76/:p76)|(:p81/:p80/:p58/^:p54))){,3} ?x2 . ?x2 ((^:p79/^:p78/:p57)) ?x3 . } }
