PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:p72/^:p80)|(:p71/^:p60/^:p68/:p81)) ?x1 . ?x1 (((^:p81/:p72/^:p60/^:p80)|(^:p81/:p81))){,3} ?x2 . ?x0 ((:p72/:p51)) ?x3 . ?x2 ((:p72/:p51)|(:p23/^:p45/:p51)) ?x4 . } }
