PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p48/^:p75/:p30)|(^:p6/:p21/^:p35/:p35)|(^:p20/^:p79/:p35)) ?x1 . ?x0 ((^:p6/:p0/^:p5/:p8)|(^:p20/^:p57/:p30)|(^:p6/:p4)) ?x2 . ?x0 ((^:p6/^:p57/:p45)|(^:p40/:p35/^:p4/:p4)) ?x3 . } }
