PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:p79/^:p79)|(:p79/^:p79))){,3} ?x1 . ?x0 (((:p35/^:p1/:p53/^:p53))){,3} ?x2 . ?x1 (((:p35/^:p23/:p23/^:p18)|(:p35/^:p17/:p3/^:p50))){,3} ?x3 . } }
