PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p1/^:p4)|(:p4/^:p7)|(:p3/^:p46/^:p65)) ?x1 . ?x0 ((:p54/^:p54/:p70/^:p54)|(^:p79/:p79/^:p76/:p76)|(:p54/^:p58/^:p80/^:p81)) ?x2 . ?x1 ((^:p79/^:p78/:p58/^:p54)|(:p54/^:p54/^:p76/:p76)|(:p81/^:p81/^:p79/:p79)) ?x3 . } }
