PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p78/:p57)|(^:p78/^:p75/:p73/:p76)|(:p79/:p67/:p59/:p57)) ?x1 . ?x1 ((^:p76/:p76/:p72/:p78)) ?x2 . ?x2 (((:p79/:p71/:p78)|(:p79/^:p79/^:p78/:p78)|(:p79/:p81/^:p81/^:p79))){,3} ?x3 . } }
