PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p51/^:p53/^:p57/:p48)|(^:p51/^:p53/:p6)) ?x1 . ?x0 ((^:p51/^:p53/:p1)|(^:p51/^:p53/:p17)) ?x2 . ?x1 ((^:p51/^:p53/:p4)|(^:p51/^:p53/:p16)|(^:p51/^:p53/:p1)) ?x3 . } }
