PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((^:p76/:p76)|(:p69/^:p68)|(:p69/:p60/^:p60/^:p69))){,3} ?x1 . ?x1 (((:p68/:p60/^:p68))){,3} ?x2 . ?x2 ((:p68/^:p59/^:p65/^:p76)|(^:p57/^:p72/^:p76)|(^:p57/:p58/^:p54/^:p76)) ?x3 . } }
