PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p66/:p9/^:p19/:p5)|(^:p66/:p8/^:p30/:p26)|(^:p61/^:p69/:p50)) ?x1 . ?x0 ((^:p61/^:p68/:p3)|(^:p66/:p50)|(^:p66/:p81/^:p81/:p11)) ?x2 . ?x0 ((^:p61/:p30/^:p31/:p0)|(^:p61/^:p59/:p47)|(^:p66/:p5/^:p0/:p3)) ?x3 . } }
