PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((:p75/^:p71/^:p79)|(:p75/:p78)|(:p75/^:p71/:p72/:p78)) ?x1 . ?x1 (((:p79/^:p79)|(:p79/^:p79)|(^:p78/^:p80/:p80/:p78))){,3} ?x2 . ?x2 (((:p79/^:p79)|(^:p78/^:p71/^:p79))){,3} ?x3 . } }
