PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 ?x1 WHERE {  {  ?x0 ((^:p60/:p57/:p8/^:p4)|(^:p72/:p5/^:p50)|(:p49/^:p5)) ?x1 . ?x1 (((^:p76/:p76/:p69/^:p71))){,3} ?x2 . ?x2 ((^:p79/^:p78/^:p71)) ?x3 . ?x3 ((^:p57/:p60/^:p72)|(^:p57/^:p72)|(^:p57/^:p72)) ?x4 . } }
