PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p23/:p5/^:p10/^:p79)) ?x1 . ?x1 (((^:p78/:p60/:p78)|(^:p78/^:p60/:p78))){,3} ?x2 . ?x2 (((^:p78/^:p60/^:p68/^:p79)|(:p79/:p71/^:p72/^:p79)|(:p79/^:p79))){,3} ?x3 . ?x3 ((:p79/:p6)) ?x4 . } }
