PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p63/:p60/:p62)|(^:p63/:p62)) ?x1 . ?x1 ((^:p62/:p78/^:p78)|(^:p62/^:p60)|(^:p62/^:p59)) ?x2 . ?x0 ((^:p63/:p57/:p54)|(^:p63/^:p72/:p4/^:p42)) ?x3 . ?x2 ((^:p63/^:p68/:p70)) ?x4 . } }
