PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p56/:p0)|(^:p56/:p5)) ?x1 . ?x0 ((^:p56/:p0/^:p5/:p0)) ?x2 . ?x0 ((^:p56/:p70/:p41)|(^:p56/^:p54/:p2)) ?x3 . ?x0 ((^:p56/:p2/^:p46/:p47)|(^:p56/:p71/^:p67/:p50)) ?x4 . } }
