PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p5/:p4/^:p45/:p64)|(^:p3/^:p57/^:p59/:p64)|(^:p47/^:p72/:p71/:p64)) ?x1 . ?x0 ((^:p47/:p64)|(^:p9/^:p76/:p72)) ?x2 . ?x0 ((^:p49/:p64)|(^:p46/^:p60/:p64)) ?x3 . } }
