PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:p54/^:p54/^:p76/:p76))){,3} ?x1 . ?x0 (((:p81/^:p81/:p81/^:p81)|(:p54/^:p54)|(:p54/^:p70/:p81/^:p81))){,3} ?x2 . ?x1 (((:p54/^:p54/:p58/^:p54))){,3} ?x3 . } }
