PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p79/:p79)|(:p69/:p60/^:p65)|(:p68/:p54/^:p54)) ?x1 . ?x0 ((:p69/:p57)|(:p69/:p57)|(:p69/:p60/:p60/:p57)) ?x2 . ?x1 ((:p69/:p57/:p65/^:p71)) ?x3 . } }
