PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x1 ?x0 WHERE {  {  ?x0 ((^:p51/:p61)) ?x1 . ?x0 ((^:p51/:p57/:p1)|(^:p51/:p45/^:p4/:p1)) ?x2 . ?x1 ((^:p51/:p30)|(^:p51/^:p74/:p32)|(^:p51/:p30)) ?x3 . } }
