PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 ((:p42/^:p30/:p0/^:p2)|(^:p54/:p3/^:p2)|(:p41/^:p2)) ?x1 . ?x0 ((^:p54/^:p76/:p39/^:p1)|(^:p58/^:p69/:p14/^:p4)|(:p42/^:p1)) ?x2 . ?x0 ((:p41/^:p19/:p19/^:p50)|(^:p54/:p7/^:p4)|(:p41/^:p0)) ?x3 . ?x0 ((:p41/^:p5)) ?x4 . } }
