PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p60/^:p68/^:p79)|(^:p72/:p81/^:p81/^:p79)) ?x1 . ?x0 ((^:p72/^:p79)) ?x2 . ?x0 ((^:p60/:p60/^:p72/^:p79)) ?x3 . ?x0 ((^:p71/:p71/^:p69/^:p79)) ?x4 . } }
