PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x1 ?x0 WHERE {  {  ?x0 (((:p58/^:p58)|(^:p69/:p54/^:p58))){,3} ?x1 . ?x1 (((^:p71/:p81/^:p81/:p69))){,3} ?x2 . ?x2 (((:p54/^:p54/^:p79/^:p78))){,3} ?x3 . } }
