PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p3/:p1/^:p1/:p3)|(^:p3/:p1/^:p1/:p3)) ?x1 . ?x0 ((^:p3/:p1/^:p1/:p3)|(^:p3/:p3)|(^:p3/:p1/^:p1/:p3)) ?x2 . ?x1 ((^:p3/:p1/^:p1/:p3)|(^:p3/:p1/^:p1/:p3)|(^:p3/:p1/^:p1/:p3)) ?x3 . } }
