PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 ?x3 WHERE {  {  ?x0 ((^:p3/:p3/^:p3/:p3)|(:p6/^:p6/:p6/^:p6)) ?x1 . ?x1 ((^:p3/:p2)) ?x2 . ?x0 ((^:p3/:p2)|(^:p3/:p0/:p0/:p2)) ?x3 . ?x2 ((^:p3/:p2)|(^:p3/:p0/:p2)|(^:p3/^:p0/:p2)) ?x4 . } }
