PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x2 ?x0 ?x1 WHERE {  {  ?x0 ((^:p6/^:p3/:p3)|(^:p6/:p5/^:p5)|(^:p6/^:p3/^:p0/:p3)) ?x1 . ?x1 ((^:p3/:p4/^:p4/:p0)) ?x2 . ?x2 (((:p0/:p0/^:p0/^:p0)|(^:p0/:p0)|(:p0/:p0/:p0/:p0))){,3} ?x3 . ?x3 (((:p0/:p0)|(:p0/:p0/:p0)|(:p0/^:p0/:p0))){,3} ?x4 . } }
