PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p2/:p3/:p5)|(^:p2/:p3/:p5)|(^:p2/:p3/:p5)) ?x1 . ?x0 ((^:p2/:p0/:p0/:p3)) ?x2 . ?x1 ((^:p2/:p3/:p5/^:p5)|(^:p2/:p3)|(^:p2/:p3/:p6/^:p6)) ?x3 . } }
