PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p6/^:p3/:p0/:p3)|(^:p6/:p5/^:p5)) ?x1 . ?x1 ((^:p3/:p4)|(^:p3/:p0/:p4)|(^:p3/^:p0/:p4)) ?x2 . ?x0 ((^:p6/^:p3/^:p0/:p4)|(^:p6/^:p3/:p4)|(^:p6/^:p3/^:p0/:p4)) ?x3 . ?x2 ((^:p6/^:p3/^:p0/:p4)) ?x4 . } }
