PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p3/:p3/^:p3/:p3)|(:p6/^:p6/^:p3/:p3)|(:p6/^:p6)) ?x1 . ?x0 ((^:p3/:p0/:p4)|(^:p3/:p4)) ?x2 . ?x2 ((^:p4/:p3/:p5)|(^:p4/^:p0/:p3/:p5)|(^:p4/:p3/:p5)) ?x1 . } }
