PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 (((:p0/:p0/^:p0/^:p0))){,3} ?x1 . ?x1 (((^:p0/:p0/^:p0)|(^:p0/^:p0/:p0)|(:p0/^:p0))){,3} ?x2 . ?x2 ((:p2/^:p2/:p3)|(:p1/^:p1/:p3)) ?x3 . } }
