PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x1 ?x2 ?x0 WHERE {  {  ?x0 ((:p5/^:p5/:p5)) ?x1 . ?x0 ((:p6/^:p6/:p5)|(:p6/^:p6/:p5)|(:p6/^:p6/:p5)) ?x2 . ?x0 ((:p6/^:p6/:p5)|(:p5/^:p5/:p5)) ?x3 . ?x0 ((:p6/^:p6/:p5)|(:p6/^:p6/:p5)|(:p5/^:p5/:p5)) ?x4 . } }
