PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p4/:p3)|(^:p4/:p2/^:p2/:p3)|(^:p4/:p2/^:p2/:p3)) ?x1 . ?x1 ((:p6/^:p6/^:p3)|(:p5/^:p5/^:p3)|(:p6/^:p6/^:p3)) ?x2 . ?x2 (((:p0/:p0/:p0)|(:p0/:p0/:p0/^:p0)|(^:p0/:p0/^:p0))){,3} ?x3 . } }
