PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p16/^:p16)|(:p16/^:p16/:p16/^:p16)|(:p16/^:p26/:p26/^:p16))){,3} ?x1 . ?x1 (((:p16/^:p22/:p22/^:p16)|(:p16/^:p25/:p23/^:p16))){,3} ?x2 . ?x2 ((^:p4/:p19/^:p16)|(^:p4/:p20/^:p16)|(^:p4/:p16/^:p16)) ?x3 . ?x3 (((:p16/^:p23/:p23/^:p16)|(:p16/^:p22/:p21/^:p16)|(:p16/^:p16))){,3} ?x4 . } }
