PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x4 WHERE {  {  ?x0 (((:p15/^:p15)|(:p17/^:p22/:p16/^:p17))){,3} ?x1 . ?x1 (((:p22/^:p17)|(:p16/^:p24/:p24/^:p21))){,3} ?x2 . ?x2 (((:p22/^:p17/:p22/^:p17)|(:p16/^:p25/:p23/^:p16))){,3} ?x3 . ?x3 ((:p4/^:p4/:p21)|(:p0/^:p0/:p20)|(^:p0/:p20)) ?x4 . }  UNION  {  }  UNION  {  } }
