PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((^:p24/:p24))){,3} ?x1 . ?x1 (((^:p24/:p23/^:p23/:p24)|(^:p24/:p23/^:p23/:p24)|(^:p24/:p23/^:p23/:p24))){,3} ?x2 . ?x2 (((^:p24/:p24/^:p24/:p24))){,3} ?x3 . ?x3 ((^:p24/:p14/^:p8/:p15)|(^:p24/:p13/^:p8/:p15)|(^:p24/:p14/^:p8/:p18)) ?x4 . }  UNION  {  } }
