PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p24/:p23/^:p17/:p0)|(^:p24/:p23/^:p22/^:p8)|(^:p24/:p23/^:p22/:p0)) ?x1 . ?x0 ((^:p24/:p23/^:p23/:p24)) ?x2 . ?x1 ((^:p24/:p24)) ?x3 . } }
