PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 (((:p22/^:p17)|(:p21/^:p22/:p22/^:p17)|(:p16/^:p22))){,3} ?x1 . ?x1 ((:p20/^:p16/:p4)|(^:p0/:p4)|(^:p0/:p4)) ?x2 . ?x0 ((:p21/^:p21/:p22/^:p21)|(:p16/^:p23/:p23/^:p22)) ?x3 . ?x3 ((:p9/:p17/^:p22/:p4)|(:p9/:p4)|(:p22/^:p21/:p9/:p4)) ?x2 . } }
