PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 (((^:p15/:p15/^:p15/:p15))){,3} ?x1 . ?x0 ((^:p15/:p20/^:p20)|(^:p15/:p19/^:p19)|(^:p18/:p20/^:p17/:p0)) ?x2 . ?x2 ((:p19/^:p21)|(^:p2/:p15/^:p18)) ?x1 . }  UNION  {  } }
