PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x0 ?x3 WHERE {  {  ?x0 ((^:p5/^:p0/^:p2)|(:p16/^:p19/^:p2)) ?x1 . ?x0 ((:p6/^:p6/^:p13)) ?x2 . ?x1 ((^:p5/^:p3/:p10)|(^:p5/:p8/^:p13)|(:p6/^:p6/:p16/^:p24)) ?x3 . } }
