PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p10/:p3/:p4)) ?x1 . ?x0 ((:p25/^:p19/:p0/:p4)|(^:p10/:p3/:p4)|(^:p10/:p3/:p4)) ?x2 . ?x0 ((:p25/^:p17/:p6/^:p6)|(:p23/^:p20/:p0/:p4)) ?x3 . ?x0 ((^:p10/:p3/:p4)|(:p13/^:p8/:p4)|(^:p10/:p3/:p4)) ?x4 . } }
