PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 (((:p23/^:p16/:p16/^:p23)|(:p24/^:p24/:p24/^:p24)|(:p24/^:p24))){,3} ?x1 . ?x1 (((:p23/^:p26/:p26/^:p23)|(:p23/^:p23)|(:p24/^:p24))){,3} ?x2 . ?x0 (((:p13/^:p13/:p24)|(:p14/:p11/:p16)|(:p13/^:p8/:p19))){,3} ?x3 . ?x2 (((:p13/^:p13/:p23)|(:p13/^:p13/:p24))){,3} ?x4 . } }
