PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x1 ?x2 ?x0 WHERE {  {  ?x0 (((:p26/^:p16/:p22/^:p26)|(:p26/^:p26))){,3} ?x1 . ?x0 (((:p26/^:p24/:p23/^:p26)|(:p26/^:p23/:p23/^:p26)|(:p26/^:p26))){,3} ?x2 . ?x1 (((:p26/^:p21/:p15/^:p15)|(:p26/^:p26))){,3} ?x3 . } }
