PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p24/:p13/^:p8/:p1)|(^:p24/:p14/:p11)|(^:p24/:p13/:p11)) ?x1 . ?x1 (((:p16/^:p25/:p25/^:p16)|(:p16/^:p16)|(:p16/^:p26/:p26/^:p16))){,3} ?x2 . ?x2 ((:p16/^:p17/^:p9/:p15)|(:p16/^:p21/^:p2/:p15)) ?x3 . } }
