PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((^:p13/^:p13/:p16/^:p21)) ?x1 . ?x0 ((:p16/^:p16/^:p9)) ?x2 . ?x0 ((:p16/^:p16/^:p9)|(^:p13/:p16/^:p21)|(^:p13/:p16/^:p16/^:p6)) ?x3 . ?x0 ((^:p13/:p16/^:p17/^:p9)|(:p16/^:p16/^:p7/^:p6)) ?x4 . } }
