PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:p23/^:p23/:p25/^:p23)|(:p23/^:p25/:p24/^:p23)|(:p23/^:p24/:p23/^:p23))){,3} ?x1 . ?x1 ((:p23/^:p22/:p20)|(:p23/^:p22/:p20)) ?x2 . ?x2 (((^:p17/:p21/^:p16/:p16))){,3} ?x3 . ?x3 ((^:p17/:p20/^:p19)|(^:p22/:p22/^:p22/^:p0)|(^:p22/^:p8/:p15/^:p18)) ?x4 . }  UNION  {  }  UNION  {  } }
