PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:p16/^:p16/:p16/^:p16)|(:p16/^:p16))){,3} ?x1 . ?x1 ((:p16/^:p22/:p19)) ?x2 . ?x2 ((^:p24/:p13/^:p13)|(^:p20/:p20/^:p24)|(^:p17/:p8/^:p13)) ?x3 . } }
