PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 ((^:p24/:p14/^:p8/:p5)|(^:p24/:p13/:p6/^:p6)) ?x1 . ?x0 ((^:p24/:p14/^:p8/:p20)|(^:p24/:p13/:p11/:p16)) ?x2 . ?x1 ((^:p24/:p13/:p11/:p16)|(^:p24/:p14/^:p14/:p23)|(^:p24/:p13/^:p13/:p23)) ?x3 . } }
