PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p16/^:p22/:p22/^:p16)|(:p16/^:p25/:p25/^:p16))){,3} ?x1 . ?x1 (((:p16/^:p21/:p17/^:p16))){,3} ?x2 . ?x2 ((:p16/^:p19/:p19)) ?x3 . ?x3 ((^:p17/^:p0/:p8/^:p13)|(^:p23/:p14/^:p13)|(^:p23/:p13/^:p13)) ?x4 . }  UNION  {  } }
