PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 (((^:p21/:p17)|(^:p23/:p23/^:p16/:p21)|(^:p21/:p16))){,3} ?x1 . ?x0 (((^:p25/:p24/^:p23/:p25)|(^:p25/:p25/^:p17/:p22))){,3} ?x2 . ?x0 (((^:p16/:p21/^:p16/:p16)|(^:p23/:p23/^:p26/:p26))){,3} ?x3 . ?x0 (((^:p22/:p21))){,3} ?x4 . } }
