PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p24/^:p24/:p23/^:p23))){,3} ?x1 . ?x0 (((:p23/^:p23)|(:p23/^:p16/:p17/^:p23))){,3} ?x2 . ?x0 (((:p23/^:p25/:p24/^:p23)|(:p23/^:p16/:p16/^:p23))){,3} ?x3 . } }
