PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((^:p24/:p23/^:p17/^:p9)|(^:p24/:p23/^:p21/^:p9)|(^:p24/:p23/^:p17/^:p9)) ?x1 . ?x0 ((^:p24/:p23/^:p17/^:p9)|(^:p24/:p23/^:p21/^:p9)) ?x2 . ?x0 ((^:p24/:p23/^:p16/^:p9)) ?x3 . ?x0 ((^:p24/:p23/^:p21/^:p9)|(^:p24/:p23/^:p17/^:p9)) ?x4 . } }
