PREFIX : <http://example.org/gmark/> ASK {  {  ?x0 (((:p16/^:p16/:p16/^:p16)|(:p16/^:p25/:p24/^:p16)|(:p16/^:p23/:p25/^:p16))){,3} ?x1 . ?x1 (((:p16/^:p23/:p24/^:p16))){,3} ?x2 . ?x2 ((^:p5/:p18)|(^:p5/^:p9/:p15)|(^:p5/:p18)) ?x3 . ?x3 ((^:p15/:p21/^:p20)|(^:p15/:p22/^:p20)|(^:p15/:p22/^:p19)) ?x4 . } }
