PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x2 ?x3 ?x0 WHERE {  {  ?x0 (((^:p15/:p17/^:p17/:p15)|(^:p18/:p21/^:p21/:p18)|(^:p15/:p22/^:p21/:p15))){,3} ?x1 . ?x0 (((^:p15/:p21/^:p22/:p15)|(^:p15/:p22/^:p17/:p18)|(^:p18/:p18))){,3} ?x2 . ?x0 (((^:p15/:p15))){,3} ?x3 . ?x0 (((^:p15/:p18))){,3} ?x4 . }  UNION  {  } }
