PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 WHERE {  {  ?x0 ((:p13/:p9/:p8)|(^:p10/:p3/:p8)|(:p13/^:p13/:p14)) ?x1 . ?x0 ((:p23/^:p20/^:p9)) ?x2 . ?x0 ((:p13/:p9/^:p9)|(:p24/^:p16/^:p1/:p8)) ?x3 . } }
