PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 ?x3 WHERE {  {  ?x0 (((:p16/^:p16)|(:p16/^:p16))){,3} ?x1 . ?x1 (((:p16/^:p16)|(:p16/^:p16))){,3} ?x2 . ?x0 (((^:p5/^:p9)|(:p16/^:p17/:p20/^:p21))){,3} ?x3 . ?x2 (((^:p5/^:p9)|(^:p5/^:p9)|(^:p5/:p17/^:p21))){,3} ?x4 . } }
