PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x3 ?x0 ?x1 ?x2 WHERE {  {  ?x0 (((:p25/^:p16/:p16/^:p24))){,3} ?x1 . ?x0 (((:p25/^:p16/:p22/^:p25))){,3} ?x2 . ?x0 (((:p25/^:p17/:p21/^:p23)|(:p25/^:p25))){,3} ?x3 . } }
