PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:p25/^:p16/^:p5)|(:p24/^:p16/^:p6/^:p4)) ?x1 . ?x1 (((:p17/^:p16/:p17/^:p17)|(:p17/^:p21/:p17/^:p22))){,3} ?x2 . ?x2 ((:p15/^:p15/:p22/^:p16)|(:p17/^:p16)) ?x3 . ?x3 ((:p16/^:p23)|(:p16/^:p23)) ?x4 . } }
