PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((:p15/^:p15)|(:p15/^:p18/:p21/^:p26))){,3} ?x1 . ?x1 (((:p26/^:p21/:p17/^:p26)|(:p26/^:p23/:p23/^:p26))){,3} ?x2 . ?x0 (((:p15/^:p15/:p17/^:p26))){,3} ?x3 . ?x3 ((:p3/^:p0/:p6)|(:p2/:p20/^:p17/:p6)|(:p2/:p19/^:p16)) ?x2 . }  UNION  {  } }
