PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x1 ?x2 WHERE {  {  ?x0 ((:p3/:p20)) ?x1 . ?x0 ((:p3/:p19)|(:p3/:p20)) ?x2 . ?x0 ((:p3/:p20)|(:p2/^:p3/:p26)|(:p10/:p25/^:p19/:p19)) ?x3 . ?x0 ((:p26/^:p20/^:p0/:p21)|(:p3/:p19)) ?x4 . } }
