PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x3 WHERE {  {  ?x0 ((:p14/^:p8/^:p0)|(:p14/^:p8/:p20/^:p17)|(:p23/^:p20/^:p0)) ?x1 . ?x1 (((:p21/^:p16/:p16/^:p16)|(:p17/^:p21)|(:p16/^:p16))){,3} ?x2 . ?x2 (((:p21/^:p22/:p18/^:p18)|(:p16/^:p22/:p21/^:p16)|(:p21/^:p24/:p25/^:p17))){,3} ?x3 . } }
