PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p16/^:p20/:p22/^:p25)|(:p16/^:p20/:p22/^:p23)|(:p16/^:p20/:p22/^:p23)) ?x1 . ?x0 ((:p16/^:p19/:p21/^:p24)|(:p16/^:p19/:p21/^:p24)|(:p16/^:p19/:p16/^:p25)) ?x2 . ?x0 ((:p16/^:p19/:p16/^:p24)|(:p16/^:p20/:p22/^:p23)) ?x3 . ?x0 ((:p16/^:p20/:p16/^:p23)) ?x4 . } }
