PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x1 ?x0 ?x2 WHERE {  {  ?x0 ((:p16/^:p22/:p15/^:p15)|(:p16/^:p24/:p23/^:p22)|(:p16/^:p25/:p25/^:p22)) ?x1 . ?x1 ((:p20/^:p21/:p20/^:p16)) ?x2 . ?x0 ((:p16/^:p16/:p16/^:p16)|(:p16/^:p16)|(:p16/^:p21/:p17/^:p16)) ?x3 . ?x2 ((:p16/^:p21/:p22/^:p16)|(:p16/^:p24/:p25/^:p16)|(:p16/^:p21/:p21/^:p16)) ?x4 . }  UNION  {  } }
