PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 ((:p24/^:p16/:p16/^:p16)|(:p24/^:p22/:p17/^:p16)) ?x1 . ?x0 ((:p23/^:p16/:p16/^:p16)|(:p24/^:p22/:p21/^:p16)) ?x2 . ?x0 ((:p24/^:p16/:p16/^:p16)|(:p23/^:p16)) ?x3 . } }
