PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x2 ?x3 ?x1 ?x0 WHERE {  {  ?x0 (((:p16/^:p25/:p25/^:p16)|(:p16/^:p16/:p22/^:p16)|(:p16/^:p16))){,3} ?x1 . ?x1 (((:p16/^:p16)|(:p16/^:p16/:p16/^:p16)|(:p16/^:p21/:p16/^:p16))){,3} ?x2 . ?x2 (((:p16/^:p22/:p22/^:p16)|(:p16/^:p21/:p21/^:p16)|(:p16/^:p24/:p23/^:p16))){,3} ?x3 . ?x3 (((:p16/^:p16)|(:p16/^:p23/:p23/^:p16))){,3} ?x4 . } }
