PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 ?x2 WHERE {  {  ?x0 ((:p26/^:p20/:p16/^:p16)) ?x1 . ?x1 (((:p16/^:p26/:p26/^:p16)|(:p16/^:p21/:p21/^:p16))){,3} ?x2 . ?x0 ((:p2/:p19/^:p21/:p4)|(:p3/:p19/^:p16)|(:p2/^:p0/:p4)) ?x3 . ?x2 ((:p3/:p0/:p4)|(:p11/^:p1/:p4)) ?x4 . } }
