PREFIX : <http://example.org/gmark/> SELECT DISTINCT ?x0 WHERE {  {  ?x0 (((^:p21/:p22/^:p17/:p21)|(^:p22/:p22/^:p16/:p16))){,3} ?x1 . ?x1 ((^:p19/^:p0/:p18)|(^:p19/:p8/:p15)) ?x2 . ?x0 (((^:p20/^:p0)|(^:p16/^:p1/:p19/^:p21)|(^:p22/:p8/^:p8/:p0))){,3} ?x3 . ?x2 (((^:p20/:p22/^:p16/^:p5))){,3} ?x4 . }  UNION  {  }  UNION  {  } }
